use thiserror::Error;

use crate::{Real, quadrature::QuadratureError, sort::SortError};

/// Error returned by FEFF path helper routines.
#[derive(Debug, Clone, Copy, PartialEq, Error)]
#[non_exhaustive]
pub enum PathError {
    /// FEFF `ipack` supports at most eight path indices.
    #[error("path packing supports at most {max} indices, got {count}")]
    TooManyIndices { count: usize, max: usize },
    /// Individual packed indices must fit in FEFF's base-1290 digit.
    #[error("path index {position}={value} is outside 0..={max}")]
    IndexOutOfRange {
        position: usize,
        value: i32,
        max: i32,
    },
    /// FEFF `upack` uses an output capacity no larger than eight.
    #[error("path unpack capacity must be at most {max}, got {capacity}")]
    InvalidUnpackCapacity { capacity: usize, max: usize },
    /// The packed path contains more indices than the caller requested.
    #[error("packed path contains {packed_count} indices but capacity is {capacity}")]
    UnpackCapacityTooSmall {
        packed_count: usize,
        capacity: usize,
    },
    /// Packed integers generated by FEFF `ipack` are nonnegative.
    #[error("packed path integer {position} must be nonnegative, got {value}")]
    NegativePackedValue { position: usize, value: i32 },
    /// Heap keys and companion index arrays must have the same length.
    #[error("path heap length mismatch: keys has {keys_len}, indices has {indices_len}")]
    HeapLengthMismatch { keys_len: usize, indices_len: usize },
    /// Heap keys must be finite before ordering them.
    #[error("path heap key at index {index} must be finite, got {value}")]
    NonFiniteHeapKey { index: usize, value: Real },
    /// Atom positions must be an `natoms x 3` Cartesian table.
    #[error(
        "path atom positions must have at least 1 row and exactly 3 columns, got {rows}x{columns}"
    )]
    InvalidAtomPositionShape { rows: usize, columns: usize },
    /// Path atom indices must point into the provided position table.
    #[error(
        "path atom at path position {position} references atom {atom_index}, but only {atoms} atoms are available"
    )]
    AtomIndexOutOfRange {
        position: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// Coordinates used for path geometry must be finite.
    #[error("path atom {atom_index} coordinate {component} must be finite, got {value}")]
    NonFiniteAtomPosition {
        atom_index: usize,
        component: usize,
        value: Real,
    },
    /// Path hash positions must align with one potential index per path atom.
    #[error(
        "path hash positions must be npath x 3 with one potential per row, got {rows}x{columns} and {potentials} potentials"
    )]
    InvalidPathHashShape {
        rows: usize,
        columns: usize,
        potentials: usize,
    },
    /// FEFF path potential indices are nonnegative.
    #[error("path hash potential at position {position} must be nonnegative, got {value}")]
    NegativePathPotential { position: usize, value: i32 },
    /// Atom potential IDs must fit FEFF's signed path-hash integer.
    #[error("path hash potential at position {position}={potential} is too large")]
    PathHashPotentialOutOfRange { position: usize, potential: usize },
    /// Coordinates used by FEFF `phash` must fit its single-precision NINT scale.
    #[error(
        "path hash coordinate at position {position} component {component} must fit FEFF NINT scale, got {value}"
    )]
    PathHashCoordinateOutOfRange {
        position: usize,
        component: usize,
        value: Real,
    },
    /// Path criteria need at least one path atom.
    #[error("path criteria require at least one path atom")]
    EmptyPathCriteria,
    /// Criteria arrays must align with FEFF `npat + 1` leg arrays.
    #[error(
        "path criteria expected {expected} leg/beta entries, got {leg_distances} distances and {beta_entries} beta entries"
    )]
    PathCriteriaLengthMismatch {
        expected: usize,
        leg_distances: usize,
        beta_entries: usize,
    },
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` must be centered on zero beta.
    #[error(
        "path criteria fbetac table must have odd beta rows and nonzero potential/criteria dimensions, got {beta_rows}x{potentials}x{criteria}"
    )]
    InvalidPathCriteriaTableShape {
        beta_rows: usize,
        potentials: usize,
        criteria: usize,
    },
    /// The number of criteria energies must fit the table.
    #[error(
        "path criteria wave-number count {wave_numbers} is invalid for fbetac criteria dimension {table_criteria}"
    )]
    PathCriteriaWaveCountMismatch {
        wave_numbers: usize,
        table_criteria: usize,
    },
    /// `mcritk` needs one mean-free path per criteria energy.
    #[error("path criteria has {wave_numbers} wave numbers but {mean_free_paths} mean-free paths")]
    PathCriteriaMeanFreePathCountMismatch {
        wave_numbers: usize,
        mean_free_paths: usize,
    },
    /// Path atom indices must point into the provided potential table.
    #[error(
        "path criteria atom at position {position} references atom {atom_index}, but only {atoms} atom potentials are available"
    )]
    PathCriteriaAtomIndexOutOfRange {
        position: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// Potential indices must point into the FEFF `fbetac` potential dimension.
    #[error(
        "path criteria atom at position {position} uses potential {potential}, but fbetac has {potentials} potentials"
    )]
    PathCriteriaPotentialOutOfRange {
        position: usize,
        potential: usize,
        potentials: usize,
    },
    /// Beta-bin indices must fit the centered FEFF `fbetac` beta dimension.
    #[error(
        "path criteria beta index at position {position} is {beta_index}, outside {min}..={max}"
    )]
    PathCriteriaBetaIndexOutOfRange {
        position: usize,
        beta_index: i32,
        min: i32,
        max: i32,
    },
    /// Floating-point criteria inputs must be finite.
    #[error("path criteria {quantity} at index {index} must be finite, got {value}")]
    NonFinitePathCriteriaValue {
        quantity: &'static str,
        index: usize,
        value: Real,
    },
    /// Divisors in criteria calculations must be positive.
    #[error("path criteria {quantity} at index {index} must be positive, got {value}")]
    NonPositivePathCriteriaValue {
        quantity: &'static str,
        index: usize,
        value: Real,
    },
    /// Cluster flags must contain every path atom index.
    #[error(
        "path criteria atom at position {position} references cluster flag {atom_index}, but only {atoms} flags are available"
    )]
    PathCriteriaClusterIndexOutOfRange {
        position: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// FEFF `paths.f90` expects one potential and first-bounce flag per atom.
    #[error(
        "pathfinder preparation length mismatch: positions={positions}, potentials={potentials}, first_bounce_degeneracies={first_bounce_degeneracies}"
    )]
    PathfinderPreparationLengthMismatch {
        positions: usize,
        potentials: usize,
        first_bounce_degeneracies: usize,
    },
    /// FEFF `paths.f90` needs one absorber potential, `ipot == 0`.
    #[error("pathfinder preparation found no absorber atom with potential index 0")]
    PathfinderMissingAbsorber,
    /// FEFF `paths.f90` needs at least one allowed first-bounce atom.
    #[error(
        "pathfinder preparation found no non-absorber atoms with positive first-bounce degeneracy"
    )]
    PathfinderMissingFirstBounce,
    /// FEFF `paths.f90` requires a finite FMS radius.
    #[error("pathfinder preparation FMS radius must be finite, got {value}")]
    NonFinitePathfinderFmsRadius { value: Real },
    /// Sorting FEFF pathfinder neighbor rows failed.
    #[error("pathfinder neighbor row {row} sort failed: {source}")]
    PathfinderNeighborSort { row: isize, source: SortError },
    /// FEFF pathfinder search limits must be positive where required.
    #[error("pathfinder search {quantity} must be positive, got {value}")]
    InvalidPathfinderSearchLimit {
        quantity: &'static str,
        value: usize,
    },
    /// Rust heap node indices must fit the companion heap array representation.
    #[error("pathfinder heap has too many nodes to index: {nodes}")]
    PathfinderHeapNodeOverflow { nodes: usize },
    /// FEFF `fbeta` output table must be centered on zero beta.
    #[error(
        "path importance fbeta table must have odd beta rows and nonzero potential/energy dimensions, got {beta_rows}x{potentials}x{energies}"
    )]
    InvalidPathImportanceTableShape {
        beta_rows: usize,
        potentials: usize,
        energies: usize,
    },
    /// The number of output energies must fit the `fbeta` table.
    #[error(
        "path importance wave-number count {wave_numbers} is invalid for fbeta energy dimension {table_energies}"
    )]
    PathImportanceEnergyCountMismatch {
        wave_numbers: usize,
        table_energies: usize,
    },
    /// `outcrt` needs one mean-free path per output energy.
    #[error(
        "path importance has {wave_numbers} wave numbers but {mean_free_paths} mean-free paths"
    )]
    PathImportanceMeanFreePathCountMismatch {
        wave_numbers: usize,
        mean_free_paths: usize,
    },
    /// FEFF `strap` needs at least two output points beginning at `ik0`.
    #[error(
        "path importance start energy {start} leaves {remaining} points, but at least 2 are required"
    )]
    PathImportanceStartOutOfRange { start: usize, remaining: usize },
    /// Numerical integration failed while calculating FEFF `xport`.
    #[error("path importance integration failed: {0}")]
    PathImportanceIntegration(QuadratureError),
    /// FEFF `mpprmp` symmetry-case override must be one of the documented cases.
    #[error("path standard-frame symmetry case must be in 1..=7, got {symmetry_case}")]
    InvalidPathSymmetryCase { symmetry_case: u8 },
    /// Standard-frame direction vectors must be finite.
    #[error("path standard-frame {vector} component {component} must be finite, got {value}")]
    NonFinitePathStandardVector {
        vector: &'static str,
        component: usize,
        value: Real,
    },
    /// FEFF case 1 needs a nonzero first leg to define the path axis.
    #[error("path standard-frame case {symmetry_case} cannot define a nonzero z axis")]
    DegeneratePathStandardAxis { symmetry_case: u8 },
    /// FEFF `prcrit` needs aligned energy, phase, and angular-limit tables.
    #[error(
        "path phase criteria shape mismatch: energies={energies}, references={references}, phase={phase_energies}x{phase_angular}x{phase_potentials}, limits={limit_energies}x{limit_potentials}"
    )]
    InvalidPathPhaseCriteriaShape {
        energies: usize,
        references: usize,
        phase_energies: usize,
        phase_angular: usize,
        phase_potentials: usize,
        limit_energies: usize,
        limit_potentials: usize,
    },
    /// FEFF `neout` must fit the phase energy grid.
    #[error(
        "path phase criteria output energy count {output_energy_count} is invalid for {energies} energies"
    )]
    PathPhaseOutputEnergyOutOfRange {
        output_energy_count: usize,
        energies: usize,
    },
    /// FEFF `ik0` must point into the phase energy grid.
    #[error("path phase criteria zero-wave energy index {index} is outside {energies} energies")]
    PathPhaseZeroWaveIndexOutOfRange { index: usize, energies: usize },
    /// FEFF `lmax` entries must fit the phase-shift angular dimension.
    #[error(
        "path phase criteria lmax({energy},{potential})={angular_limit} exceeds angular dimension {angular_channels}"
    )]
    PathPhaseAngularLimitOutOfRange {
        energy: usize,
        potential: usize,
        angular_limit: usize,
        angular_channels: usize,
    },
    /// Complex path phase criteria inputs must be finite.
    #[error(
        "path phase criteria {quantity}({energy},{angular},{potential}) must be finite, got {real}+{imaginary}i"
    )]
    NonFinitePathPhaseComplex {
        quantity: &'static str,
        energy: usize,
        angular: usize,
        potential: usize,
        real: Real,
        imaginary: Real,
    },
    /// Derived FEFF `prcrit` scalar values must be finite.
    #[error("path phase criteria {quantity} at energy {energy} must be finite, got {value}")]
    NonFinitePathPhaseScalar {
        quantity: &'static str,
        energy: usize,
        value: Real,
    },
    /// At least one critical energy must be available.
    #[error("path phase criteria found no critical energies from zero-wave index {index}")]
    NoPathPhaseCriticalEnergies { index: usize },
    /// FEFF `pathsd` first-bounce degeneracy table must cover every first path atom.
    #[error(
        "path degeneracy candidate {candidate} starts at atom {atom_index}, but only {atoms} first-bounce degeneracies are available"
    )]
    PathDegeneracyFirstBounceOutOfRange {
        candidate: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// FEFF `pathsd` expects equal-hash paths to be truly degenerate.
    #[error(
        "path degeneracy hash collision between candidates {first_candidate} and {second_candidate}"
    )]
    PathDegeneracyHashCollision {
        first_candidate: usize,
        second_candidate: usize,
    },
    /// Summing FEFF `i1b` first-bounce factors overflowed Rust's `usize`.
    #[error("path degeneracy sum overflowed while adding candidate {candidate}")]
    PathDegeneracyOverflow { candidate: usize },
    /// Sorting FEFF `pathsd` degeneracy hashes failed.
    #[error("path degeneracy hash sort failed: {source}")]
    PathDegeneracyHashSort { source: SortError },
    /// FEFF `pathsd` retention needs one `xport` per unique path group.
    #[error(
        "path degeneracy retention has {groups} groups but {port_importances} port importances"
    )]
    PathDegeneracyRetentionLengthMismatch {
        groups: usize,
        port_importances: usize,
    },
    /// FEFF `pathsd` retention percentages and importance values must be finite.
    #[error("path degeneracy retention {quantity} at index {index} must be finite, got {value}")]
    NonFinitePathDegeneracyRetentionValue {
        quantity: &'static str,
        index: usize,
        value: Real,
    },
    /// FEFF `pathsd` degeneracy sums use positive first-bounce counts.
    #[error("path degeneracy group {index} must have positive degeneracy, got {degeneracy}")]
    NonPositivePathDegeneracy { index: usize, degeneracy: usize },
    /// FEFF `pathsd` cannot form a relative path-importance fraction from a zero reference.
    #[error("path degeneracy retention reference at group {index} has zero port importance")]
    ZeroPathDegeneracyRetentionReference { index: usize },
    /// FEFF `pathsd` retained-path reference must be finite and positive.
    #[error(
        "path degeneracy retention reference {quantity} must be finite and positive, got {value}"
    )]
    InvalidPathDegeneracyRetentionReference { quantity: &'static str, value: Real },
    /// FEFF `pathsd` retained-path reference degeneracy must be positive.
    #[error("path degeneracy retention reference degeneracy must be positive, got {degeneracy}")]
    InvalidPathDegeneracyRetentionReferenceDegeneracy { degeneracy: usize },
    /// Summing retained FEFF path degeneracies overflowed Rust's `usize`.
    #[error("retained path degeneracy sum overflowed while adding group {index}")]
    PathDegeneracyRetentionOverflow { index: usize },
    /// FEFF `pathsd` candidate path lengths must be finite.
    #[error("path degeneracy record {record} has non-finite total path length {value}")]
    NonFinitePathDegeneracyRecordLength { record: usize, value: Real },
    /// Summing retained FEFF path counts across ranges overflowed Rust's `usize`.
    #[error("path degeneracy reduction count overflowed while adding range {range}")]
    PathDegeneracyReductionOverflow { range: usize },
}
