use ndarray::{Array2, Array3, ArrayView2, ArrayView3};

use crate::{Complex, Real};

/// Distances and angle cosines generated by FEFF `mrb`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathGeometry {
    /// FEFF `ri`: leg lengths for each path point, including return to absorber.
    pub leg_distances: Vec<Real>,
    /// FEFF `beta`: cosines of scattering angles at each path point.
    pub angle_cosines: Vec<Real>,
    /// Sum of `leg_distances`, matching FEFF's local `rpath`.
    pub total_path_length: Real,
}

/// Output path parameters generated by FEFF `mpprmd`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathOutputParameters {
    /// FEFF `ri`: leg distances for each path point, including return to absorber.
    pub leg_distances: Vec<Real>,
    /// FEFF `beta`: scattering angles in radians, not angle cosines.
    pub scattering_angles: Vec<Real>,
    /// FEFF `eta`: phase angles formed from adjacent Euler-angle factors.
    pub eta_angles: Vec<Real>,
}

/// Phase-derived path criteria tables generated by FEFF `prcrit`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathPhaseCriteriaTables {
    /// FEFF `neout`, the output-energy count advertised to PATH.
    pub output_energy_count: usize,
    /// Zero-based equivalent of FEFF `ik0out`.
    pub zero_wave_energy_index: usize,
    /// FEFF `cksp(1:ne)`: real wave numbers in inverse angstroms.
    pub wave_numbers: Vec<Real>,
    /// FEFF `xlam(1:ne)`: mean free paths in angstroms.
    pub mean_free_paths: Vec<Real>,
    /// FEFF `fbeta(-40:40,0:npot,1:ne)` as `(81, potentials, energies)`.
    pub fbeta: Array3<Real>,
    /// Zero-based energy indices selected for FEFF critical criteria.
    pub critical_energy_indices: Vec<usize>,
    /// FEFF `ckspc(1:nncrit)`.
    pub critical_wave_numbers: Vec<Real>,
    /// FEFF `xlamc(1:nncrit)`.
    pub critical_mean_free_paths: Vec<Real>,
    /// FEFF `fbetac(-40:40,0:npot,1:nncrit)`.
    pub fbeta_critical: Array3<Real>,
}

/// Inputs for the computational core of FEFF `prcrit`.
#[derive(Debug, Clone, Copy)]
pub struct PathPhaseCriteriaInput<'a> {
    /// FEFF `em(1:ne)` complex energy grid.
    pub energies: &'a [Complex],
    /// FEFF `eref(1:ne)` complex reference energies for the selected spin.
    pub reference_energies: &'a [Complex],
    /// FEFF `ph(1:ne,1:lmaxp1,0:npot)` phase shifts.
    pub phase_shifts: ArrayView3<'a, Complex>,
    /// FEFF `lmax(1:ne,0:npot)` inclusive angular limits.
    pub angular_limits: ArrayView2<'a, usize>,
    /// FEFF `neout`.
    pub output_energy_count: usize,
    /// Zero-based equivalent of FEFF `ik0`.
    pub zero_wave_energy_index: usize,
}

/// Result of FEFF `mcritk` output-importance calculation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathOutputCriterion {
    /// Output importance factor, or `None` for FEFF's undefined `xout = -1`.
    pub output_importance: Option<Real>,
    /// Updated `xcalcx` normalization. FEFF initializes it from `xcalc` when
    /// the input value is nonpositive.
    pub normalization: Real,
}

/// Inputs for FEFF `mcritk` output-importance calculation.
#[derive(Debug, Clone, Copy)]
pub struct PathOutputCriterionInput<'a> {
    /// FEFF `ipat(1:npat)`: path atom indices, with `0` as absorber.
    pub path_indices: &'a [usize],
    /// FEFF `ri(1:npat+1)`: path leg distances.
    pub leg_distances: &'a [Real],
    /// FEFF `beta(1:npat+1)`: path angle cosines.
    pub angle_cosines: &'a [Real],
    /// FEFF `indbet(1:npat+1)`: discretized beta bins for `fbetac`.
    pub beta_indices: &'a [i32],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` laid out as
    /// `(2 * nbeta + 1, nph + 1, necrit)`.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `xlamc(1:nncrit)`: mean-free paths for criteria energies.
    pub mean_free_paths: &'a [Real],
    /// FEFF `ckspc(1:nncrit)`: wave numbers for criteria energies.
    pub wave_numbers: &'a [Real],
    /// FEFF `xcalcx`: normalization updated when nonpositive.
    pub current_normalization: Real,
}

/// Result of FEFF `ccrit` heap/output decision for a path.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathCriteriaDecision {
    /// FEFF `rpath`: total closed path length.
    pub total_path_length: Real,
    /// FEFF `lheap`: whether this path remains in the pathfinder heap.
    pub add_to_heap: bool,
    /// FEFF `lkeep`: whether this path should be retained for output.
    pub keep_for_output: bool,
    /// Updated FEFF `xcalcx` normalization.
    pub normalization: Real,
    /// FEFF `xheap` when evaluated; `None` if undefined or skipped.
    pub heap_importance: Option<Real>,
    /// FEFF `xout` when evaluated; `None` if undefined or skipped.
    pub output_importance: Option<Real>,
}

/// Inputs for FEFF `ccrit` pathfinder heap/output decision.
#[derive(Debug, Clone, Copy)]
pub struct PathCriteriaDecisionInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// Atom-indexed cluster flags; `true` means outside the FMS cluster.
    pub cluster_outside: &'a [bool],
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `xlamc(1:nncrit)`: mean-free paths for criteria energies.
    pub mean_free_paths: &'a [Real],
    /// FEFF `ckspc(1:nncrit)`: wave numbers for criteria energies.
    pub wave_numbers: &'a [Real],
    /// FEFF `rmax`: maximum closed path length.
    pub max_path_length: Real,
    /// FEFF `pcrith`: heap cutoff; nonpositive disables heap criterion.
    pub heap_cutoff: Real,
    /// FEFF `pcritk`: output cutoff; nonpositive skips output criterion.
    pub output_cutoff: Real,
    /// FEFF `xcalcx`: output normalization updated when needed.
    pub current_normalization: Real,
}

/// Result of FEFF `outcrt` output-path importance recalculation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathOutputImportance {
    /// FEFF `xport`: integrated path importance over the output energy grid.
    pub port_importance: Real,
    /// FEFF `xheap`: heap importance for the path in its current direction.
    pub heap_importance: Option<Real>,
    /// FEFF `xheapr`: heap importance for the time-reversed path.
    pub reversed_heap_importance: Option<Real>,
    /// FEFF `xout`: output keep importance from `mcritk`.
    pub output_importance: Option<Real>,
    /// Updated FEFF `xcalcx` normalization.
    pub normalization: Real,
}

/// Inputs for FEFF `outcrt` output-path importance recalculation.
#[derive(Debug, Clone, Copy)]
pub struct PathOutputImportanceInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `fbeta(-nbeta:nbeta, 0:nph, 1:ne)` output-energy table.
    pub fbeta: ArrayView3<'a, Real>,
    /// FEFF `cksp(1:ne)`: output wave numbers.
    pub wave_numbers: &'a [Real],
    /// FEFF `xlam(1:ne)`: output mean-free paths.
    pub mean_free_paths: &'a [Real],
    /// Zero-based equivalent of FEFF `ik0`, the first energy to integrate.
    pub start_energy_index: usize,
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, 1:nncrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `ckspc(1:nncrit)`: criteria wave numbers.
    pub critical_wave_numbers: &'a [Real],
    /// FEFF `xlamc(1:nncrit)`: criteria mean-free paths.
    pub critical_mean_free_paths: &'a [Real],
    /// FEFF `xcalcx`: output normalization updated when needed.
    pub current_normalization: Real,
}

/// Standard-frame coordinates generated by FEFF `mpprmp`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathStandardCoordinates {
    /// Path atom coordinates in the selected standard frame, as `npat x 3`.
    pub coordinates: Array2<Real>,
    /// FEFF symmetry case selected by `mpprmp`, in the range `1..=7`.
    pub symmetry_case: u8,
}

/// Inputs for FEFF `mpprmp` standard-frame path coordinates.
#[derive(Debug, Clone, Copy)]
pub struct PathStandardCoordinatesInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
}

/// Canonical path representation generated by FEFF `timrep`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathCanonicalRepresentation {
    /// Path atom indices in the selected canonical direction.
    pub path_indices: Vec<usize>,
    /// Canonical standard-frame coordinates as `npat x 3`.
    pub coordinates: Array2<Real>,
    /// FEFF `dhash` key for degeneracy grouping.
    pub degeneracy_hash: Real,
    /// Whether the input path was time-reversed to reach canonical order.
    pub reversed: bool,
    /// FEFF symmetry case used by `mpprmp` while building coordinates.
    pub symmetry_case: u8,
}

/// Inputs for FEFF `timrep` canonical time-reversal representation.
#[derive(Debug, Clone, Copy)]
pub struct PathCanonicalRepresentationInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
    /// Force FEFF case 7 when EELS or NRIXS disables symmetry operations.
    pub force_no_symmetry: bool,
}
