use ndarray::{Array2, Array3, ArrayView2, ArrayView3};

use crate::{Complex, Real};

/// Distances and angle cosines generated by FEFF `mrb`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathGeometry {
    /// FEFF `ri`: leg lengths for each path point, including return to absorber.
    pub leg_distances: Vec<Real>,
    /// FEFF `beta`: cosines of scattering angles at each path point.
    pub angle_cosines: Vec<Real>,
    /// Sum of `leg_distances`, matching FEFF's local `rpath`.
    pub total_path_length: Real,
}

/// Output path parameters generated by FEFF `mpprmd`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathOutputParameters {
    /// FEFF `ri`: leg distances for each path point, including return to absorber.
    pub leg_distances: Vec<Real>,
    /// FEFF `beta`: scattering angles in radians, not angle cosines.
    pub scattering_angles: Vec<Real>,
    /// FEFF `eta`: phase angles formed from adjacent Euler-angle factors.
    pub eta_angles: Vec<Real>,
}

/// Phase-derived path criteria tables generated by FEFF `prcrit`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathPhaseCriteriaTables {
    /// FEFF `neout`, the output-energy count advertised to PATH.
    pub output_energy_count: usize,
    /// Zero-based equivalent of FEFF `ik0out`.
    pub zero_wave_energy_index: usize,
    /// FEFF `cksp(1:ne)`: real wave numbers in inverse angstroms.
    pub wave_numbers: Vec<Real>,
    /// FEFF `xlam(1:ne)`: mean free paths in angstroms.
    pub mean_free_paths: Vec<Real>,
    /// FEFF `fbeta(-40:40,0:npot,1:ne)` as `(81, potentials, energies)`.
    pub fbeta: Array3<Real>,
    /// Zero-based energy indices selected for FEFF critical criteria.
    pub critical_energy_indices: Vec<usize>,
    /// FEFF `ckspc(1:nncrit)`.
    pub critical_wave_numbers: Vec<Real>,
    /// FEFF `xlamc(1:nncrit)`.
    pub critical_mean_free_paths: Vec<Real>,
    /// FEFF `fbetac(-40:40,0:npot,1:nncrit)`.
    pub fbeta_critical: Array3<Real>,
}

/// Inputs for the computational core of FEFF `prcrit`.
#[derive(Debug, Clone, Copy)]
pub struct PathPhaseCriteriaInput<'a> {
    /// FEFF `em(1:ne)` complex energy grid.
    pub energies: &'a [Complex],
    /// FEFF `eref(1:ne)` complex reference energies for the selected spin.
    pub reference_energies: &'a [Complex],
    /// FEFF `ph(1:ne,1:lmaxp1,0:npot)` phase shifts.
    pub phase_shifts: ArrayView3<'a, Complex>,
    /// FEFF `lmax(1:ne,0:npot)` inclusive angular limits.
    pub angular_limits: ArrayView2<'a, usize>,
    /// FEFF `neout`.
    pub output_energy_count: usize,
    /// Zero-based equivalent of FEFF `ik0`.
    pub zero_wave_energy_index: usize,
}

/// Result of FEFF `mcritk` output-importance calculation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathOutputCriterion {
    /// Output importance factor, or `None` for FEFF's undefined `xout = -1`.
    pub output_importance: Option<Real>,
    /// Updated `xcalcx` normalization. FEFF initializes it from `xcalc` when
    /// the input value is nonpositive.
    pub normalization: Real,
}

/// Inputs for FEFF `mcritk` output-importance calculation.
#[derive(Debug, Clone, Copy)]
pub struct PathOutputCriterionInput<'a> {
    /// FEFF `ipat(1:npat)`: path atom indices, with `0` as absorber.
    pub path_indices: &'a [usize],
    /// FEFF `ri(1:npat+1)`: path leg distances.
    pub leg_distances: &'a [Real],
    /// FEFF `beta(1:npat+1)`: path angle cosines.
    pub angle_cosines: &'a [Real],
    /// FEFF `indbet(1:npat+1)`: discretized beta bins for `fbetac`.
    pub beta_indices: &'a [i32],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` laid out as
    /// `(2 * nbeta + 1, nph + 1, necrit)`.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `xlamc(1:nncrit)`: mean-free paths for criteria energies.
    pub mean_free_paths: &'a [Real],
    /// FEFF `ckspc(1:nncrit)`: wave numbers for criteria energies.
    pub wave_numbers: &'a [Real],
    /// FEFF `xcalcx`: normalization updated when nonpositive.
    pub current_normalization: Real,
}

/// Result of FEFF `ccrit` heap/output decision for a path.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathCriteriaDecision {
    /// FEFF `rpath`: total closed path length.
    pub total_path_length: Real,
    /// FEFF `lheap`: whether this path remains in the pathfinder heap.
    pub add_to_heap: bool,
    /// FEFF `lkeep`: whether this path should be retained for output.
    pub keep_for_output: bool,
    /// Updated FEFF `xcalcx` normalization.
    pub normalization: Real,
    /// FEFF `xheap` when evaluated; `None` if undefined or skipped.
    pub heap_importance: Option<Real>,
    /// FEFF `xout` when evaluated; `None` if undefined or skipped.
    pub output_importance: Option<Real>,
}

/// Inputs for FEFF `ccrit` pathfinder heap/output decision.
#[derive(Debug, Clone, Copy)]
pub struct PathCriteriaDecisionInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// Atom-indexed cluster flags; `true` means outside the FMS cluster.
    pub cluster_outside: &'a [bool],
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `xlamc(1:nncrit)`: mean-free paths for criteria energies.
    pub mean_free_paths: &'a [Real],
    /// FEFF `ckspc(1:nncrit)`: wave numbers for criteria energies.
    pub wave_numbers: &'a [Real],
    /// FEFF `rmax`: maximum closed path length.
    pub max_path_length: Real,
    /// FEFF `pcrith`: heap cutoff; nonpositive disables heap criterion.
    pub heap_cutoff: Real,
    /// FEFF `pcritk`: output cutoff; nonpositive skips output criterion.
    pub output_cutoff: Real,
    /// FEFF `xcalcx`: output normalization updated when needed.
    pub current_normalization: Real,
}

/// Inputs for the FEFF `paths.f90` pathfinder preparation stage.
#[derive(Debug, Clone, Copy)]
pub struct PathfinderPreparationInput<'a> {
    /// Cartesian atom coordinates in Angstroms before FEFF absorber normalization.
    pub atom_positions: ArrayView2<'a, Real>,
    /// Potential index for each atom, equivalent to FEFF `iphat`.
    pub atom_potentials: &'a [usize],
    /// First-bounce degeneracy flags for each atom, equivalent to FEFF `ibounc`.
    pub first_bounce_degeneracies: &'a [usize],
    /// FEFF `rfms`; atoms farther than this from the absorber are outside the FMS cluster.
    pub fms_radius: Real,
}

/// Prepared atom and neighbor tables for FEFF `paths.f90`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathfinderPreparation {
    /// Single-precision-normalized coordinates with the absorber in row `0`.
    pub atom_positions: Array2<Real>,
    /// Potential indices after FEFF's absorber row permutation.
    pub atom_potentials: Vec<usize>,
    /// FEFF `i1b` after setting row `0` to zero; not permuted by `paths.f90`.
    pub first_bounce_degeneracies: Vec<usize>,
    /// FEFF `iclus`: `true` means the atom is outside the FMS cluster.
    pub cluster_outside: Vec<bool>,
    /// Original input row that supplied the absorber moved to row `0`.
    pub absorber_source_index: usize,
    /// FEFF `m(-1,0:nat)`: first-bounce candidates sorted by return distance.
    pub first_bounce_neighbors: Vec<usize>,
    /// FEFF `m(0:nat,0:nat)`: per-last-atom extension candidates.
    pub neighbor_rows: Vec<Vec<usize>>,
    /// Number of non-absorber atoms with positive first-bounce degeneracy.
    pub first_bounce_count: usize,
}

/// One owned candidate emitted by the FEFF `paths.f90` heap search.
#[derive(Debug, Clone, PartialEq)]
pub struct PathfinderRecord {
    /// FEFF `r0`: total closed path length.
    pub total_path_length: Real,
    /// FEFF `ipat(1:npat)` path atom indices.
    pub path_indices: Vec<usize>,
}

/// Inputs for the FEFF `paths.f90` heap search.
#[derive(Debug, Clone, Copy)]
pub struct PathfinderSearchInput<'a> {
    /// Prepared atom and neighbor data from `pathfinder_preparation`.
    pub preparation: &'a PathfinderPreparation,
    /// FEFF doubled `rmax`: maximum total closed path length.
    pub max_path_length: Real,
    /// FEFF `npatxx`: maximum number of scattering atoms in a path.
    pub max_path_atoms: usize,
    /// FEFF `npx`: maximum number of output candidates to emit.
    pub max_output_paths: usize,
    /// FEFF `pcrith`: heap cutoff; nonpositive disables heap criterion.
    pub heap_cutoff: Real,
    /// FEFF `pcritk`: output cutoff; nonpositive skips output criterion.
    pub output_cutoff: Real,
    /// FEFF `fbetac(-nbeta:nbeta,0:nph,1:nncrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `ckspc(1:nncrit)`: criteria wave numbers.
    pub critical_wave_numbers: &'a [Real],
    /// FEFF `xlamc(1:nncrit)`: criteria mean-free paths.
    pub critical_mean_free_paths: &'a [Real],
    /// Incoming FEFF `xcalcx` normalization.
    pub current_normalization: Real,
}

/// Result of the FEFF `paths.f90` heap search.
#[derive(Debug, Clone, PartialEq)]
pub struct PathfinderSearch {
    /// Candidate records in the order FEFF writes them to `paths.bin`.
    pub records: Vec<PathfinderRecord>,
    /// Updated FEFF `xcalcx` normalization.
    pub normalization: Real,
    /// Maximum heap size reached during the search.
    pub max_heap_size: usize,
    /// Maximum path atom count reached at the heap root.
    pub max_path_atoms_reached: usize,
    /// Number of rejected heap candidates, matching FEFF's `nna` counter.
    pub skipped_count: usize,
    /// Whether the heap was exhausted without hitting output or length limits.
    pub complete: bool,
}

/// Inputs for the FEFF PATH core through `paths.f90` search and `pathsd` reduction.
#[derive(Debug, Clone, Copy)]
pub struct PathfinderReductionInput<'a> {
    /// Cartesian atom coordinates in Angstroms before FEFF absorber normalization.
    pub atom_positions: ArrayView2<'a, Real>,
    /// Potential index for each atom, equivalent to FEFF `iphat`.
    pub atom_potentials: &'a [usize],
    /// First-bounce degeneracy flags for each atom, equivalent to FEFF `ibounc`.
    pub first_bounce_degeneracies: &'a [usize],
    /// FEFF `rfms`; atoms farther than this from the absorber are outside the FMS cluster.
    pub fms_radius: Real,
    /// FEFF doubled `rmax`: maximum total closed path length.
    pub max_path_length: Real,
    /// FEFF `npatxx`: maximum number of scattering atoms in a path.
    pub max_path_atoms: usize,
    /// FEFF `npx`: maximum number of output candidates to emit.
    pub max_output_paths: usize,
    /// FEFF `pcrith`: heap cutoff; nonpositive disables heap criterion.
    pub heap_cutoff: Real,
    /// FEFF `pcritk`: output cutoff; nonpositive skips output criterion.
    pub output_cutoff: Real,
    /// Incoming FEFF `paths.f90` `xcalcx` normalization.
    pub search_normalization: Real,
    /// FEFF `fbeta(-nbeta:nbeta,0:nph,1:ne)` output-energy table.
    pub fbeta: ArrayView3<'a, Real>,
    /// FEFF `cksp(1:ne)`: output wave numbers.
    pub wave_numbers: &'a [Real],
    /// FEFF `xlam(1:ne)`: output mean-free paths.
    pub mean_free_paths: &'a [Real],
    /// Zero-based equivalent of FEFF `ik0`.
    pub start_energy_index: usize,
    /// FEFF `fbetac(-nbeta:nbeta,0:nph,1:nncrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `ckspc(1:nncrit)`: criteria wave numbers.
    pub critical_wave_numbers: &'a [Real],
    /// FEFF `xlamc(1:nncrit)`: criteria mean-free paths.
    pub critical_mean_free_paths: &'a [Real],
    /// Incoming FEFF `pathsd` `xcalcx` normalization.
    pub reduction_normalization: Real,
    /// FEFF `critpw`: retain paths whose relative importance is at least this percent.
    pub criterion_percent: Real,
    /// Existing FEFF `xportx`/`ndegx` reference from a previous reduction.
    pub retention_reference: Option<PathDegeneracyRetentionReference>,
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
    /// Force FEFF case 7 when EELS or NRIXS disables symmetry operations.
    pub force_no_symmetry: bool,
}

/// Output of the FEFF PATH core through heap search and degeneracy reduction.
#[derive(Debug, Clone, PartialEq)]
pub struct PathfinderReduction {
    /// Prepared atom and neighbor state used by the heap search.
    pub preparation: PathfinderPreparation,
    /// Candidate records emitted by the FEFF `paths.f90` search.
    pub search: PathfinderSearch,
    /// Reduced unique path groups from the FEFF `pathsd` pass.
    pub reduction: PathDegeneracyReduction,
}

/// Result of FEFF `outcrt` output-path importance recalculation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathOutputImportance {
    /// FEFF `xport`: integrated path importance over the output energy grid.
    pub port_importance: Real,
    /// FEFF `xheap`: heap importance for the path in its current direction.
    pub heap_importance: Option<Real>,
    /// FEFF `xheapr`: heap importance for the time-reversed path.
    pub reversed_heap_importance: Option<Real>,
    /// FEFF `xout`: output keep importance from `mcritk`.
    pub output_importance: Option<Real>,
    /// Updated FEFF `xcalcx` normalization.
    pub normalization: Real,
}

/// Inputs for FEFF `outcrt` output-path importance recalculation.
#[derive(Debug, Clone, Copy)]
pub struct PathOutputImportanceInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `fbeta(-nbeta:nbeta, 0:nph, 1:ne)` output-energy table.
    pub fbeta: ArrayView3<'a, Real>,
    /// FEFF `cksp(1:ne)`: output wave numbers.
    pub wave_numbers: &'a [Real],
    /// FEFF `xlam(1:ne)`: output mean-free paths.
    pub mean_free_paths: &'a [Real],
    /// Zero-based equivalent of FEFF `ik0`, the first energy to integrate.
    pub start_energy_index: usize,
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, 1:nncrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `ckspc(1:nncrit)`: criteria wave numbers.
    pub critical_wave_numbers: &'a [Real],
    /// FEFF `xlamc(1:nncrit)`: criteria mean-free paths.
    pub critical_mean_free_paths: &'a [Real],
    /// FEFF `xcalcx`: output normalization updated when needed.
    pub current_normalization: Real,
}

/// Standard-frame coordinates generated by FEFF `mpprmp`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathStandardCoordinates {
    /// Path atom coordinates in the selected standard frame, as `npat x 3`.
    pub coordinates: Array2<Real>,
    /// FEFF symmetry case selected by `mpprmp`, in the range `1..=7`.
    pub symmetry_case: u8,
}

/// Inputs for FEFF `mpprmp` standard-frame path coordinates.
#[derive(Debug, Clone, Copy)]
pub struct PathStandardCoordinatesInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
}

/// Canonical path representation generated by FEFF `timrep`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathCanonicalRepresentation {
    /// Path atom indices in the selected canonical direction.
    pub path_indices: Vec<usize>,
    /// Canonical standard-frame coordinates as `npat x 3`.
    pub coordinates: Array2<Real>,
    /// FEFF `dhash` key for degeneracy grouping.
    pub degeneracy_hash: Real,
    /// Whether the input path was time-reversed to reach canonical order.
    pub reversed: bool,
    /// FEFF symmetry case used by `mpprmp` while building coordinates.
    pub symmetry_case: u8,
}

/// Inputs for FEFF `timrep` canonical time-reversal representation.
#[derive(Debug, Clone, Copy)]
pub struct PathCanonicalRepresentationInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// FEFF `ipat(1:npat)`: path atom indices.
    pub path_indices: &'a [usize],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
    /// Force FEFF case 7 when EELS or NRIXS disables symmetry operations.
    pub force_no_symmetry: bool,
}

/// Candidate path from one FEFF `pathsd` total-length range.
#[derive(Debug, Clone, Copy)]
pub struct PathDegeneracyCandidate<'a> {
    /// FEFF `ipat(1:npat)`: path atom indices before `timrep` canonicalization.
    pub path_indices: &'a [usize],
}

/// One unpacked FEFF `paths.bin` candidate record.
#[derive(Debug, Clone, Copy)]
pub struct PathDegeneracyRecord<'a> {
    /// FEFF `r0`: total closed path length used to form `pathsd` ranges.
    pub total_path_length: Real,
    /// FEFF `ipat(1:npat)`: unpacked path atom indices.
    pub path_indices: &'a [usize],
}

/// Inputs for FEFF `pathsd` hash-range degeneracy grouping.
#[derive(Debug, Clone, Copy)]
pub struct PathDegeneracyGroupsInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// Atom-indexed first-bounce degeneracy factors, equivalent to `i1b(atom)`.
    pub first_bounce_degeneracies: &'a [usize],
    /// Candidate paths from one `pathsd` total-length range.
    pub candidates: &'a [PathDegeneracyCandidate<'a>],
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
    /// Force FEFF case 7 when EELS or NRIXS disables symmetry operations.
    pub force_no_symmetry: bool,
}

/// One unique path group from FEFF `pathsd` degeneracy reduction.
#[derive(Debug, Clone, PartialEq)]
pub struct PathDegeneracyGroup {
    /// FEFF canonical `ipat(1:npat)` selected for the group.
    pub path_indices: Vec<usize>,
    /// Sum of `i1b(ipat(1))` over all candidate paths in the hash range.
    pub degeneracy: usize,
    /// FEFF `dhash` key used to group canonical paths.
    pub degeneracy_hash: Real,
    /// Number of candidate paths merged into this unique path.
    pub member_count: usize,
    /// Canonical standard-frame coordinates as `npat x 3`.
    pub coordinates: Array2<Real>,
    /// Whether the representative candidate was time-reversed by `timrep`.
    pub reversed: bool,
    /// FEFF symmetry case used by `mpprmp` while building coordinates.
    pub symmetry_case: u8,
}

/// Inputs for FEFF `pathsd` plane-wave importance retention.
#[derive(Debug, Clone, Copy)]
pub struct PathDegeneracyRetentionInput<'a> {
    /// Unique path groups in FEFF `pathsd` processing order.
    pub groups: &'a [PathDegeneracyGroup],
    /// FEFF `xport` value for each unique path group.
    pub port_importances: &'a [Real],
    /// FEFF `critpw`: retain paths whose relative importance is at least this percent.
    pub criterion_percent: Real,
    /// Existing FEFF `xportx`/`ndegx` reference from a previous path range.
    pub initial_reference: Option<PathDegeneracyRetentionReference>,
}

/// FEFF `pathsd` retained-path reference, equivalent to `xportx` and `ndegx`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathDegeneracyRetentionReference {
    /// FEFF `xportx` reference importance.
    pub port_importance: Real,
    /// FEFF `ndegx` reference degeneracy.
    pub degeneracy: usize,
}

/// One FEFF `pathsd` retention decision.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathDegeneracyRetentionDecision {
    /// Index of the corresponding entry in `PathDegeneracyRetentionInput::groups`.
    pub group_index: usize,
    /// FEFF `xport` for this group.
    pub port_importance: Real,
    /// FEFF `frac = 100 * ndeg * xport / (ndegx * xportx)`.
    pub fraction_percent: Real,
    /// Whether `frac >= critpw`.
    pub retained: bool,
}

/// FEFF `pathsd` retention summary for one pass over unique path groups.
#[derive(Debug, Clone, PartialEq)]
pub struct PathDegeneracyRetention {
    /// Per-group retention decisions in input order.
    pub decisions: Vec<PathDegeneracyRetentionDecision>,
    /// Number of retained unique paths, equivalent to FEFF `nuptot`.
    pub retained_unique_count: usize,
    /// Sum of retained path degeneracies, equivalent to FEFF `nptot`.
    pub retained_total_degeneracy: usize,
    /// Group that initialized FEFF's `xportx`/`ndegx` reference.
    pub reference_group_index: Option<usize>,
    /// FEFF `xportx` reference value.
    pub reference_port_importance: Option<Real>,
    /// FEFF `ndegx` reference degeneracy.
    pub reference_degeneracy: Option<usize>,
    /// Final reference value to pass into the next path range.
    pub reference: Option<PathDegeneracyRetentionReference>,
}

/// Inputs for reducing one FEFF `pathsd` equal-total-length range.
#[derive(Debug, Clone, Copy)]
pub struct PathDegeneracyRangeInput<'a> {
    /// Hash/canonicalization inputs for this total-length range.
    pub grouping: PathDegeneracyGroupsInput<'a>,
    /// FEFF `fbeta(-nbeta:nbeta,0:nph,1:ne)` output-energy table.
    pub fbeta: ArrayView3<'a, Real>,
    /// FEFF `cksp(1:ne)`: output wave numbers.
    pub wave_numbers: &'a [Real],
    /// FEFF `xlam(1:ne)`: output mean-free paths.
    pub mean_free_paths: &'a [Real],
    /// Zero-based equivalent of FEFF `ik0`.
    pub start_energy_index: usize,
    /// FEFF `fbetac(-nbeta:nbeta,0:nph,1:nncrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `ckspc(1:nncrit)`: criteria wave numbers.
    pub critical_wave_numbers: &'a [Real],
    /// FEFF `xlamc(1:nncrit)`: criteria mean-free paths.
    pub critical_mean_free_paths: &'a [Real],
    /// Incoming FEFF `xcalcx` normalization.
    pub current_normalization: Real,
    /// FEFF `critpw`: retain paths whose relative importance is at least this percent.
    pub criterion_percent: Real,
    /// Existing FEFF `xportx`/`ndegx` reference from a previous path range.
    pub retention_reference: Option<PathDegeneracyRetentionReference>,
}

/// Output of reducing one FEFF `pathsd` equal-total-length range.
#[derive(Debug, Clone, PartialEq)]
pub struct PathDegeneracyRange {
    /// Unique path groups in FEFF hash order.
    pub groups: Vec<PathDegeneracyGroup>,
    /// FEFF `outcrt` output for each unique path group.
    pub importances: Vec<PathOutputImportance>,
    /// FEFF `critpw` retention decisions for this range.
    pub retention: PathDegeneracyRetention,
    /// Updated FEFF `xcalcx` normalization to pass to the next range.
    pub normalization: Real,
}

/// Inputs for reducing all FEFF `pathsd` candidate records.
#[derive(Debug, Clone, Copy)]
pub struct PathDegeneracyReductionInput<'a> {
    /// Atom-indexed Cartesian coordinates, with row `0` as absorber.
    pub atom_positions: ArrayView2<'a, Real>,
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// Atom-indexed first-bounce degeneracy factors, equivalent to `i1b(atom)`.
    pub first_bounce_degeneracies: &'a [usize],
    /// Candidate records in FEFF `paths.bin` traversal order.
    pub records: &'a [PathDegeneracyRecord<'a>],
    /// FEFF `ipol`: polarization selector.
    pub polarization: i32,
    /// FEFF `ispin`: spin selector.
    pub spin: i32,
    /// FEFF `evec`: polarization vector.
    pub electric_vector: [Real; 3],
    /// FEFF `xivec`: incident beam or spin-axis vector.
    pub incident_vector: [Real; 3],
    /// FEFF `ica`: optional manual symmetry case override.
    pub symmetry_case_override: Option<u8>,
    /// Force FEFF case 7 when EELS or NRIXS disables symmetry operations.
    pub force_no_symmetry: bool,
    /// FEFF `fbeta(-nbeta:nbeta,0:nph,1:ne)` output-energy table.
    pub fbeta: ArrayView3<'a, Real>,
    /// FEFF `cksp(1:ne)`: output wave numbers.
    pub wave_numbers: &'a [Real],
    /// FEFF `xlam(1:ne)`: output mean-free paths.
    pub mean_free_paths: &'a [Real],
    /// Zero-based equivalent of FEFF `ik0`.
    pub start_energy_index: usize,
    /// FEFF `fbetac(-nbeta:nbeta,0:nph,1:nncrit)` criteria table.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `ckspc(1:nncrit)`: criteria wave numbers.
    pub critical_wave_numbers: &'a [Real],
    /// FEFF `xlamc(1:nncrit)`: criteria mean-free paths.
    pub critical_mean_free_paths: &'a [Real],
    /// Incoming FEFF `xcalcx` normalization.
    pub current_normalization: Real,
    /// FEFF `critpw`: retain paths whose relative importance is at least this percent.
    pub criterion_percent: Real,
    /// Existing FEFF `xportx`/`ndegx` reference from a previous reduction.
    pub retention_reference: Option<PathDegeneracyRetentionReference>,
}

/// One reduced FEFF `pathsd` total-length range.
#[derive(Debug, Clone, PartialEq)]
pub struct PathDegeneracyProcessedRange {
    /// FEFF `rcurr`: representative total path length for this range.
    pub representative_total_path_length: Real,
    /// Reduced range data.
    pub range: PathDegeneracyRange,
}

/// Output of the FEFF `pathsd` outer candidate-reduction loop.
#[derive(Debug, Clone, PartialEq)]
pub struct PathDegeneracyReduction {
    /// Total-length ranges in FEFF traversal order.
    pub ranges: Vec<PathDegeneracyProcessedRange>,
    /// Total retained unique paths, equivalent to FEFF `nuptot`.
    pub retained_unique_count: usize,
    /// Total retained degeneracy, equivalent to FEFF `nptot`.
    pub retained_total_degeneracy: usize,
    /// Updated FEFF `xcalcx` normalization after all ranges.
    pub normalization: Real,
    /// Final FEFF `xportx`/`ndegx` reference after all ranges.
    pub retention_reference: Option<PathDegeneracyRetentionReference>,
}
