//! FEFF FULLSPECTRUM numerical helpers.
//!
//! This module covers small kernels from `FULLSPECTRUM/` that can be tested
//! independently of the full driver. Larger spectrum assembly remains in the
//! module runner layer until the surrounding FEFF state is ported.

use ndarray::{Array1, ArrayView1};
use thiserror::Error;

use crate::interpolation::{InterpolationError, LintCache, lint_with_cache};
use crate::{Complex, Real};

/// FEFF Hartree energy in eV, matching `COMMON/m_constants.f90`.
pub const FEFF_HARTREE_EV: Real = 27.211_396;
/// FEFF Bohr radius in Angstrom, matching `COMMON/m_constants.f90`.
pub const FEFF_BOHR_ANGSTROM: Real = 0.529_177_249;
/// Inverse fine-structure constant used by FEFF optical sum rules.
pub const FEFF_ALPHA_INV: Real = 137.035_989_56;
/// Reduced Planck constant in eV seconds used by `FULLSPECTRUM/drdtrm.f90`.
pub const FEFF_HBAR_EV_SECONDS: Real = 6.58E-16;
/// FEFF lower energy floor for `FULLSPECTRUM/egrid_lin.f90`, in Hartree.
pub const FEFF_FULLSPECTRUM_MIN_LINEAR_ENERGY: Real = 0.01 / FEFF_HARTREE_EV;
/// FEFF lower energy floor for `FULLSPECTRUM/egrid.f90`, in Hartree.
pub const FEFF_FULLSPECTRUM_MIN_EDGE_GRID_ENERGY: Real = 0.001 / FEFF_HARTREE_EV;
/// FEFF `FULLSPECTRUM/HEADERS/params.h` default k-space step.
pub const FEFF_FULLSPECTRUM_XK_STEP: Real = 0.005;
/// FEFF `FULLSPECTRUM/HEADERS/params.h` energy-grid capacity.
pub const FEFF_FULLSPECTRUM_GRID_CAPACITY: usize = 200_001;

/// Inputs for FEFF `FULLSPECTRUM/qsum.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumQSumInput<'a> {
    /// Number density `numden` used in the oscillator-strength sum rule.
    pub number_density: Real,
    /// Imaginary dielectric function `eps2`.
    pub epsilon2: ArrayView1<'a, Real>,
    /// Energy grid `omega`.
    pub omega: ArrayView1<'a, Real>,
    /// Number of active rows, equivalent to FEFF `iepts`.
    pub active_len: usize,
}

/// Inputs for FEFF `FULLSPECTRUM/drdtrm.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumDrudeInput<'a> {
    /// Energy grid `omega` in Hartree.
    pub omega: ArrayView1<'a, Real>,
    /// Drude lifetime `tau`, in seconds.
    pub lifetime_seconds: Real,
    /// Free-electron density `numden`, in FEFF atomic units.
    pub number_density: Real,
}

/// Drude free-electron dielectric contribution.
#[derive(Debug, Clone, PartialEq)]
pub struct FullSpectrumDrudeTerm {
    /// Drude width in eV, matching the first `drude.dat` header value.
    pub gamma_ev: Real,
    /// Plasma frequency in eV, matching the second `drude.dat` header value.
    pub plasma_frequency_ev: Real,
    /// Energy grid `omega` in Hartree.
    pub omega: Array1<Real>,
    /// Complex Drude dielectric contribution on `omega`.
    pub epsilon: Array1<Complex>,
}

impl FullSpectrumDrudeTerm {
    /// Number of Drude samples.
    #[must_use]
    pub fn point_count(&self) -> usize {
        self.omega.len()
    }
}

/// Inputs for FEFF `FULLSPECTRUM/sumrules.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumSumRulesInput<'a> {
    /// Number density `numden` in FEFF atomic units.
    pub number_density: Real,
    /// Photon energy grid in eV, as read from `opconsKK.dat`.
    pub energy_ev: ArrayView1<'a, Real>,
    /// Dielectric function minus one, using the columns written by `opcons.f90`.
    pub epsilon_minus_one: ArrayView1<'a, Complex>,
    /// Refractive index minus one, using the columns written by `opcons.f90`.
    pub refractive_index_minus_one: ArrayView1<'a, Complex>,
    /// FEFF `mu` absorption coefficient column, in `cm^(-1)`.
    pub absorption_coefficient: ArrayView1<'a, Real>,
}

/// Inputs for FEFF `FULLSPECTRUM/egrid_lin.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumLinearGridInput {
    /// Number of energy points to generate.
    pub point_count: usize,
    /// Requested lower energy bound in Hartree.
    pub min_energy: Real,
    /// Upper energy bound in Hartree.
    pub max_energy: Real,
}

/// Inputs for FEFF `FULLSPECTRUM/egrid.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumEdgeGridInput<'a> {
    /// Requested lower energy bound in Hartree.
    pub min_energy: Real,
    /// Upper energy bound in Hartree.
    pub max_energy: Real,
    /// Edge energies in Hartree. This is the table FEFF obtains from Elam data.
    pub edge_energies: ArrayView1<'a, Real>,
    /// Momentum spacing, FEFF `xkstep`.
    pub wave_number_step: Real,
    /// Maximum number of points to emit, FEFF `fullpts`.
    pub max_points: usize,
}

/// Energy grid generated by FEFF `FULLSPECTRUM/egrid.f90`.
#[derive(Debug, Clone, PartialEq)]
pub struct FullSpectrumEdgeGrid {
    /// Generated energy grid in Hartree.
    pub energy: Array1<Real>,
    /// True when `max_points` was exhausted before the upper bound was reached.
    pub clipped: bool,
}

impl FullSpectrumEdgeGrid {
    /// Number of generated grid points.
    #[must_use]
    pub fn point_count(&self) -> usize {
        self.energy.len()
    }
}

/// Inputs for FEFF `FULLSPECTRUM/kk.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumKramersKronigInput<'a> {
    /// Monotonic energy grid `omega`.
    pub omega: ArrayView1<'a, Real>,
    /// Imaginary dielectric function `eps2` tabulated on `omega`.
    pub epsilon2: ArrayView1<'a, Real>,
}

/// Inputs for FEFF `FULLSPECTRUM/hamaker.f90`.
#[derive(Debug, Clone, Copy)]
pub struct FullSpectrumHamakerInput<'a> {
    /// Monotonic energy grid `omega`.
    pub omega: ArrayView1<'a, Real>,
    /// Complex dielectric function `eps`; FEFF uses its imaginary part.
    pub epsilon: ArrayView1<'a, Complex>,
}

/// Cumulative rows written to FEFF `sumrules.dat`.
#[derive(Debug, Clone, PartialEq)]
pub struct FullSpectrumSumRules {
    /// Photon energy grid in eV.
    pub energy_ev: Array1<Real>,
    /// Cumulative `epsilon_2` sum-rule effective electron count.
    pub epsilon2_effective_electrons: Array1<Real>,
    /// Cumulative absorption-coefficient sum-rule effective electron count.
    pub absorption_effective_electrons: Array1<Real>,
    /// Cumulative loss-function sum-rule effective electron count.
    pub loss_effective_electrons: Array1<Real>,
    /// Cumulative `mu * (n - 1)` sum-rule column.
    pub absorption_refractive_sum: Array1<Real>,
    /// Cumulative `(n - 1)` signed-to-absolute integral ratio.
    pub refractive_index_sum_ratio: Array1<Real>,
    /// Cumulative logarithmic loss-function moment ratio.
    pub log_loss_moment_ratio: Array1<Real>,
}

impl FullSpectrumSumRules {
    /// Number of cumulative sum-rule samples.
    #[must_use]
    pub fn point_count(&self) -> usize {
        self.energy_ev.len()
    }
}

/// Error returned by FULLSPECTRUM helper kernels.
#[derive(Debug, Clone, Copy, PartialEq, Error)]
pub enum FullSpectrumError {
    /// Number density must be positive.
    #[error("FULLSPECTRUM {name} must be positive, got {value}")]
    NonPositiveInput { name: &'static str, value: Real },
    /// Scalar inputs must be finite.
    #[error("FULLSPECTRUM {name} must be finite, got {value}")]
    NonFiniteInput { name: &'static str, value: Real },
    /// Active rows must fit in both input arrays.
    #[error("FULLSPECTRUM active row count {active_len} exceeds {field} length {len}")]
    ActiveCountOutOfRange {
        field: &'static str,
        active_len: usize,
        len: usize,
    },
    /// Array values must be finite.
    #[error("FULLSPECTRUM {field} row {row} must be finite, got {value}")]
    NonFiniteValue {
        field: &'static str,
        row: usize,
        value: Real,
    },
    /// Energy rows are expected in nondecreasing order for the trapezoid rule.
    #[error("FULLSPECTRUM omega row {row} must not decrease, got {current} after {previous}")]
    DecreasingOmega {
        row: usize,
        previous: Real,
        current: Real,
    },
    /// Array values must be positive.
    #[error("FULLSPECTRUM {field} row {row} must be positive, got {value}")]
    NonPositiveValue {
        field: &'static str,
        row: usize,
        value: Real,
    },
    /// Tabulated sum-rule inputs require at least one row.
    #[error("FULLSPECTRUM {name} requires at least one row")]
    EmptyTable { name: &'static str },
    /// Array lengths must agree for a tabulated calculation.
    #[error("FULLSPECTRUM {field} length {actual} does not match energy length {expected}")]
    LengthMismatch {
        field: &'static str,
        actual: usize,
        expected: usize,
    },
    /// Each cumulative sum-rule value must be finite.
    #[error("FULLSPECTRUM sum-rule row {row} {field} must be finite, got {value}")]
    NonFiniteSumRule {
        field: &'static str,
        row: usize,
        value: Real,
    },
    /// The final sum-rule value must be finite.
    #[error("FULLSPECTRUM neff must be finite, got {value}")]
    NonFiniteResult { value: Real },
    /// Kramers-Kronig style transforms need at least two rows.
    #[error("FULLSPECTRUM {name} requires at least two rows, got {len}")]
    TooFewRows { name: &'static str, len: usize },
    /// Energy rows are expected in strictly increasing order for transforms.
    #[error("FULLSPECTRUM omega row {row} must increase, got {current} after {previous}")]
    NonIncreasingOmega {
        row: usize,
        previous: Real,
        current: Real,
    },
    /// FEFF `lint` failed while projecting midpoint transform values.
    #[error("FULLSPECTRUM midpoint interpolation failed: {source}")]
    Interpolation { source: InterpolationError },
    /// A generated energy grid must have an increasing range.
    #[error("FULLSPECTRUM {name} upper bound {max} must exceed lower bound {min}")]
    InvalidEnergyRange {
        name: &'static str,
        min: Real,
        max: Real,
    },
}

/// Port of `FULLSPECTRUM/qsum.f90`: compute the effective electron count.
///
/// FEFF applies a trapezoid integral to `omega * eps2`, then scales it by
/// `1 / (2*pi^2*numden)`. An active length of zero or one follows the Fortran
/// loop semantics and returns zero.
pub fn full_spectrum_effective_electron_count(
    input: FullSpectrumQSumInput<'_>,
) -> Result<Real, FullSpectrumError> {
    validate_positive("number_density", input.number_density)?;
    validate_active_len("epsilon2", input.active_len, input.epsilon2.len())?;
    validate_active_len("omega", input.active_len, input.omega.len())?;

    for row in 0..input.active_len {
        validate_finite_value("epsilon2", row, input.epsilon2[row])?;
        validate_finite_value("omega", row, input.omega[row])?;
        if row > 0 && input.omega[row] < input.omega[row - 1] {
            return Err(FullSpectrumError::DecreasingOmega {
                row,
                previous: input.omega[row - 1],
                current: input.omega[row],
            });
        }
    }

    let integral = (0..input.active_len.saturating_sub(1))
        .map(|row| {
            let left = input.omega[row] * input.epsilon2[row];
            let right = input.omega[row + 1] * input.epsilon2[row + 1];
            0.5 * (left + right) * (input.omega[row + 1] - input.omega[row])
        })
        .sum::<Real>();
    let result = integral / (2.0 * std::f64::consts::PI.powi(2) * input.number_density);
    if result.is_finite() {
        Ok(result)
    } else {
        Err(FullSpectrumError::NonFiniteResult { value: result })
    }
}

/// Port of `FULLSPECTRUM/drdtrm.f90`: Drude free-electron epsilon term.
///
/// FEFF converts `tau` to a Hartree-scale width, uses `wp2 = 4*pi*numden`,
/// and writes both the eV-scaled width/plasma frequency and the complex
/// dielectric response on the active energy grid.
pub fn full_spectrum_drude_term(
    input: FullSpectrumDrudeInput<'_>,
) -> Result<FullSpectrumDrudeTerm, FullSpectrumError> {
    validate_positive("lifetime_seconds", input.lifetime_seconds)?;
    validate_positive("number_density", input.number_density)?;
    if input.omega.is_empty() {
        return Err(FullSpectrumError::EmptyTable { name: "drude_term" });
    }

    let gamma_hartree = FEFF_HBAR_EV_SECONDS / input.lifetime_seconds / FEFF_HARTREE_EV;
    let plasma_squared = 4.0 * std::f64::consts::PI * input.number_density;
    let mut epsilon = Vec::with_capacity(input.omega.len());

    for (row, omega) in input.omega.iter().copied().enumerate() {
        validate_finite_value("omega", row, omega)?;
        if omega <= 0.0 {
            return Err(FullSpectrumError::NonPositiveValue {
                field: "omega",
                row,
                value: omega,
            });
        }
        let denominator = omega.powi(2) + gamma_hartree.powi(2);
        let epsilon2 = plasma_squared * gamma_hartree / omega / denominator;
        let epsilon1 = -plasma_squared / denominator;
        let value = Complex::new(epsilon1, epsilon2);
        validate_finite_value("epsilon real", row, value.re)?;
        validate_finite_value("epsilon imaginary", row, value.im)?;
        epsilon.push(value);
    }

    Ok(FullSpectrumDrudeTerm {
        gamma_ev: gamma_hartree * FEFF_HARTREE_EV,
        plasma_frequency_ev: plasma_squared.sqrt() * FEFF_HARTREE_EV,
        omega: input.omega.to_owned(),
        epsilon: Array1::from_vec(epsilon),
    })
}

/// Port of `FULLSPECTRUM/sumrules.f90`: cumulative optical sum rules.
///
/// FEFF reads `opconsKK.dat`, recomputes the loss function from `epsilon - 1`,
/// converts energy and absorption units to atomic units, then writes a row after
/// every input point. This helper keeps the same integration rules, including
/// the right-endpoint rule for `mu` columns and trapezoids for energy-weighted
/// dielectric/loss columns.
pub fn full_spectrum_sum_rules(
    input: FullSpectrumSumRulesInput<'_>,
) -> Result<FullSpectrumSumRules, FullSpectrumError> {
    validate_positive("number_density", input.number_density)?;
    if input.energy_ev.is_empty() {
        return Err(FullSpectrumError::EmptyTable { name: "sum_rules" });
    }
    validate_matching_len(
        "epsilon_minus_one",
        input.epsilon_minus_one.len(),
        input.energy_ev.len(),
    )?;
    validate_matching_len(
        "refractive_index_minus_one",
        input.refractive_index_minus_one.len(),
        input.energy_ev.len(),
    )?;
    validate_matching_len(
        "absorption_coefficient",
        input.absorption_coefficient.len(),
        input.energy_ev.len(),
    )?;

    let mut epsilon2_effective_electrons = Vec::with_capacity(input.energy_ev.len());
    let mut absorption_effective_electrons = Vec::with_capacity(input.energy_ev.len());
    let mut loss_effective_electrons = Vec::with_capacity(input.energy_ev.len());
    let mut absorption_refractive_sum = Vec::with_capacity(input.energy_ev.len());
    let mut refractive_index_sum_ratio = Vec::with_capacity(input.energy_ev.len());
    let mut log_loss_moment_ratio = Vec::with_capacity(input.energy_ev.len());

    let scale = 1.0 / (2.0 * std::f64::consts::PI.powi(2) * input.number_density);
    let mut previous_energy_hartree = 0.0;
    let mut previous_epsilon2 = 0.0;
    let mut previous_loss = 0.0;
    let mut sum_epsilon2 = 0.0;
    let mut sum_absorption = 0.0;
    let mut sum_loss = 0.0;
    let mut sum_absorption_refractive = 0.0;
    let mut sum_refractive = 0.0;
    let mut sum_abs_refractive = 0.0;
    let mut sum_log_loss = 0.0;

    for row in 0..input.energy_ev.len() {
        let energy_ev = input.energy_ev[row];
        let epsilon = input.epsilon_minus_one[row];
        let refractive_index = input.refractive_index_minus_one[row];
        let absorption = input.absorption_coefficient[row];

        validate_finite_value("energy_ev", row, energy_ev)?;
        validate_finite_value("epsilon_minus_one real", row, epsilon.re)?;
        validate_finite_value("epsilon_minus_one imaginary", row, epsilon.im)?;
        validate_finite_value("refractive_index_minus_one real", row, refractive_index.re)?;
        validate_finite_value(
            "refractive_index_minus_one imaginary",
            row,
            refractive_index.im,
        )?;
        validate_finite_value("absorption_coefficient", row, absorption)?;
        if row > 0 && energy_ev < input.energy_ev[row - 1] {
            return Err(FullSpectrumError::DecreasingOmega {
                row,
                previous: input.energy_ev[row - 1],
                current: energy_ev,
            });
        }

        let energy_hartree = energy_ev / FEFF_HARTREE_EV;
        let mu_atomic = absorption * FEFF_BOHR_ANGSTROM / 1000.0;
        let epsilon2 = epsilon.im;
        let refractive_real = refractive_index.re;
        let loss = epsilon2 / (epsilon2.powi(2) + (epsilon.re + 1.0).powi(2));
        let delta_energy = energy_hartree - previous_energy_hartree;

        sum_epsilon2 += 0.5
            * (energy_hartree * epsilon2 + previous_energy_hartree * previous_epsilon2)
            * delta_energy;
        sum_absorption += mu_atomic * delta_energy;
        sum_loss +=
            0.5 * (energy_hartree * loss + previous_energy_hartree * previous_loss) * delta_energy;
        sum_absorption_refractive += mu_atomic * refractive_real * delta_energy;
        sum_refractive += delta_energy * refractive_real;
        sum_abs_refractive += delta_energy * refractive_real.abs();
        if previous_energy_hartree > 0.0 {
            sum_log_loss += 0.5
                * (energy_hartree.ln() * energy_hartree * loss
                    + previous_energy_hartree.ln() * previous_energy_hartree * previous_loss)
                * delta_energy;
        } else {
            sum_log_loss += energy_hartree.ln() * energy_hartree * loss * energy_hartree;
        }

        push_sum_rule_value(
            &mut epsilon2_effective_electrons,
            "epsilon2_effective_electrons",
            row,
            scale * sum_epsilon2,
        )?;
        push_sum_rule_value(
            &mut absorption_effective_electrons,
            "absorption_effective_electrons",
            row,
            FEFF_ALPHA_INV * scale * sum_absorption,
        )?;
        push_sum_rule_value(
            &mut loss_effective_electrons,
            "loss_effective_electrons",
            row,
            scale * sum_loss,
        )?;
        push_sum_rule_value(
            &mut absorption_refractive_sum,
            "absorption_refractive_sum",
            row,
            FEFF_ALPHA_INV * scale * sum_absorption_refractive,
        )?;
        push_sum_rule_value(
            &mut refractive_index_sum_ratio,
            "refractive_index_sum_ratio",
            row,
            sum_refractive / sum_abs_refractive,
        )?;
        push_sum_rule_value(
            &mut log_loss_moment_ratio,
            "log_loss_moment_ratio",
            row,
            sum_log_loss / sum_loss,
        )?;

        previous_energy_hartree = energy_hartree;
        previous_epsilon2 = epsilon2;
        previous_loss = loss;
    }

    Ok(FullSpectrumSumRules {
        energy_ev: input.energy_ev.to_owned(),
        epsilon2_effective_electrons: Array1::from_vec(epsilon2_effective_electrons),
        absorption_effective_electrons: Array1::from_vec(absorption_effective_electrons),
        loss_effective_electrons: Array1::from_vec(loss_effective_electrons),
        absorption_refractive_sum: Array1::from_vec(absorption_refractive_sum),
        refractive_index_sum_ratio: Array1::from_vec(refractive_index_sum_ratio),
        log_loss_moment_ratio: Array1::from_vec(log_loss_moment_ratio),
    })
}

/// Port of the active branch in `FULLSPECTRUM/egrid_lin.f90`.
///
/// The historical logarithmic branch is skipped by a `goto` in FEFF10. The live
/// path clamps non-positive lower bounds to `0.01 eV` in Hartree units and then
/// advances by a fixed linear step from `min_energy` to `max_energy`.
pub fn full_spectrum_linear_energy_grid(
    input: FullSpectrumLinearGridInput,
) -> Result<Array1<Real>, FullSpectrumError> {
    validate_transform_len("linear_grid", input.point_count)?;
    validate_finite("min_energy", input.min_energy)?;
    validate_finite("max_energy", input.max_energy)?;

    let min_energy = if input.min_energy <= 0.0 {
        FEFF_FULLSPECTRUM_MIN_LINEAR_ENERGY
    } else {
        input.min_energy
    };
    if input.max_energy <= min_energy {
        return Err(FullSpectrumError::InvalidEnergyRange {
            name: "linear_grid",
            min: min_energy,
            max: input.max_energy,
        });
    }

    let step = (input.max_energy - min_energy) / (input.point_count - 1) as Real;
    let mut grid = Vec::with_capacity(input.point_count);
    grid.push(min_energy);
    for row in 1..input.point_count {
        grid.push(grid[row - 1] + step);
    }
    Ok(Array1::from_vec(grid))
}

/// Port of `FULLSPECTRUM/egrid.f90`: edge-aware full-spectrum energy grid.
///
/// FEFF builds a grid that is regular in `k = sqrt(2 * (omega - edge))`
/// relative to the previous absorption edge, then restarts the k grid whenever
/// the next edge is crossed. This helper accepts the already-tabulated edge
/// energies directly; a higher-level Elam-table adapter can provide those from
/// atomic numbers without changing the numerical grid algorithm.
pub fn full_spectrum_edge_energy_grid(
    input: FullSpectrumEdgeGridInput<'_>,
) -> Result<FullSpectrumEdgeGrid, FullSpectrumError> {
    validate_transform_len("edge_grid", input.max_points)?;
    validate_finite("min_energy", input.min_energy)?;
    validate_finite("max_energy", input.max_energy)?;
    validate_positive("wave_number_step", input.wave_number_step)?;
    for (row, value) in input.edge_energies.iter().copied().enumerate() {
        validate_finite_value("edge_energies", row, value)?;
    }

    let min_energy = input.min_energy.max(FEFF_FULLSPECTRUM_MIN_EDGE_GRID_ENERGY);
    if input.max_energy <= min_energy {
        return Err(FullSpectrumError::InvalidEnergyRange {
            name: "edge_grid",
            min: min_energy,
            max: input.max_energy,
        });
    }

    let mut energy = Vec::with_capacity(input.max_points);
    energy.push(min_energy);
    let mut next_edge = next_edge_above(input.edge_energies, min_energy);
    let mut current_edge = previous_edge_below(input.edge_energies, min_energy);
    let mut current_k = (2.0 * (min_energy - current_edge)).sqrt();
    let mut next_k = (2.0 * (next_edge - current_edge)).sqrt();

    for _ in 1..input.max_points {
        current_k += input.wave_number_step;
        let mut value = if current_k >= next_k {
            current_k = 0.0;
            current_edge = next_edge;
            next_edge = next_edge_above(input.edge_energies, current_edge);
            next_k = (2.0 * (next_edge - current_edge)).sqrt();
            current_edge
        } else {
            current_edge + current_k.powi(2) / 2.0
        };

        if value > input.max_energy {
            value = input.max_energy;
            energy.push(value);
            return Ok(FullSpectrumEdgeGrid {
                energy: Array1::from_vec(energy),
                clipped: false,
            });
        }
        energy.push(value);
    }

    Ok(FullSpectrumEdgeGrid {
        energy: Array1::from_vec(energy),
        clipped: true,
    })
}

/// Port of `FULLSPECTRUM/kk.f90`: Kramers-Kronig transform of `eps2`.
///
/// FEFF evaluates the principal-value integral at interval midpoints, using an
/// analytic linear-`eps2` contribution near the singularity and trapezoid
/// contributions elsewhere, then linearly interpolates the midpoint result back
/// to the input grid. The first and last output values copy their neighbors,
/// matching the Fortran endpoint convention.
pub fn full_spectrum_kramers_kronig(
    input: FullSpectrumKramersKronigInput<'_>,
) -> Result<Array1<Real>, FullSpectrumError> {
    validate_transform_len("kramers_kronig", input.omega.len())?;
    validate_matching_len("epsilon2", input.epsilon2.len(), input.omega.len())?;
    validate_strictly_increasing_grid(input.omega)?;
    for (row, value) in input.epsilon2.iter().copied().enumerate() {
        validate_finite_value("epsilon2", row, value)?;
    }

    let midpoints = midpoint_grid(input.omega);
    let midpoint_values = midpoints
        .iter()
        .copied()
        .map(|midpoint| kk_midpoint_value(input.omega, input.epsilon2, midpoint))
        .collect::<Result<Vec<_>, _>>()?;
    interpolate_midpoints_to_grid(input.omega, &midpoints, &midpoint_values)
}

/// Port of `FULLSPECTRUM/hamaker.f90`: dielectric transform on the imaginary axis.
///
/// The FEFF routine integrates `omega' * eps2(omega') / (omega'^2 + omega^2)`
/// at interval midpoints, applies the `2/pi` factor, and interpolates back to
/// the input grid. The real part of the input epsilon is ignored by FEFF.
pub fn full_spectrum_hamaker_transform(
    input: FullSpectrumHamakerInput<'_>,
) -> Result<Array1<Real>, FullSpectrumError> {
    validate_transform_len("hamaker", input.omega.len())?;
    validate_matching_len("epsilon", input.epsilon.len(), input.omega.len())?;
    validate_strictly_increasing_grid(input.omega)?;
    for row in 0..input.epsilon.len() {
        validate_finite_value("epsilon real", row, input.epsilon[row].re)?;
        validate_finite_value("epsilon imaginary", row, input.epsilon[row].im)?;
    }

    let midpoints = midpoint_grid(input.omega);
    let midpoint_values = midpoints
        .iter()
        .copied()
        .map(|midpoint| hamaker_midpoint_value(input.omega, input.epsilon, midpoint))
        .collect::<Result<Vec<_>, _>>()?;
    interpolate_midpoints_to_grid(input.omega, &midpoints, &midpoint_values)
}

fn validate_positive(name: &'static str, value: Real) -> Result<(), FullSpectrumError> {
    if !value.is_finite() {
        Err(FullSpectrumError::NonFiniteInput { name, value })
    } else if value <= 0.0 {
        Err(FullSpectrumError::NonPositiveInput { name, value })
    } else {
        Ok(())
    }
}

fn validate_finite(name: &'static str, value: Real) -> Result<(), FullSpectrumError> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(FullSpectrumError::NonFiniteInput { name, value })
    }
}

fn validate_transform_len(name: &'static str, len: usize) -> Result<(), FullSpectrumError> {
    if len >= 2 {
        Ok(())
    } else {
        Err(FullSpectrumError::TooFewRows { name, len })
    }
}

fn validate_strictly_increasing_grid(omega: ArrayView1<'_, Real>) -> Result<(), FullSpectrumError> {
    for (row, value) in omega.iter().copied().enumerate() {
        validate_finite_value("omega", row, value)?;
        if row > 0 && value <= omega[row - 1] {
            return Err(FullSpectrumError::NonIncreasingOmega {
                row,
                previous: omega[row - 1],
                current: value,
            });
        }
    }
    Ok(())
}

fn validate_matching_len(
    field: &'static str,
    actual: usize,
    expected: usize,
) -> Result<(), FullSpectrumError> {
    if actual == expected {
        Ok(())
    } else {
        Err(FullSpectrumError::LengthMismatch {
            field,
            actual,
            expected,
        })
    }
}

fn midpoint_grid(omega: ArrayView1<'_, Real>) -> Vec<Real> {
    (0..omega.len() - 1)
        .map(|row| 0.5 * (omega[row + 1] + omega[row]))
        .collect()
}

fn previous_edge_below(edge_energies: ArrayView1<'_, Real>, current: Real) -> Real {
    edge_energies
        .iter()
        .copied()
        .map(|edge| edge.max(0.0))
        .filter(|&edge| edge < current)
        .fold(0.0, Real::max)
}

fn next_edge_above(edge_energies: ArrayView1<'_, Real>, current: Real) -> Real {
    edge_energies
        .iter()
        .copied()
        .map(|edge| edge.max(0.0))
        .filter(|&edge| edge > current)
        .fold(1.0e8, Real::min)
}

fn kk_midpoint_value(
    omega: ArrayView1<'_, Real>,
    epsilon2: ArrayView1<'_, Real>,
    midpoint: Real,
) -> Result<Real, FullSpectrumError> {
    const ANALYTIC_WINDOW: Real = 25.0;
    const TOO_BIG: Real = 1.0e8;

    let mut integral = 0.0;
    for row in (0..omega.len() - 1).rev() {
        let left = omega[row];
        let right = omega[row + 1];
        let contribution =
            if (left - midpoint).abs().max((right - midpoint).abs()) < ANALYTIC_WINDOW {
                let delta = right - left;
                let mut value = epsilon2[row + 1] - epsilon2[row];
                let slope = value / delta;
                let intercept = epsilon2[row] - slope * left;

                let plus_factor = (right + midpoint) / (left + midpoint);
                if plus_factor <= 0.0 || plus_factor >= TOO_BIG {
                    continue;
                }
                value += plus_factor.ln() * (intercept - slope * midpoint) / 2.0;

                let minus_factor = (right - midpoint) / (left - midpoint);
                if minus_factor == 0.0 {
                    continue;
                }
                value += minus_factor.abs().ln() * (intercept + midpoint * slope) / 2.0;
                if value.abs() < TOO_BIG {
                    value
                } else {
                    continue;
                }
            } else {
                let left_denominator = left.powi(2) - midpoint.powi(2);
                let right_denominator = right.powi(2) - midpoint.powi(2);
                let value = right * epsilon2[row + 1] / right_denominator
                    + left * epsilon2[row] / left_denominator;
                value * (right - left) / 2.0
            };
        integral += contribution;
    }

    let value = 2.0 * integral / std::f64::consts::PI;
    if value.is_finite() {
        Ok(value)
    } else {
        Err(FullSpectrumError::NonFiniteResult { value })
    }
}

fn hamaker_midpoint_value(
    omega: ArrayView1<'_, Real>,
    epsilon: ArrayView1<'_, Complex>,
    midpoint: Real,
) -> Result<Real, FullSpectrumError> {
    let integral = (0..omega.len() - 1)
        .rev()
        .map(|row| {
            let left = omega[row];
            let right = omega[row + 1];
            let left_value = left * epsilon[row].im / (left.powi(2) + midpoint.powi(2));
            let right_value = right * epsilon[row + 1].im / (right.powi(2) + midpoint.powi(2));
            (left_value + right_value) * (right - left) / 2.0
        })
        .sum::<Real>();
    let value = 2.0 * integral / std::f64::consts::PI;
    if value.is_finite() {
        Ok(value)
    } else {
        Err(FullSpectrumError::NonFiniteResult { value })
    }
}

fn interpolate_midpoints_to_grid(
    omega: ArrayView1<'_, Real>,
    midpoints: &[Real],
    midpoint_values: &[Real],
) -> Result<Array1<Real>, FullSpectrumError> {
    let mut output = vec![0.0; omega.len()];
    if omega.len() == 2 {
        output[0] = midpoint_values[0];
        output[1] = midpoint_values[0];
        return Ok(Array1::from_vec(output));
    }

    let mut cache = LintCache::new();
    for row in 1..omega.len() - 1 {
        output[row] = lint_with_cache(midpoints, midpoint_values, omega[row], &mut cache)
            .map_err(|source| FullSpectrumError::Interpolation { source })?;
    }
    output[0] = output[1];
    output[omega.len() - 1] = output[omega.len() - 2];
    Ok(Array1::from_vec(output))
}

fn validate_active_len(
    field: &'static str,
    active_len: usize,
    len: usize,
) -> Result<(), FullSpectrumError> {
    if active_len > len {
        Err(FullSpectrumError::ActiveCountOutOfRange {
            field,
            active_len,
            len,
        })
    } else {
        Ok(())
    }
}

fn validate_finite_value(
    field: &'static str,
    row: usize,
    value: Real,
) -> Result<(), FullSpectrumError> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(FullSpectrumError::NonFiniteValue { field, row, value })
    }
}

fn push_sum_rule_value(
    values: &mut Vec<Real>,
    field: &'static str,
    row: usize,
    value: Real,
) -> Result<(), FullSpectrumError> {
    if value.is_finite() {
        values.push(value);
        Ok(())
    } else {
        Err(FullSpectrumError::NonFiniteSumRule { field, row, value })
    }
}

#[cfg(test)]
mod tests {
    use ndarray::{Array1, array};
    use num_complex::Complex64;

    use crate::Real;

    use super::{
        FEFF_FULLSPECTRUM_MIN_EDGE_GRID_ENERGY, FullSpectrumDrudeInput, FullSpectrumEdgeGridInput,
        FullSpectrumError, FullSpectrumHamakerInput, FullSpectrumKramersKronigInput,
        FullSpectrumLinearGridInput, FullSpectrumQSumInput, FullSpectrumSumRulesInput,
        full_spectrum_drude_term, full_spectrum_edge_energy_grid,
        full_spectrum_effective_electron_count, full_spectrum_hamaker_transform,
        full_spectrum_kramers_kronig, full_spectrum_linear_energy_grid, full_spectrum_sum_rules,
    };

    #[test]
    fn effective_electron_count_matches_feff_qsum_reference() -> Result<(), FullSpectrumError> {
        let omega = array![0.0, 0.1, 0.2, 0.5, 1.0, 1.8];
        let epsilon2 = array![0.0, 0.5, 1.0, 0.25, 0.75, 0.1];

        let neff = full_spectrum_effective_electron_count(FullSpectrumQSumInput {
            number_density: 0.075,
            epsilon2: epsilon2.view(),
            omega: omega.view(),
            active_len: 6,
        })?;

        assert_close(neff, 0.442_098_097_959_400_5, 1.0e-14);
        Ok(())
    }

    #[test]
    fn effective_electron_count_matches_feff_single_point_reference()
    -> Result<(), FullSpectrumError> {
        let omega = array![0.0, 0.1];
        let epsilon2 = array![1.0, 2.0];

        let neff = full_spectrum_effective_electron_count(FullSpectrumQSumInput {
            number_density: 0.075,
            epsilon2: epsilon2.view(),
            omega: omega.view(),
            active_len: 1,
        })?;

        assert_eq!(neff, 0.0);
        Ok(())
    }

    #[test]
    fn effective_electron_count_rejects_invalid_inputs() {
        let omega = array![0.0, 0.1, 0.2];
        let epsilon2 = array![0.0, 0.5, 1.0];

        assert!(matches!(
            full_spectrum_effective_electron_count(FullSpectrumQSumInput {
                number_density: 0.0,
                epsilon2: epsilon2.view(),
                omega: omega.view(),
                active_len: 3,
            }),
            Err(FullSpectrumError::NonPositiveInput {
                name: "number_density",
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_effective_electron_count(FullSpectrumQSumInput {
                number_density: 0.075,
                epsilon2: epsilon2.view(),
                omega: omega.view(),
                active_len: 4,
            }),
            Err(FullSpectrumError::ActiveCountOutOfRange {
                field: "epsilon2",
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_effective_electron_count(FullSpectrumQSumInput {
                number_density: 0.075,
                epsilon2: array![0.0, f64::NAN, 1.0].view(),
                omega: omega.view(),
                active_len: 3,
            }),
            Err(FullSpectrumError::NonFiniteValue {
                field: "epsilon2",
                row: 1,
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_effective_electron_count(FullSpectrumQSumInput {
                number_density: 0.075,
                epsilon2: epsilon2.view(),
                omega: array![0.0, 0.2, 0.1].view(),
                active_len: 3,
            }),
            Err(FullSpectrumError::DecreasingOmega { row: 2, .. })
        ));
    }

    #[test]
    fn drude_term_matches_feff_reference_algorithm() -> Result<(), FullSpectrumError> {
        let omega = array![0.1, 0.2, 0.5];

        let drude = full_spectrum_drude_term(FullSpectrumDrudeInput {
            omega: omega.view(),
            lifetime_seconds: 1.0e-15,
            number_density: 0.075,
        })?;

        assert_eq!(drude.point_count(), 3);
        assert_close(drude.gamma_ev, 0.658, 1.0e-14);
        assert_close(drude.plasma_frequency_ev, 26.417_175_795_207_253, 1.0e-14);
        assert_close(drude.epsilon[0].re, -89.041_328_740_125_08, 1.0e-14);
        assert_close(drude.epsilon[0].im, 21.531_124_059_567_656, 1.0e-14);
        assert_close(drude.epsilon[2].re, -3.761_114_344_763_512, 1.0e-14);
        assert_close(drude.epsilon[2].im, 0.181_895_352_877_477_57, 1.0e-14);
        Ok(())
    }

    #[test]
    fn drude_term_rejects_invalid_inputs() {
        assert!(matches!(
            full_spectrum_drude_term(FullSpectrumDrudeInput {
                omega: array![0.1].view(),
                lifetime_seconds: 0.0,
                number_density: 0.075,
            }),
            Err(FullSpectrumError::NonPositiveInput {
                name: "lifetime_seconds",
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_drude_term(FullSpectrumDrudeInput {
                omega: Array1::<Real>::zeros(0).view(),
                lifetime_seconds: 1.0e-15,
                number_density: 0.075,
            }),
            Err(FullSpectrumError::EmptyTable { name: "drude_term" })
        ));
        assert!(matches!(
            full_spectrum_drude_term(FullSpectrumDrudeInput {
                omega: array![0.0].view(),
                lifetime_seconds: 1.0e-15,
                number_density: 0.075,
            }),
            Err(FullSpectrumError::NonPositiveValue {
                field: "omega",
                row: 0,
                ..
            })
        ));
    }

    #[test]
    fn sum_rules_match_feff_reference_algorithm() -> Result<(), FullSpectrumError> {
        let energy_ev = array![10.0, 20.0, 40.0];
        let epsilon_minus_one = array![
            Complex64::new(0.10, 0.20),
            Complex64::new(0.15, 0.25),
            Complex64::new(0.20, 0.35),
        ];
        let refractive_index_minus_one = array![
            Complex64::new(0.01, 0.02),
            Complex64::new(0.02, 0.03),
            Complex64::new(0.03, 0.04),
        ];
        let absorption_coefficient = array![1000.0, 2000.0, 3000.0];

        let rules = full_spectrum_sum_rules(FullSpectrumSumRulesInput {
            number_density: 0.075,
            energy_ev: energy_ev.view(),
            epsilon_minus_one: epsilon_minus_one.view(),
            refractive_index_minus_one: refractive_index_minus_one.view(),
            absorption_coefficient: absorption_coefficient.view(),
        })?;

        assert_eq!(rules.point_count(), 3);
        assert_close(rules.energy_ev[2], 40.0, 0.0);
        assert_close(
            rules.epsilon2_effective_electrons[2],
            0.214_375_530_814_624_3,
            1.0e-14,
        );
        assert_close(
            rules.absorption_effective_electrons[2],
            162.008_009_804_073_2,
            1.0e-14,
        );
        assert_close(
            rules.loss_effective_electrons[2],
            0.145_731_231_111_208_3,
            1.0e-14,
        );
        assert_close(
            rules.absorption_refractive_sum[2],
            4.140_204_694_992_98,
            1.0e-14,
        );
        assert_close(rules.refractive_index_sum_ratio[2], 1.0, 1.0e-14);
        assert_close(
            rules.log_loss_moment_ratio[2],
            -0.038_690_505_695_948_56,
            1.0e-14,
        );
        Ok(())
    }

    #[test]
    fn sum_rules_reject_invalid_inputs() {
        let energy_ev = array![10.0, 5.0];
        let epsilon_minus_one = array![Complex64::new(0.10, 0.20), Complex64::new(0.15, 0.25)];
        let refractive_index_minus_one =
            array![Complex64::new(0.01, 0.02), Complex64::new(0.02, 0.03)];
        let absorption_coefficient = array![1000.0, 2000.0];

        assert!(matches!(
            full_spectrum_sum_rules(FullSpectrumSumRulesInput {
                number_density: 0.075,
                energy_ev: energy_ev.view(),
                epsilon_minus_one: epsilon_minus_one.view(),
                refractive_index_minus_one: refractive_index_minus_one.view(),
                absorption_coefficient: absorption_coefficient.view(),
            }),
            Err(FullSpectrumError::DecreasingOmega { row: 1, .. })
        ));
        assert!(matches!(
            full_spectrum_sum_rules(FullSpectrumSumRulesInput {
                number_density: 0.075,
                energy_ev: Array1::<Real>::zeros(0).view(),
                epsilon_minus_one: Array1::<Complex64>::zeros(0).view(),
                refractive_index_minus_one: Array1::<Complex64>::zeros(0).view(),
                absorption_coefficient: Array1::<Real>::zeros(0).view(),
            }),
            Err(FullSpectrumError::EmptyTable { name: "sum_rules" })
        ));
        assert!(matches!(
            full_spectrum_sum_rules(FullSpectrumSumRulesInput {
                number_density: 0.075,
                energy_ev: array![10.0, 20.0].view(),
                epsilon_minus_one: array![Complex64::new(0.10, 0.20)].view(),
                refractive_index_minus_one: refractive_index_minus_one.view(),
                absorption_coefficient: absorption_coefficient.view(),
            }),
            Err(FullSpectrumError::LengthMismatch {
                field: "epsilon_minus_one",
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_sum_rules(FullSpectrumSumRulesInput {
                number_density: 0.075,
                energy_ev: array![10.0].view(),
                epsilon_minus_one: array![Complex64::new(0.10, 0.20)].view(),
                refractive_index_minus_one: array![Complex64::new(0.0, 0.0)].view(),
                absorption_coefficient: array![1000.0].view(),
            }),
            Err(FullSpectrumError::NonFiniteSumRule {
                field: "refractive_index_sum_ratio",
                ..
            })
        ));
    }

    #[test]
    fn linear_energy_grid_matches_active_feff_egrid_lin_branch() -> Result<(), FullSpectrumError> {
        let grid = full_spectrum_linear_energy_grid(FullSpectrumLinearGridInput {
            point_count: 5,
            min_energy: 0.1,
            max_energy: 1.1,
        })?;

        assert_close(grid[0], 0.1, 0.0);
        assert_close(grid[1], 0.35, 1.0e-15);
        assert_close(grid[2], 0.6, 1.0e-15);
        assert_close(grid[3], 0.85, 1.0e-15);
        assert_close(grid[4], 1.1, 1.0e-15);
        Ok(())
    }

    #[test]
    fn linear_energy_grid_applies_feff_positive_floor() -> Result<(), FullSpectrumError> {
        let grid = full_spectrum_linear_energy_grid(FullSpectrumLinearGridInput {
            point_count: 3,
            min_energy: -1.0,
            max_energy: 0.5,
        })?;

        assert_close(grid[0], super::FEFF_FULLSPECTRUM_MIN_LINEAR_ENERGY, 0.0);
        assert_close(
            grid[1],
            (super::FEFF_FULLSPECTRUM_MIN_LINEAR_ENERGY + 0.5) / 2.0,
            1.0e-15,
        );
        assert_close(grid[2], 0.5, 1.0e-15);
        Ok(())
    }

    #[test]
    fn linear_energy_grid_rejects_invalid_inputs() {
        assert!(matches!(
            full_spectrum_linear_energy_grid(FullSpectrumLinearGridInput {
                point_count: 1,
                min_energy: 0.1,
                max_energy: 1.1,
            }),
            Err(FullSpectrumError::TooFewRows {
                name: "linear_grid",
                len: 1
            })
        ));
        assert!(matches!(
            full_spectrum_linear_energy_grid(FullSpectrumLinearGridInput {
                point_count: 2,
                min_energy: f64::NAN,
                max_energy: 1.1,
            }),
            Err(FullSpectrumError::NonFiniteInput {
                name: "min_energy",
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_linear_energy_grid(FullSpectrumLinearGridInput {
                point_count: 2,
                min_energy: 1.1,
                max_energy: 1.1,
            }),
            Err(FullSpectrumError::InvalidEnergyRange {
                name: "linear_grid",
                ..
            })
        ));
    }

    #[test]
    fn edge_energy_grid_matches_feff_egrid_edge_restarts() -> Result<(), FullSpectrumError> {
        let edges = array![0.4, 0.8];

        let grid = full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
            min_energy: 0.0,
            max_energy: 1.0,
            edge_energies: edges.view(),
            wave_number_step: 0.2,
            max_points: 20,
        })?;

        assert!(!grid.clipped);
        assert_eq!(grid.point_count(), 15);
        assert_close(grid.energy[0], FEFF_FULLSPECTRUM_MIN_EDGE_GRID_ENERGY, 0.0);
        assert_close(grid.energy[4], 0.326_895_256_108_847_07, 1.0e-14);
        assert_close(grid.energy[5], 0.4, 1.0e-14);
        assert_close(grid.energy[10], 0.8, 1.0e-14);
        assert_close(grid.energy[14], 1.0, 1.0e-14);
        Ok(())
    }

    #[test]
    fn edge_energy_grid_matches_feff_egrid_without_edges() -> Result<(), FullSpectrumError> {
        let edges = Array1::<Real>::zeros(0);

        let grid = full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
            min_energy: 0.1,
            max_energy: 1.0,
            edge_energies: edges.view(),
            wave_number_step: 0.2,
            max_points: 20,
        })?;

        assert!(!grid.clipped);
        assert_eq!(grid.point_count(), 6);
        assert_close(grid.energy[0], 0.1, 0.0);
        assert_close(grid.energy[1], 0.209_442_719_099_991_6, 1.0e-14);
        assert_close(grid.energy[4], 0.777_770_876_399_966_3, 1.0e-14);
        assert_close(grid.energy[5], 1.0, 1.0e-14);
        Ok(())
    }

    #[test]
    fn edge_energy_grid_reports_feff_capacity_clipping() -> Result<(), FullSpectrumError> {
        let edges = Array1::<Real>::zeros(0);

        let grid = full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
            min_energy: 0.1,
            max_energy: 10.0,
            edge_energies: edges.view(),
            wave_number_step: 0.2,
            max_points: 5,
        })?;

        assert!(grid.clipped);
        assert_eq!(grid.point_count(), 5);
        assert_close(grid.energy[4], 0.777_770_876_399_966_3, 1.0e-14);
        Ok(())
    }

    #[test]
    fn edge_energy_grid_rejects_invalid_inputs() {
        let edges = array![0.4];

        assert!(matches!(
            full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
                min_energy: 0.1,
                max_energy: 1.0,
                edge_energies: edges.view(),
                wave_number_step: 0.2,
                max_points: 1,
            }),
            Err(FullSpectrumError::TooFewRows {
                name: "edge_grid",
                len: 1
            })
        ));
        assert!(matches!(
            full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
                min_energy: 0.1,
                max_energy: 1.0,
                edge_energies: edges.view(),
                wave_number_step: 0.0,
                max_points: 2,
            }),
            Err(FullSpectrumError::NonPositiveInput {
                name: "wave_number_step",
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
                min_energy: 0.1,
                max_energy: 1.0,
                edge_energies: array![f64::NAN].view(),
                wave_number_step: 0.2,
                max_points: 2,
            }),
            Err(FullSpectrumError::NonFiniteValue {
                field: "edge_energies",
                row: 0,
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_edge_energy_grid(FullSpectrumEdgeGridInput {
                min_energy: 1.0,
                max_energy: 1.0,
                edge_energies: edges.view(),
                wave_number_step: 0.2,
                max_points: 2,
            }),
            Err(FullSpectrumError::InvalidEnergyRange {
                name: "edge_grid",
                ..
            })
        ));
    }

    #[test]
    fn kramers_kronig_matches_feff_reference_algorithm() -> Result<(), FullSpectrumError> {
        let omega = array![1.0, 2.0, 4.0, 7.0, 11.0];
        let epsilon2 = array![0.2, 0.5, 0.25, 0.4, 0.15];

        let epsilon1 = full_spectrum_kramers_kronig(FullSpectrumKramersKronigInput {
            omega: omega.view(),
            epsilon2: epsilon2.view(),
        })?;

        assert_close(epsilon1[0], 0.459_691_458_481_860_66, 1.0e-14);
        assert_close(epsilon1[1], 0.459_691_458_481_860_66, 1.0e-14);
        assert_close(epsilon1[2], 0.160_612_887_833_759_8, 1.0e-14);
        assert_close(epsilon1[3], 0.014_010_911_454_772_346, 1.0e-14);
        assert_close(epsilon1[4], 0.014_010_911_454_772_346, 1.0e-14);
        Ok(())
    }

    #[test]
    fn hamaker_transform_matches_feff_reference_algorithm() -> Result<(), FullSpectrumError> {
        let omega = array![1.0, 2.0, 4.0, 7.0, 11.0];
        let epsilon = array![
            Complex64::new(0.1, 0.2),
            Complex64::new(0.3, 0.5),
            Complex64::new(0.2, 0.25),
            Complex64::new(0.4, 0.4),
            Complex64::new(0.1, 0.15),
        ];

        let imaginary_axis = full_spectrum_hamaker_transform(FullSpectrumHamakerInput {
            omega: omega.view(),
            epsilon: epsilon.view(),
        })?;

        assert_close(imaginary_axis[0], 0.354_646_982_533_894_65, 1.0e-14);
        assert_close(imaginary_axis[1], 0.354_646_982_533_894_65, 1.0e-14);
        assert_close(imaginary_axis[2], 0.223_104_490_219_296_74, 1.0e-14);
        assert_close(imaginary_axis[3], 0.126_886_660_083_068_56, 1.0e-14);
        assert_close(imaginary_axis[4], 0.126_886_660_083_068_56, 1.0e-14);
        Ok(())
    }

    #[test]
    fn fullspectrum_transforms_reject_invalid_inputs() {
        assert!(matches!(
            full_spectrum_kramers_kronig(FullSpectrumKramersKronigInput {
                omega: array![1.0].view(),
                epsilon2: array![0.2].view(),
            }),
            Err(FullSpectrumError::TooFewRows {
                name: "kramers_kronig",
                len: 1
            })
        ));
        assert!(matches!(
            full_spectrum_kramers_kronig(FullSpectrumKramersKronigInput {
                omega: array![1.0, 1.0].view(),
                epsilon2: array![0.2, 0.3].view(),
            }),
            Err(FullSpectrumError::NonIncreasingOmega { row: 1, .. })
        ));
        assert!(matches!(
            full_spectrum_hamaker_transform(FullSpectrumHamakerInput {
                omega: array![1.0, 2.0].view(),
                epsilon: array![Complex64::new(0.1, f64::NAN), Complex64::new(0.2, 0.3)].view(),
            }),
            Err(FullSpectrumError::NonFiniteValue {
                field: "epsilon imaginary",
                row: 0,
                ..
            })
        ));
        assert!(matches!(
            full_spectrum_hamaker_transform(FullSpectrumHamakerInput {
                omega: array![1.0, 2.0].view(),
                epsilon: array![Complex64::new(0.1, 0.2)].view(),
            }),
            Err(FullSpectrumError::LengthMismatch {
                field: "epsilon",
                ..
            })
        ));
    }

    fn assert_close(actual: Real, expected: Real, tolerance: Real) {
        assert!(
            (actual - expected).abs() <= tolerance * expected.abs().max(1.0),
            "{actual} != {expected}"
        );
    }
}
