//! FEFF path-finder packing helpers.
//!
//! `PATH/ipack.f90` stores up to eight path atom indices in three signed
//! integers by treating each packed field as base 1290. These helpers preserve
//! that representation for compatibility with FEFF path-degeneracy logic.
//! This module also ports the small companion-index min-heap maintenance
//! routines from `PATH/heap.f90` and the path distance/angle builder from
//! `PATH/mrb.f90`. Errors are structured instead of calling `par_stop`.

use ndarray::ArrayView2;
use thiserror::Error;

use crate::{Real, vector::single_precision_distance_between};

const PATH_PACK_BASE: i32 = 1_290;
const PATH_PACK_BASE_SQUARED: i32 = PATH_PACK_BASE * PATH_PACK_BASE;
const MAX_PACKED_PATH_INDICES: usize = 8;
const MAX_PACKED_PATH_VALUE: i32 = PATH_PACK_BASE - 1;
const DOT_COSINE_EPSILON: f32 = 1.0e-8;
const PATH_HASH_SCALE: f32 = 1_000.0;
const PATH_HASH_FACTOR: f32 = 16.123_457;
const PATH_HASH_POTENTIAL_FACTOR: f32 = 8.576_543;
const PATH_HASH_Y_WEIGHT: f32 = 0.894_375;
const PATH_HASH_Z_WEIGHT: f32 = 0.573_498;
const PATH_HASH_LENGTH_OFFSET: Real = 40_000_000.0;

/// Distances and angle cosines generated by FEFF `mrb`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathGeometry {
    /// FEFF `ri`: leg lengths for each path point, including return to absorber.
    pub leg_distances: Vec<Real>,
    /// FEFF `beta`: cosines of scattering angles at each path point.
    pub angle_cosines: Vec<Real>,
    /// Sum of `leg_distances`, matching FEFF's local `rpath`.
    pub total_path_length: Real,
}

/// Error returned by FEFF path helper routines.
#[derive(Debug, Clone, Copy, PartialEq, Error)]
pub enum PathError {
    /// FEFF `ipack` supports at most eight path indices.
    #[error("path packing supports at most {max} indices, got {count}")]
    TooManyIndices { count: usize, max: usize },
    /// Individual packed indices must fit in FEFF's base-1290 digit.
    #[error("path index {position}={value} is outside 0..={max}")]
    IndexOutOfRange {
        position: usize,
        value: i32,
        max: i32,
    },
    /// FEFF `upack` uses an output capacity no larger than eight.
    #[error("path unpack capacity must be at most {max}, got {capacity}")]
    InvalidUnpackCapacity { capacity: usize, max: usize },
    /// The packed path contains more indices than the caller requested.
    #[error("packed path contains {packed_count} indices but capacity is {capacity}")]
    UnpackCapacityTooSmall {
        packed_count: usize,
        capacity: usize,
    },
    /// Packed integers generated by FEFF `ipack` are nonnegative.
    #[error("packed path integer {position} must be nonnegative, got {value}")]
    NegativePackedValue { position: usize, value: i32 },
    /// Heap keys and companion index arrays must have the same length.
    #[error("path heap length mismatch: keys has {keys_len}, indices has {indices_len}")]
    HeapLengthMismatch { keys_len: usize, indices_len: usize },
    /// Heap keys must be finite before ordering them.
    #[error("path heap key at index {index} must be finite, got {value}")]
    NonFiniteHeapKey { index: usize, value: Real },
    /// Atom positions must be an `natoms x 3` Cartesian table.
    #[error(
        "path atom positions must have at least 1 row and exactly 3 columns, got {rows}x{columns}"
    )]
    InvalidAtomPositionShape { rows: usize, columns: usize },
    /// Path atom indices must point into the provided position table.
    #[error(
        "path atom at path position {position} references atom {atom_index}, but only {atoms} atoms are available"
    )]
    AtomIndexOutOfRange {
        position: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// Coordinates used for path geometry must be finite.
    #[error("path atom {atom_index} coordinate {component} must be finite, got {value}")]
    NonFiniteAtomPosition {
        atom_index: usize,
        component: usize,
        value: Real,
    },
    /// Path hash positions must align with one potential index per path atom.
    #[error(
        "path hash positions must be npath x 3 with one potential per row, got {rows}x{columns} and {potentials} potentials"
    )]
    InvalidPathHashShape {
        rows: usize,
        columns: usize,
        potentials: usize,
    },
    /// FEFF path potential indices are nonnegative.
    #[error("path hash potential at position {position} must be nonnegative, got {value}")]
    NegativePathPotential { position: usize, value: i32 },
    /// Coordinates used by FEFF `phash` must fit its single-precision NINT scale.
    #[error(
        "path hash coordinate at position {position} component {component} must fit FEFF NINT scale, got {value}"
    )]
    PathHashCoordinateOutOfRange {
        position: usize,
        component: usize,
        value: Real,
    },
}

/// Port of FEFF `ipack`: pack up to eight path indices into three integers.
///
/// Each path index must be in `0..=1289`, matching the base used by FEFF. The
/// first packed integer stores the path length and the first two indices; the
/// second and third packed integers store the remaining six indices.
pub fn pack_path_indices(indices: &[i32]) -> Result<[i32; 3], PathError> {
    if indices.len() > MAX_PACKED_PATH_INDICES {
        return Err(PathError::TooManyIndices {
            count: indices.len(),
            max: MAX_PACKED_PATH_INDICES,
        });
    }

    let mut padded = [0; MAX_PACKED_PATH_INDICES];
    for (position, &value) in indices.iter().enumerate() {
        validate_path_index(position, value)?;
        padded[position] = value;
    }

    Ok([
        i32::try_from(indices.len()).map_err(|_| PathError::TooManyIndices {
            count: indices.len(),
            max: MAX_PACKED_PATH_INDICES,
        })? + padded[0] * PATH_PACK_BASE
            + padded[1] * PATH_PACK_BASE_SQUARED,
        padded[2] + padded[3] * PATH_PACK_BASE + padded[4] * PATH_PACK_BASE_SQUARED,
        padded[5] + padded[6] * PATH_PACK_BASE + padded[7] * PATH_PACK_BASE_SQUARED,
    ])
}

/// Port of FEFF `upack`: unpack a three-integer path representation.
///
/// `capacity` mirrors FEFF's caller-provided maximum `n`: it must be at most
/// eight and must be no smaller than the packed path length.
pub fn unpack_path_indices(packed: [i32; 3], capacity: usize) -> Result<Vec<i32>, PathError> {
    if capacity > MAX_PACKED_PATH_INDICES {
        return Err(PathError::InvalidUnpackCapacity {
            capacity,
            max: MAX_PACKED_PATH_INDICES,
        });
    }
    for (position, &value) in packed.iter().enumerate() {
        if value < 0 {
            return Err(PathError::NegativePackedValue { position, value });
        }
    }

    let packed_count = usize::try_from(packed[0] % PATH_PACK_BASE).map_err(|_| {
        PathError::NegativePackedValue {
            position: 0,
            value: packed[0],
        }
    })?;
    if packed_count > MAX_PACKED_PATH_INDICES {
        return Err(PathError::TooManyIndices {
            count: packed_count,
            max: MAX_PACKED_PATH_INDICES,
        });
    }
    if packed_count > capacity {
        return Err(PathError::UnpackCapacityTooSmall {
            packed_count,
            capacity,
        });
    }

    let unpacked = [
        (packed[0] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[0] / PATH_PACK_BASE_SQUARED,
        packed[1] % PATH_PACK_BASE,
        (packed[1] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[1] / PATH_PACK_BASE_SQUARED,
        packed[2] % PATH_PACK_BASE,
        (packed[2] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[2] / PATH_PACK_BASE_SQUARED,
    ];

    Ok(unpacked[..packed_count].to_vec())
}

/// Port of FEFF `hup`: bubble the last min-heap element upward.
///
/// `keys` and `indices` are swapped together so callers can keep path metadata
/// associated with the heap key, matching FEFF's `h` and `ih` arrays.
pub fn path_heap_bubble_up(keys: &mut [Real], indices: &mut [i32]) -> Result<(), PathError> {
    validate_heap_inputs(keys, indices)?;
    let mut child = keys.len().saturating_sub(1);
    while child > 0 {
        let parent = (child - 1) / 2;
        if keys[child] < keys[parent] {
            keys.swap(child, parent);
            indices.swap(child, parent);
            child = parent;
        } else {
            break;
        }
    }
    Ok(())
}

/// Port of FEFF `hdown`: bubble the root min-heap element downward.
///
/// This is used after the root has been replaced. The function preserves FEFF's
/// choice of the smaller child and swaps the companion index array with the key.
pub fn path_heap_bubble_down(keys: &mut [Real], indices: &mut [i32]) -> Result<(), PathError> {
    validate_heap_inputs(keys, indices)?;
    let mut parent = 0;
    loop {
        let left = 2 * parent + 1;
        if left >= keys.len() {
            break;
        }
        let right = left + 1;
        let child = if right < keys.len() && keys[left] > keys[right] {
            right
        } else {
            left
        };

        if keys[parent] > keys[child] {
            keys.swap(parent, child);
            indices.swap(parent, child);
            parent = child;
        } else {
            break;
        }
    }
    Ok(())
}

/// Port of FEFF `mrb`: build leg distances and scattering-angle cosines.
///
/// `atom_positions` is indexed by FEFF atom number, with row `0` as the
/// absorber/central atom. `path_indices` are the scattering atoms in the path;
/// the final return to atom `0` is added internally. FEFF performs this
/// calculation in single precision through `sdist`, so Rust casts coordinates
/// through `f32` before evaluating distances and cosines.
pub fn path_geometry(
    atom_positions: ArrayView2<'_, Real>,
    path_indices: &[usize],
) -> Result<PathGeometry, PathError> {
    validate_position_shape(atom_positions)?;
    for (position, &atom_index) in path_indices.iter().enumerate() {
        validate_atom_index(atom_positions, position, atom_index)?;
    }

    let legs = path_indices.len() + 1;
    let mut leg_distances = Vec::with_capacity(legs);
    let mut angle_cosines = Vec::with_capacity(legs);
    let mut total_path_length = 0.0_f32;

    for leg in 0..legs {
        let previous = if leg == 0 { legs - 1 } else { leg - 1 };
        let next = if leg + 1 == legs { 0 } else { leg + 1 };
        let current_atom = path_atom_for_leg(path_indices, leg);
        let previous_atom = path_atom_for_leg(path_indices, previous);
        let next_atom = path_atom_for_leg(path_indices, next);

        let current = atom_position(atom_positions, leg, current_atom)?;
        let previous = atom_position(atom_positions, previous, previous_atom)?;
        let next = atom_position(atom_positions, next, next_atom)?;

        let distance = single_precision_distance_between(current, previous);
        total_path_length += distance;
        leg_distances.push(Real::from(distance));
        angle_cosines.push(Real::from(dot_cosine(previous, current, next)));
    }

    Ok(PathGeometry {
        leg_distances,
        angle_cosines,
        total_path_length: Real::from(total_path_length),
    })
}

/// Port of FEFF `phash`: hash standardized path coordinates and potentials.
///
/// `local_positions` contains one row per scattering atom after FEFF's path
/// frame normalization, using columns `x`, `y`, and `z`. `potential_indices`
/// are the corresponding FEFF potential IDs, equivalent to `ipot(ipat(j))`.
/// FEFF hashes single-precision coordinates after multiplying by `1000` and
/// applying `NINT`; this function preserves that quantization.
pub fn path_degeneracy_hash(
    local_positions: ArrayView2<'_, Real>,
    potential_indices: &[i32],
) -> Result<Real, PathError> {
    validate_hash_input(local_positions, potential_indices)?;

    let mut hash = 0.0;
    let mut coordinate_factor = 1.0_f32;
    for position in 0..local_positions.nrows() {
        let x = rounded_hash_coordinate(local_positions[(position, 0)], position, 0)? as f32;
        let y = rounded_hash_coordinate(local_positions[(position, 1)], position, 1)? as f32;
        let z = rounded_hash_coordinate(local_positions[(position, 2)], position, 2)? as f32;
        let coordinate_term = x + y * PATH_HASH_Y_WEIGHT + z * PATH_HASH_Z_WEIGHT;
        hash += Real::from(coordinate_factor) * Real::from(coordinate_term);
        coordinate_factor *= PATH_HASH_FACTOR;
    }

    let mut potential_factor = 1.0_f32;
    for &potential in potential_indices {
        hash += Real::from(potential_factor) * Real::from(PATH_HASH_SCALE) * Real::from(potential);
        potential_factor *= PATH_HASH_POTENTIAL_FACTOR;
    }

    Ok(hash + local_positions.nrows() as Real * PATH_HASH_LENGTH_OFFSET)
}

fn path_atom_for_leg(path_indices: &[usize], leg: usize) -> usize {
    if leg == path_indices.len() {
        0
    } else {
        path_indices[leg]
    }
}

fn validate_path_index(position: usize, value: i32) -> Result<(), PathError> {
    if (0..=MAX_PACKED_PATH_VALUE).contains(&value) {
        Ok(())
    } else {
        Err(PathError::IndexOutOfRange {
            position,
            value,
            max: MAX_PACKED_PATH_VALUE,
        })
    }
}

fn validate_heap_inputs(keys: &[Real], indices: &[i32]) -> Result<(), PathError> {
    if keys.len() != indices.len() {
        return Err(PathError::HeapLengthMismatch {
            keys_len: keys.len(),
            indices_len: indices.len(),
        });
    }
    for (index, &value) in keys.iter().enumerate() {
        if !value.is_finite() {
            return Err(PathError::NonFiniteHeapKey { index, value });
        }
    }
    Ok(())
}

fn validate_hash_input(
    local_positions: ArrayView2<'_, Real>,
    potential_indices: &[i32],
) -> Result<(), PathError> {
    if local_positions.ncols() != 3 || local_positions.nrows() != potential_indices.len() {
        return Err(PathError::InvalidPathHashShape {
            rows: local_positions.nrows(),
            columns: local_positions.ncols(),
            potentials: potential_indices.len(),
        });
    }

    for (position, &value) in potential_indices.iter().enumerate() {
        if value < 0 {
            return Err(PathError::NegativePathPotential { position, value });
        }
    }
    Ok(())
}

fn rounded_hash_coordinate(
    value: Real,
    position: usize,
    component: usize,
) -> Result<i32, PathError> {
    let single = value as f32;
    if !value.is_finite() || !single.is_finite() {
        return Err(PathError::PathHashCoordinateOutOfRange {
            position,
            component,
            value,
        });
    }

    let scaled = single * PATH_HASH_SCALE;
    let rounded = scaled.round();
    let rounded_real = Real::from(rounded);
    if !rounded.is_finite()
        || rounded_real < Real::from(i32::MIN)
        || rounded_real > Real::from(i32::MAX)
    {
        return Err(PathError::PathHashCoordinateOutOfRange {
            position,
            component,
            value,
        });
    }
    Ok(rounded as i32)
}

fn validate_position_shape(atom_positions: ArrayView2<'_, Real>) -> Result<(), PathError> {
    if atom_positions.nrows() == 0 || atom_positions.ncols() != 3 {
        Err(PathError::InvalidAtomPositionShape {
            rows: atom_positions.nrows(),
            columns: atom_positions.ncols(),
        })
    } else {
        Ok(())
    }
}

fn validate_atom_index(
    atom_positions: ArrayView2<'_, Real>,
    position: usize,
    atom_index: usize,
) -> Result<(), PathError> {
    if atom_index >= atom_positions.nrows() {
        Err(PathError::AtomIndexOutOfRange {
            position,
            atom_index,
            atoms: atom_positions.nrows(),
        })
    } else {
        Ok(())
    }
}

fn atom_position(
    atom_positions: ArrayView2<'_, Real>,
    position: usize,
    atom_index: usize,
) -> Result<[f32; 3], PathError> {
    validate_atom_index(atom_positions, position, atom_index)?;
    let mut point = [0.0_f32; 3];
    for component in 0..3 {
        let value = atom_positions[(atom_index, component)];
        if !value.is_finite() {
            return Err(PathError::NonFiniteAtomPosition {
                atom_index,
                component,
                value,
            });
        }
        point[component] = value as f32;
    }
    Ok(point)
}

fn dot_cosine(previous: [f32; 3], current: [f32; 3], next: [f32; 3]) -> f32 {
    let mut cosine = 0.0_f32;
    for component in 0..3 {
        cosine +=
            (current[component] - previous[component]) * (next[component] - current[component]);
    }
    let denominator = single_precision_distance_between(current, previous)
        * single_precision_distance_between(next, current);
    if denominator > DOT_COSINE_EPSILON {
        cosine / denominator
    } else {
        0.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::arr2;

    const HASH_TOLERANCE: Real = 1.0e-3;
    const MRB_TOLERANCE: Real = 1.0e-7;

    #[test]
    fn pack_path_indices_matches_feff_reference() -> Result<(), PathError> {
        let packed = pack_path_indices(&[0, 12, 1289])?;
        assert_eq!(packed, [19_969_203, 1_289, 0]);
        assert_eq!(unpack_path_indices(packed, 8)?, vec![0, 12, 1289]);

        let packed = pack_path_indices(&[1, 2, 3, 4, 5, 6, 7, 8])?;
        assert_eq!(packed, [3_329_498, 8_325_663, 13_321_836]);
        assert_eq!(
            unpack_path_indices(packed, 8)?,
            vec![1, 2, 3, 4, 5, 6, 7, 8]
        );

        let packed = pack_path_indices(&[1289, 0, 17, 300, 42])?;
        assert_eq!(packed, [1_662_815, 70_279_217, 0]);
        assert_eq!(unpack_path_indices(packed, 8)?, vec![1289, 0, 17, 300, 42]);
        Ok(())
    }

    #[test]
    fn pack_path_indices_rejects_invalid_inputs() {
        assert!(matches!(
            pack_path_indices(&[0, 1, 2, 3, 4, 5, 6, 7, 8]),
            Err(PathError::TooManyIndices { count: 9, .. })
        ));
        assert!(matches!(
            pack_path_indices(&[1290]),
            Err(PathError::IndexOutOfRange {
                position: 0,
                value: 1290,
                ..
            })
        ));
        assert!(matches!(
            unpack_path_indices([3_329_498, 8_325_663, 13_321_836], 7),
            Err(PathError::UnpackCapacityTooSmall {
                packed_count: 8,
                capacity: 7
            })
        ));
        assert!(matches!(
            unpack_path_indices([-1, 0, 0], 8),
            Err(PathError::NegativePackedValue {
                position: 0,
                value: -1
            })
        ));
    }

    #[test]
    fn path_heap_helpers_match_feff_reference() -> Result<(), PathError> {
        let mut keys = [1.0, 3.0, 2.0, 5.0, 4.0, 0.5];
        let mut indices = [10, 30, 20, 50, 40, 5];
        path_heap_bubble_up(&mut keys, &mut indices)?;
        assert_eq!(keys, [0.5, 3.0, 1.0, 5.0, 4.0, 2.0]);
        assert_eq!(indices, [5, 30, 10, 50, 40, 20]);

        let mut keys = [6.0, 2.0, 3.0, 4.0, 5.0];
        let mut indices = [60, 20, 30, 40, 50];
        path_heap_bubble_down(&mut keys, &mut indices)?;
        assert_eq!(keys, [2.0, 4.0, 3.0, 6.0, 5.0]);
        assert_eq!(indices, [20, 40, 30, 60, 50]);

        let mut keys = [0.2, 0.4, 0.3, 0.8, 0.7, 0.5, 0.1];
        let mut indices = [2, 4, 3, 8, 7, 5, 1];
        path_heap_bubble_up(&mut keys, &mut indices)?;
        assert_eq!(keys, [0.1, 0.4, 0.2, 0.8, 0.7, 0.5, 0.3]);
        assert_eq!(indices, [1, 4, 2, 8, 7, 5, 3]);
        Ok(())
    }

    #[test]
    fn path_heap_helpers_reject_invalid_inputs() {
        assert!(matches!(
            path_heap_bubble_up(&mut [1.0, 2.0], &mut [1]),
            Err(PathError::HeapLengthMismatch {
                keys_len: 2,
                indices_len: 1
            })
        ));
        assert!(matches!(
            path_heap_bubble_down(&mut [1.0, Real::NAN], &mut [1, 2]),
            Err(PathError::NonFiniteHeapKey { index: 1, .. })
        ));
    }

    #[test]
    fn path_geometry_matches_feff_mrb_reference() -> Result<(), PathError> {
        let atom_positions = mrb_reference_positions();

        let case_a = path_geometry(atom_positions.view(), &[1, 2, 3])?;
        assert_path_geometry_close(
            &case_a,
            &[1.118_034_005, 1.268_857_718, 2.598_076_344, 1.797_220_111],
            &[
                0.810_643_494_1,
                -0.524_784_803_4,
                -0.516_135_692_6,
                0.104_511_246_1,
            ],
        );

        let case_b = path_geometry(atom_positions.view(), &[5, 1])?;
        assert_path_geometry_close(
            &case_b,
            &[0.0, 1.118_034_005, 1.118_034_005],
            &[0.0, -1.0, 0.0],
        );

        let case_c = path_geometry(atom_positions.view(), &[4, 1, 6, 2])?;
        assert_path_geometry_close(
            &case_c,
            &[
                1.603_121_996,
                1.661_324_859,
                0.0,
                1.268_857_718,
                2.271_563_292,
            ],
            &[
                -0.765_965_223_3,
                0.0,
                0.0,
                -0.957_571_744_9,
                -0.142_794_638_9,
            ],
        );

        Ok(())
    }

    #[test]
    fn path_geometry_rejects_invalid_inputs() {
        let bad_shape = arr2(&[[0.0, 0.0]]);
        assert!(matches!(
            path_geometry(bad_shape.view(), &[]),
            Err(PathError::InvalidAtomPositionShape {
                rows: 1,
                columns: 2
            })
        ));

        let atom_positions = mrb_reference_positions();
        assert!(matches!(
            path_geometry(atom_positions.view(), &[7]),
            Err(PathError::AtomIndexOutOfRange {
                position: 0,
                atom_index: 7,
                atoms: 7
            })
        ));

        let with_nan = arr2(&[[0.0, 0.0, 0.0], [1.0, Real::NAN, 0.0]]);
        assert!(matches!(
            path_geometry(with_nan.view(), &[1]),
            Err(PathError::NonFiniteAtomPosition {
                atom_index: 1,
                component: 1,
                ..
            })
        ));
    }

    #[test]
    fn path_degeneracy_hash_matches_feff_phash_reference() -> Result<(), PathError> {
        let case_a_positions = arr2(&[
            [1.23456, -0.34567, 0.12549],
            [-2.25, 1.5004, -0.9995],
            [0.0, 2.4996, 3.3333],
        ]);
        assert_hash_close(
            path_degeneracy_hash(case_a_positions.view(), &[1, 3, 0])?,
            1.210_820_169_326_026E8,
        );

        let case_b_positions = arr2(&[[-0.0005, 0.0005, -1.2345]]);
        assert_hash_close(
            path_degeneracy_hash(case_b_positions.view(), &[2])?,
            4.000_129_162_432_861E7,
        );

        let case_c_positions = arr2(&[
            [4.4444, -3.3333, 2.2222],
            [-1.1111, 0.0, 1.1111],
            [0.75, -0.25, 0.5],
            [-0.5, -0.75, 1.25],
        ]);
        assert_hash_close(
            path_degeneracy_hash(case_c_positions.view(), &[1, 2, 3, 0])?,
            1.585_427_338_452_837E8,
        );

        Ok(())
    }

    #[test]
    fn path_degeneracy_hash_rejects_invalid_inputs() {
        let bad_shape = arr2(&[[0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(bad_shape.view(), &[1]),
            Err(PathError::InvalidPathHashShape {
                rows: 1,
                columns: 2,
                potentials: 1
            })
        ));

        let positions = arr2(&[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(positions.view(), &[1]),
            Err(PathError::InvalidPathHashShape {
                rows: 2,
                columns: 3,
                potentials: 1
            })
        ));

        let positions = arr2(&[[0.0, 0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(positions.view(), &[-1]),
            Err(PathError::NegativePathPotential {
                position: 0,
                value: -1
            })
        ));

        let positions = arr2(&[[Real::INFINITY, 0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(positions.view(), &[1]),
            Err(PathError::PathHashCoordinateOutOfRange {
                position: 0,
                component: 0,
                ..
            })
        ));
    }

    fn mrb_reference_positions() -> ndarray::Array2<Real> {
        arr2(&[
            [0.0, 0.0, 0.0],
            [1.1, 0.2, 0.0],
            [2.0, 1.0, 0.4],
            [-0.5, 1.7, 0.3],
            [0.7, -1.2, 0.8],
            [0.0, 0.0, 0.0],
            [1.1, 0.2, 0.0],
        ])
    }

    fn assert_path_geometry_close(
        actual: &PathGeometry,
        expected_distances: &[Real],
        expected_cosines: &[Real],
    ) {
        assert_eq!(actual.leg_distances.len(), expected_distances.len());
        assert_eq!(actual.angle_cosines.len(), expected_cosines.len());

        for (&actual, &expected) in actual.leg_distances.iter().zip(expected_distances) {
            assert!(
                (actual - expected).abs() <= MRB_TOLERANCE,
                "leg distance {actual} != {expected}"
            );
        }
        for (&actual, &expected) in actual.angle_cosines.iter().zip(expected_cosines) {
            assert!(
                (actual - expected).abs() <= MRB_TOLERANCE,
                "angle cosine {actual} != {expected}"
            );
        }

        let expected_total = expected_distances
            .iter()
            .fold(0.0_f32, |sum, &distance| sum + distance as f32);
        assert!(
            (actual.total_path_length - Real::from(expected_total)).abs() <= MRB_TOLERANCE,
            "total path length {} != {}",
            actual.total_path_length,
            expected_total
        );
    }

    fn assert_hash_close(actual: Real, expected: Real) {
        assert!(
            (actual - expected).abs() <= HASH_TOLERANCE,
            "path hash {actual} != {expected}"
        );
    }
}
