//! FEFF path-finder packing helpers.
//!
//! `PATH/ipack.f90` stores up to eight path atom indices in three signed
//! integers by treating each packed field as base 1290. These helpers preserve
//! that representation for compatibility with FEFF path-degeneracy logic.
//! This module also ports the small companion-index min-heap maintenance
//! routines from `PATH/heap.f90`. Errors are structured instead of calling
//! `par_stop`.

use thiserror::Error;

use crate::Real;

const PATH_PACK_BASE: i32 = 1_290;
const PATH_PACK_BASE_SQUARED: i32 = PATH_PACK_BASE * PATH_PACK_BASE;
const MAX_PACKED_PATH_INDICES: usize = 8;
const MAX_PACKED_PATH_VALUE: i32 = PATH_PACK_BASE - 1;

/// Error returned by FEFF path helper routines.
#[derive(Debug, Clone, Copy, PartialEq, Error)]
pub enum PathError {
    /// FEFF `ipack` supports at most eight path indices.
    #[error("path packing supports at most {max} indices, got {count}")]
    TooManyIndices { count: usize, max: usize },
    /// Individual packed indices must fit in FEFF's base-1290 digit.
    #[error("path index {position}={value} is outside 0..={max}")]
    IndexOutOfRange {
        position: usize,
        value: i32,
        max: i32,
    },
    /// FEFF `upack` uses an output capacity no larger than eight.
    #[error("path unpack capacity must be at most {max}, got {capacity}")]
    InvalidUnpackCapacity { capacity: usize, max: usize },
    /// The packed path contains more indices than the caller requested.
    #[error("packed path contains {packed_count} indices but capacity is {capacity}")]
    UnpackCapacityTooSmall {
        packed_count: usize,
        capacity: usize,
    },
    /// Packed integers generated by FEFF `ipack` are nonnegative.
    #[error("packed path integer {position} must be nonnegative, got {value}")]
    NegativePackedValue { position: usize, value: i32 },
    /// Heap keys and companion index arrays must have the same length.
    #[error("path heap length mismatch: keys has {keys_len}, indices has {indices_len}")]
    HeapLengthMismatch { keys_len: usize, indices_len: usize },
    /// Heap keys must be finite before ordering them.
    #[error("path heap key at index {index} must be finite, got {value}")]
    NonFiniteHeapKey { index: usize, value: Real },
}

/// Port of FEFF `ipack`: pack up to eight path indices into three integers.
///
/// Each path index must be in `0..=1289`, matching the base used by FEFF. The
/// first packed integer stores the path length and the first two indices; the
/// second and third packed integers store the remaining six indices.
pub fn pack_path_indices(indices: &[i32]) -> Result<[i32; 3], PathError> {
    if indices.len() > MAX_PACKED_PATH_INDICES {
        return Err(PathError::TooManyIndices {
            count: indices.len(),
            max: MAX_PACKED_PATH_INDICES,
        });
    }

    let mut padded = [0; MAX_PACKED_PATH_INDICES];
    for (position, &value) in indices.iter().enumerate() {
        validate_path_index(position, value)?;
        padded[position] = value;
    }

    Ok([
        i32::try_from(indices.len()).map_err(|_| PathError::TooManyIndices {
            count: indices.len(),
            max: MAX_PACKED_PATH_INDICES,
        })? + padded[0] * PATH_PACK_BASE
            + padded[1] * PATH_PACK_BASE_SQUARED,
        padded[2] + padded[3] * PATH_PACK_BASE + padded[4] * PATH_PACK_BASE_SQUARED,
        padded[5] + padded[6] * PATH_PACK_BASE + padded[7] * PATH_PACK_BASE_SQUARED,
    ])
}

/// Port of FEFF `upack`: unpack a three-integer path representation.
///
/// `capacity` mirrors FEFF's caller-provided maximum `n`: it must be at most
/// eight and must be no smaller than the packed path length.
pub fn unpack_path_indices(packed: [i32; 3], capacity: usize) -> Result<Vec<i32>, PathError> {
    if capacity > MAX_PACKED_PATH_INDICES {
        return Err(PathError::InvalidUnpackCapacity {
            capacity,
            max: MAX_PACKED_PATH_INDICES,
        });
    }
    for (position, &value) in packed.iter().enumerate() {
        if value < 0 {
            return Err(PathError::NegativePackedValue { position, value });
        }
    }

    let packed_count = usize::try_from(packed[0] % PATH_PACK_BASE).map_err(|_| {
        PathError::NegativePackedValue {
            position: 0,
            value: packed[0],
        }
    })?;
    if packed_count > MAX_PACKED_PATH_INDICES {
        return Err(PathError::TooManyIndices {
            count: packed_count,
            max: MAX_PACKED_PATH_INDICES,
        });
    }
    if packed_count > capacity {
        return Err(PathError::UnpackCapacityTooSmall {
            packed_count,
            capacity,
        });
    }

    let unpacked = [
        (packed[0] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[0] / PATH_PACK_BASE_SQUARED,
        packed[1] % PATH_PACK_BASE,
        (packed[1] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[1] / PATH_PACK_BASE_SQUARED,
        packed[2] % PATH_PACK_BASE,
        (packed[2] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[2] / PATH_PACK_BASE_SQUARED,
    ];

    Ok(unpacked[..packed_count].to_vec())
}

/// Port of FEFF `hup`: bubble the last min-heap element upward.
///
/// `keys` and `indices` are swapped together so callers can keep path metadata
/// associated with the heap key, matching FEFF's `h` and `ih` arrays.
pub fn path_heap_bubble_up(keys: &mut [Real], indices: &mut [i32]) -> Result<(), PathError> {
    validate_heap_inputs(keys, indices)?;
    let mut child = keys.len().saturating_sub(1);
    while child > 0 {
        let parent = (child - 1) / 2;
        if keys[child] < keys[parent] {
            keys.swap(child, parent);
            indices.swap(child, parent);
            child = parent;
        } else {
            break;
        }
    }
    Ok(())
}

/// Port of FEFF `hdown`: bubble the root min-heap element downward.
///
/// This is used after the root has been replaced. The function preserves FEFF's
/// choice of the smaller child and swaps the companion index array with the key.
pub fn path_heap_bubble_down(keys: &mut [Real], indices: &mut [i32]) -> Result<(), PathError> {
    validate_heap_inputs(keys, indices)?;
    let mut parent = 0;
    loop {
        let left = 2 * parent + 1;
        if left >= keys.len() {
            break;
        }
        let right = left + 1;
        let child = if right < keys.len() && keys[left] > keys[right] {
            right
        } else {
            left
        };

        if keys[parent] > keys[child] {
            keys.swap(parent, child);
            indices.swap(parent, child);
            parent = child;
        } else {
            break;
        }
    }
    Ok(())
}

fn validate_path_index(position: usize, value: i32) -> Result<(), PathError> {
    if (0..=MAX_PACKED_PATH_VALUE).contains(&value) {
        Ok(())
    } else {
        Err(PathError::IndexOutOfRange {
            position,
            value,
            max: MAX_PACKED_PATH_VALUE,
        })
    }
}

fn validate_heap_inputs(keys: &[Real], indices: &[i32]) -> Result<(), PathError> {
    if keys.len() != indices.len() {
        return Err(PathError::HeapLengthMismatch {
            keys_len: keys.len(),
            indices_len: indices.len(),
        });
    }
    for (index, &value) in keys.iter().enumerate() {
        if !value.is_finite() {
            return Err(PathError::NonFiniteHeapKey { index, value });
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pack_path_indices_matches_feff_reference() -> Result<(), PathError> {
        let packed = pack_path_indices(&[0, 12, 1289])?;
        assert_eq!(packed, [19_969_203, 1_289, 0]);
        assert_eq!(unpack_path_indices(packed, 8)?, vec![0, 12, 1289]);

        let packed = pack_path_indices(&[1, 2, 3, 4, 5, 6, 7, 8])?;
        assert_eq!(packed, [3_329_498, 8_325_663, 13_321_836]);
        assert_eq!(
            unpack_path_indices(packed, 8)?,
            vec![1, 2, 3, 4, 5, 6, 7, 8]
        );

        let packed = pack_path_indices(&[1289, 0, 17, 300, 42])?;
        assert_eq!(packed, [1_662_815, 70_279_217, 0]);
        assert_eq!(unpack_path_indices(packed, 8)?, vec![1289, 0, 17, 300, 42]);
        Ok(())
    }

    #[test]
    fn pack_path_indices_rejects_invalid_inputs() {
        assert!(matches!(
            pack_path_indices(&[0, 1, 2, 3, 4, 5, 6, 7, 8]),
            Err(PathError::TooManyIndices { count: 9, .. })
        ));
        assert!(matches!(
            pack_path_indices(&[1290]),
            Err(PathError::IndexOutOfRange {
                position: 0,
                value: 1290,
                ..
            })
        ));
        assert!(matches!(
            unpack_path_indices([3_329_498, 8_325_663, 13_321_836], 7),
            Err(PathError::UnpackCapacityTooSmall {
                packed_count: 8,
                capacity: 7
            })
        ));
        assert!(matches!(
            unpack_path_indices([-1, 0, 0], 8),
            Err(PathError::NegativePackedValue {
                position: 0,
                value: -1
            })
        ));
    }

    #[test]
    fn path_heap_helpers_match_feff_reference() -> Result<(), PathError> {
        let mut keys = [1.0, 3.0, 2.0, 5.0, 4.0, 0.5];
        let mut indices = [10, 30, 20, 50, 40, 5];
        path_heap_bubble_up(&mut keys, &mut indices)?;
        assert_eq!(keys, [0.5, 3.0, 1.0, 5.0, 4.0, 2.0]);
        assert_eq!(indices, [5, 30, 10, 50, 40, 20]);

        let mut keys = [6.0, 2.0, 3.0, 4.0, 5.0];
        let mut indices = [60, 20, 30, 40, 50];
        path_heap_bubble_down(&mut keys, &mut indices)?;
        assert_eq!(keys, [2.0, 4.0, 3.0, 6.0, 5.0]);
        assert_eq!(indices, [20, 40, 30, 60, 50]);

        let mut keys = [0.2, 0.4, 0.3, 0.8, 0.7, 0.5, 0.1];
        let mut indices = [2, 4, 3, 8, 7, 5, 1];
        path_heap_bubble_up(&mut keys, &mut indices)?;
        assert_eq!(keys, [0.1, 0.4, 0.2, 0.8, 0.7, 0.5, 0.3]);
        assert_eq!(indices, [1, 4, 2, 8, 7, 5, 3]);
        Ok(())
    }

    #[test]
    fn path_heap_helpers_reject_invalid_inputs() {
        assert!(matches!(
            path_heap_bubble_up(&mut [1.0, 2.0], &mut [1]),
            Err(PathError::HeapLengthMismatch {
                keys_len: 2,
                indices_len: 1
            })
        ));
        assert!(matches!(
            path_heap_bubble_down(&mut [1.0, Real::NAN], &mut [1, 2]),
            Err(PathError::NonFiniteHeapKey { index: 1, .. })
        ));
    }
}
