//! FEFF path-finder packing helpers.
//!
//! `PATH/ipack.f90` stores up to eight path atom indices in three signed
//! integers by treating each packed field as base 1290. These helpers preserve
//! that representation for compatibility with FEFF path-degeneracy logic.
//! This module also ports the small companion-index min-heap maintenance
//! routines from `PATH/heap.f90`, the path distance/angle builder from
//! `PATH/mrb.f90`, and the path-pruning criteria from `PATH/mcrith.f90` and
//! `PATH/mcritk.f90`. Errors are structured instead of calling `par_stop`.

use ndarray::{ArrayView2, ArrayView3};
use thiserror::Error;

use crate::{Real, vector::single_precision_distance_between};

const PATH_PACK_BASE: i32 = 1_290;
const PATH_PACK_BASE_SQUARED: i32 = PATH_PACK_BASE * PATH_PACK_BASE;
const MAX_PACKED_PATH_INDICES: usize = 8;
const MAX_PACKED_PATH_VALUE: i32 = PATH_PACK_BASE - 1;
const DOT_COSINE_EPSILON: f32 = 1.0e-8;
const PATH_HASH_SCALE: f32 = 1_000.0;
const PATH_HASH_FACTOR: f32 = 16.123_457;
const PATH_HASH_POTENTIAL_FACTOR: f32 = 8.576_543;
const PATH_HASH_Y_WEIGHT: f32 = 0.894_375;
const PATH_HASH_Z_WEIGHT: f32 = 0.573_498;
const PATH_HASH_LENGTH_OFFSET: Real = 40_000_000.0;
const PATH_OUTPUT_MIN_ABS_ANGLE_COSINE: f32 = 0.3;

/// Distances and angle cosines generated by FEFF `mrb`.
#[derive(Debug, Clone, PartialEq)]
pub struct PathGeometry {
    /// FEFF `ri`: leg lengths for each path point, including return to absorber.
    pub leg_distances: Vec<Real>,
    /// FEFF `beta`: cosines of scattering angles at each path point.
    pub angle_cosines: Vec<Real>,
    /// Sum of `leg_distances`, matching FEFF's local `rpath`.
    pub total_path_length: Real,
}

/// Result of FEFF `mcritk` output-importance calculation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PathOutputCriterion {
    /// Output importance factor, or `None` for FEFF's undefined `xout = -1`.
    pub output_importance: Option<Real>,
    /// Updated `xcalcx` normalization. FEFF initializes it from `xcalc` when
    /// the input value is nonpositive.
    pub normalization: Real,
}

/// Inputs for FEFF `mcritk` output-importance calculation.
#[derive(Debug, Clone, Copy)]
pub struct PathOutputCriterionInput<'a> {
    /// FEFF `ipat(1:npat)`: path atom indices, with `0` as absorber.
    pub path_indices: &'a [usize],
    /// FEFF `ri(1:npat+1)`: path leg distances.
    pub leg_distances: &'a [Real],
    /// FEFF `beta(1:npat+1)`: path angle cosines.
    pub angle_cosines: &'a [Real],
    /// FEFF `indbet(1:npat+1)`: discretized beta bins for `fbetac`.
    pub beta_indices: &'a [i32],
    /// Atom-indexed FEFF potential IDs, equivalent to `ipot(atom)`.
    pub atom_potentials: &'a [usize],
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` laid out as
    /// `(2 * nbeta + 1, nph + 1, necrit)`.
    pub fbeta_critical: ArrayView3<'a, Real>,
    /// FEFF `xlamc(1:nncrit)`: mean-free paths for criteria energies.
    pub mean_free_paths: &'a [Real],
    /// FEFF `ckspc(1:nncrit)`: wave numbers for criteria energies.
    pub wave_numbers: &'a [Real],
    /// FEFF `xcalcx`: normalization updated when nonpositive.
    pub current_normalization: Real,
}

/// Error returned by FEFF path helper routines.
#[derive(Debug, Clone, Copy, PartialEq, Error)]
pub enum PathError {
    /// FEFF `ipack` supports at most eight path indices.
    #[error("path packing supports at most {max} indices, got {count}")]
    TooManyIndices { count: usize, max: usize },
    /// Individual packed indices must fit in FEFF's base-1290 digit.
    #[error("path index {position}={value} is outside 0..={max}")]
    IndexOutOfRange {
        position: usize,
        value: i32,
        max: i32,
    },
    /// FEFF `upack` uses an output capacity no larger than eight.
    #[error("path unpack capacity must be at most {max}, got {capacity}")]
    InvalidUnpackCapacity { capacity: usize, max: usize },
    /// The packed path contains more indices than the caller requested.
    #[error("packed path contains {packed_count} indices but capacity is {capacity}")]
    UnpackCapacityTooSmall {
        packed_count: usize,
        capacity: usize,
    },
    /// Packed integers generated by FEFF `ipack` are nonnegative.
    #[error("packed path integer {position} must be nonnegative, got {value}")]
    NegativePackedValue { position: usize, value: i32 },
    /// Heap keys and companion index arrays must have the same length.
    #[error("path heap length mismatch: keys has {keys_len}, indices has {indices_len}")]
    HeapLengthMismatch { keys_len: usize, indices_len: usize },
    /// Heap keys must be finite before ordering them.
    #[error("path heap key at index {index} must be finite, got {value}")]
    NonFiniteHeapKey { index: usize, value: Real },
    /// Atom positions must be an `natoms x 3` Cartesian table.
    #[error(
        "path atom positions must have at least 1 row and exactly 3 columns, got {rows}x{columns}"
    )]
    InvalidAtomPositionShape { rows: usize, columns: usize },
    /// Path atom indices must point into the provided position table.
    #[error(
        "path atom at path position {position} references atom {atom_index}, but only {atoms} atoms are available"
    )]
    AtomIndexOutOfRange {
        position: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// Coordinates used for path geometry must be finite.
    #[error("path atom {atom_index} coordinate {component} must be finite, got {value}")]
    NonFiniteAtomPosition {
        atom_index: usize,
        component: usize,
        value: Real,
    },
    /// Path hash positions must align with one potential index per path atom.
    #[error(
        "path hash positions must be npath x 3 with one potential per row, got {rows}x{columns} and {potentials} potentials"
    )]
    InvalidPathHashShape {
        rows: usize,
        columns: usize,
        potentials: usize,
    },
    /// FEFF path potential indices are nonnegative.
    #[error("path hash potential at position {position} must be nonnegative, got {value}")]
    NegativePathPotential { position: usize, value: i32 },
    /// Coordinates used by FEFF `phash` must fit its single-precision NINT scale.
    #[error(
        "path hash coordinate at position {position} component {component} must fit FEFF NINT scale, got {value}"
    )]
    PathHashCoordinateOutOfRange {
        position: usize,
        component: usize,
        value: Real,
    },
    /// Path criteria need at least one path atom.
    #[error("path criteria require at least one path atom")]
    EmptyPathCriteria,
    /// Criteria arrays must align with FEFF `npat + 1` leg arrays.
    #[error(
        "path criteria expected {expected} leg/beta entries, got {leg_distances} distances and {beta_entries} beta entries"
    )]
    PathCriteriaLengthMismatch {
        expected: usize,
        leg_distances: usize,
        beta_entries: usize,
    },
    /// FEFF `fbetac(-nbeta:nbeta, 0:nph, necrit)` must be centered on zero beta.
    #[error(
        "path criteria fbetac table must have odd beta rows and nonzero potential/criteria dimensions, got {beta_rows}x{potentials}x{criteria}"
    )]
    InvalidPathCriteriaTableShape {
        beta_rows: usize,
        potentials: usize,
        criteria: usize,
    },
    /// The number of criteria energies must fit the table.
    #[error(
        "path criteria wave-number count {wave_numbers} is invalid for fbetac criteria dimension {table_criteria}"
    )]
    PathCriteriaWaveCountMismatch {
        wave_numbers: usize,
        table_criteria: usize,
    },
    /// `mcritk` needs one mean-free path per criteria energy.
    #[error("path criteria has {wave_numbers} wave numbers but {mean_free_paths} mean-free paths")]
    PathCriteriaMeanFreePathCountMismatch {
        wave_numbers: usize,
        mean_free_paths: usize,
    },
    /// Path atom indices must point into the provided potential table.
    #[error(
        "path criteria atom at position {position} references atom {atom_index}, but only {atoms} atom potentials are available"
    )]
    PathCriteriaAtomIndexOutOfRange {
        position: usize,
        atom_index: usize,
        atoms: usize,
    },
    /// Potential indices must point into the FEFF `fbetac` potential dimension.
    #[error(
        "path criteria atom at position {position} uses potential {potential}, but fbetac has {potentials} potentials"
    )]
    PathCriteriaPotentialOutOfRange {
        position: usize,
        potential: usize,
        potentials: usize,
    },
    /// Beta-bin indices must fit the centered FEFF `fbetac` beta dimension.
    #[error(
        "path criteria beta index at position {position} is {beta_index}, outside {min}..={max}"
    )]
    PathCriteriaBetaIndexOutOfRange {
        position: usize,
        beta_index: i32,
        min: i32,
        max: i32,
    },
    /// Floating-point criteria inputs must be finite.
    #[error("path criteria {quantity} at index {index} must be finite, got {value}")]
    NonFinitePathCriteriaValue {
        quantity: &'static str,
        index: usize,
        value: Real,
    },
    /// Divisors in criteria calculations must be positive.
    #[error("path criteria {quantity} at index {index} must be positive, got {value}")]
    NonPositivePathCriteriaValue {
        quantity: &'static str,
        index: usize,
        value: Real,
    },
}

/// Port of FEFF `ipack`: pack up to eight path indices into three integers.
///
/// Each path index must be in `0..=1289`, matching the base used by FEFF. The
/// first packed integer stores the path length and the first two indices; the
/// second and third packed integers store the remaining six indices.
pub fn pack_path_indices(indices: &[i32]) -> Result<[i32; 3], PathError> {
    if indices.len() > MAX_PACKED_PATH_INDICES {
        return Err(PathError::TooManyIndices {
            count: indices.len(),
            max: MAX_PACKED_PATH_INDICES,
        });
    }

    let mut padded = [0; MAX_PACKED_PATH_INDICES];
    for (position, &value) in indices.iter().enumerate() {
        validate_path_index(position, value)?;
        padded[position] = value;
    }

    Ok([
        i32::try_from(indices.len()).map_err(|_| PathError::TooManyIndices {
            count: indices.len(),
            max: MAX_PACKED_PATH_INDICES,
        })? + padded[0] * PATH_PACK_BASE
            + padded[1] * PATH_PACK_BASE_SQUARED,
        padded[2] + padded[3] * PATH_PACK_BASE + padded[4] * PATH_PACK_BASE_SQUARED,
        padded[5] + padded[6] * PATH_PACK_BASE + padded[7] * PATH_PACK_BASE_SQUARED,
    ])
}

/// Port of FEFF `upack`: unpack a three-integer path representation.
///
/// `capacity` mirrors FEFF's caller-provided maximum `n`: it must be at most
/// eight and must be no smaller than the packed path length.
pub fn unpack_path_indices(packed: [i32; 3], capacity: usize) -> Result<Vec<i32>, PathError> {
    if capacity > MAX_PACKED_PATH_INDICES {
        return Err(PathError::InvalidUnpackCapacity {
            capacity,
            max: MAX_PACKED_PATH_INDICES,
        });
    }
    for (position, &value) in packed.iter().enumerate() {
        if value < 0 {
            return Err(PathError::NegativePackedValue { position, value });
        }
    }

    let packed_count = usize::try_from(packed[0] % PATH_PACK_BASE).map_err(|_| {
        PathError::NegativePackedValue {
            position: 0,
            value: packed[0],
        }
    })?;
    if packed_count > MAX_PACKED_PATH_INDICES {
        return Err(PathError::TooManyIndices {
            count: packed_count,
            max: MAX_PACKED_PATH_INDICES,
        });
    }
    if packed_count > capacity {
        return Err(PathError::UnpackCapacityTooSmall {
            packed_count,
            capacity,
        });
    }

    let unpacked = [
        (packed[0] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[0] / PATH_PACK_BASE_SQUARED,
        packed[1] % PATH_PACK_BASE,
        (packed[1] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[1] / PATH_PACK_BASE_SQUARED,
        packed[2] % PATH_PACK_BASE,
        (packed[2] % PATH_PACK_BASE_SQUARED) / PATH_PACK_BASE,
        packed[2] / PATH_PACK_BASE_SQUARED,
    ];

    Ok(unpacked[..packed_count].to_vec())
}

/// Port of FEFF `hup`: bubble the last min-heap element upward.
///
/// `keys` and `indices` are swapped together so callers can keep path metadata
/// associated with the heap key, matching FEFF's `h` and `ih` arrays.
pub fn path_heap_bubble_up(keys: &mut [Real], indices: &mut [i32]) -> Result<(), PathError> {
    validate_heap_inputs(keys, indices)?;
    let mut child = keys.len().saturating_sub(1);
    while child > 0 {
        let parent = (child - 1) / 2;
        if keys[child] < keys[parent] {
            keys.swap(child, parent);
            indices.swap(child, parent);
            child = parent;
        } else {
            break;
        }
    }
    Ok(())
}

/// Port of FEFF `hdown`: bubble the root min-heap element downward.
///
/// This is used after the root has been replaced. The function preserves FEFF's
/// choice of the smaller child and swaps the companion index array with the key.
pub fn path_heap_bubble_down(keys: &mut [Real], indices: &mut [i32]) -> Result<(), PathError> {
    validate_heap_inputs(keys, indices)?;
    let mut parent = 0;
    loop {
        let left = 2 * parent + 1;
        if left >= keys.len() {
            break;
        }
        let right = left + 1;
        let child = if right < keys.len() && keys[left] > keys[right] {
            right
        } else {
            left
        };

        if keys[parent] > keys[child] {
            keys.swap(parent, child);
            indices.swap(parent, child);
            parent = child;
        } else {
            break;
        }
    }
    Ok(())
}

/// Port of FEFF `mrb`: build leg distances and scattering-angle cosines.
///
/// `atom_positions` is indexed by FEFF atom number, with row `0` as the
/// absorber/central atom. `path_indices` are the scattering atoms in the path;
/// the final return to atom `0` is added internally. FEFF performs this
/// calculation in single precision through `sdist`, so Rust casts coordinates
/// through `f32` before evaluating distances and cosines.
pub fn path_geometry(
    atom_positions: ArrayView2<'_, Real>,
    path_indices: &[usize],
) -> Result<PathGeometry, PathError> {
    validate_position_shape(atom_positions)?;
    for (position, &atom_index) in path_indices.iter().enumerate() {
        validate_atom_index(atom_positions, position, atom_index)?;
    }

    let legs = path_indices.len() + 1;
    let mut leg_distances = Vec::with_capacity(legs);
    let mut angle_cosines = Vec::with_capacity(legs);
    let mut total_path_length = 0.0_f32;

    for leg in 0..legs {
        let previous = if leg == 0 { legs - 1 } else { leg - 1 };
        let next = if leg + 1 == legs { 0 } else { leg + 1 };
        let current_atom = path_atom_for_leg(path_indices, leg);
        let previous_atom = path_atom_for_leg(path_indices, previous);
        let next_atom = path_atom_for_leg(path_indices, next);

        let current = atom_position(atom_positions, leg, current_atom)?;
        let previous = atom_position(atom_positions, previous, previous_atom)?;
        let next = atom_position(atom_positions, next, next_atom)?;

        let distance = single_precision_distance_between(current, previous);
        total_path_length += distance;
        leg_distances.push(Real::from(distance));
        angle_cosines.push(Real::from(dot_cosine(previous, current, next)));
    }

    Ok(PathGeometry {
        leg_distances,
        angle_cosines,
        total_path_length: Real::from(total_path_length),
    })
}

/// Port of FEFF `phash`: hash standardized path coordinates and potentials.
///
/// `local_positions` contains one row per scattering atom after FEFF's path
/// frame normalization, using columns `x`, `y`, and `z`. `potential_indices`
/// are the corresponding FEFF potential IDs, equivalent to `ipot(ipat(j))`.
/// FEFF hashes single-precision coordinates after multiplying by `1000` and
/// applying `NINT`; this function preserves that quantization.
pub fn path_degeneracy_hash(
    local_positions: ArrayView2<'_, Real>,
    potential_indices: &[i32],
) -> Result<Real, PathError> {
    validate_hash_input(local_positions, potential_indices)?;

    let mut hash = 0.0;
    let mut coordinate_factor = 1.0_f32;
    for position in 0..local_positions.nrows() {
        let x = rounded_hash_coordinate(local_positions[(position, 0)], position, 0)? as f32;
        let y = rounded_hash_coordinate(local_positions[(position, 1)], position, 1)? as f32;
        let z = rounded_hash_coordinate(local_positions[(position, 2)], position, 2)? as f32;
        let coordinate_term = x + y * PATH_HASH_Y_WEIGHT + z * PATH_HASH_Z_WEIGHT;
        hash += Real::from(coordinate_factor) * Real::from(coordinate_term);
        coordinate_factor *= PATH_HASH_FACTOR;
    }

    let mut potential_factor = 1.0_f32;
    for &potential in potential_indices {
        hash += Real::from(potential_factor) * Real::from(PATH_HASH_SCALE) * Real::from(potential);
        potential_factor *= PATH_HASH_POTENTIAL_FACTOR;
    }

    Ok(hash + local_positions.nrows() as Real * PATH_HASH_LENGTH_OFFSET)
}

/// Port of FEFF `mcrith`: heap importance for extending a partial path.
///
/// `None` corresponds to FEFF's undefined `xheap = -1` branch for paths ending
/// at the absorber or paths with two or fewer atoms. All arithmetic is performed
/// in single precision to match the original PATH code.
pub fn path_heap_criterion(
    path_indices: &[usize],
    leg_distances: &[Real],
    beta_indices: &[i32],
    atom_potentials: &[usize],
    fbeta_critical: ArrayView3<'_, Real>,
    wave_numbers: &[Real],
) -> Result<Option<Real>, PathError> {
    let path_atoms = validate_nonempty_path(path_indices)?;
    if path_indices[path_atoms - 1] == 0 || path_atoms <= 2 {
        return Ok(None);
    }

    let beta_offset = validate_criteria_inputs(
        path_indices,
        path_atoms,
        leg_distances,
        beta_indices,
        atom_potentials,
        fbeta_critical,
        wave_numbers,
    )?;

    let mut heap = 0.0_f32;
    let mut inverse_wave_sum = 0.0_f32;
    for criterion in 0..wave_numbers.len() {
        let wave_number = positive_f32("wave number", criterion, wave_numbers[criterion])?;
        let mut value = wave_number.powi(-((path_atoms as i32) - 1))
            * positive_f32(
                "leg distance",
                path_atoms - 2,
                leg_distances[path_atoms - 2],
            )?;

        for atom_position in 0..path_atoms - 2 {
            let potential = criteria_potential(
                path_indices,
                atom_potentials,
                fbeta_critical.dim().1,
                atom_position,
            )?;
            let beta_row =
                criteria_beta_row(beta_indices[atom_position], beta_offset, atom_position)?;
            let fbeta = finite_f32(
                "fbeta",
                atom_position,
                fbeta_critical[(beta_row, potential, criterion)],
            )?;
            let distance =
                positive_f32("leg distance", atom_position, leg_distances[atom_position])?;
            value = value * fbeta / distance;
        }

        inverse_wave_sum += 1.0 / wave_number;
        heap += value;
    }

    Ok(Some(Real::from(100.0_f32 * heap / inverse_wave_sum)))
}

/// Port of FEFF `mcritk`: output importance for keeping a complete path.
///
/// `None` corresponds to FEFF's undefined `xout = -1` branch for paths ending
/// at the absorber. `current_normalization` is FEFF `xcalcx`; when it is
/// nonpositive, the returned normalization is initialized from the current
/// path's raw `xcalc`.
pub fn path_output_criterion(
    input: PathOutputCriterionInput<'_>,
) -> Result<PathOutputCriterion, PathError> {
    let PathOutputCriterionInput {
        path_indices,
        leg_distances,
        angle_cosines,
        beta_indices,
        atom_potentials,
        fbeta_critical,
        mean_free_paths,
        wave_numbers,
        current_normalization,
    } = input;

    let path_atoms = validate_nonempty_path(path_indices)?;
    let normalization = finite_f32("normalization", 0, current_normalization)?;
    if path_indices[path_atoms - 1] == 0 {
        return Ok(PathOutputCriterion {
            output_importance: None,
            normalization: Real::from(normalization),
        });
    }

    let beta_offset = validate_criteria_inputs(
        path_indices,
        path_atoms,
        leg_distances,
        beta_indices,
        atom_potentials,
        fbeta_critical,
        wave_numbers,
    )?;
    if mean_free_paths.len() != wave_numbers.len() {
        return Err(PathError::PathCriteriaMeanFreePathCountMismatch {
            wave_numbers: wave_numbers.len(),
            mean_free_paths: mean_free_paths.len(),
        });
    }
    if angle_cosines.len() != path_atoms + 1 {
        return Err(PathError::PathCriteriaLengthMismatch {
            expected: path_atoms + 1,
            leg_distances: leg_distances.len(),
            beta_entries: angle_cosines.len(),
        });
    }

    let total_distance = leg_distances
        .iter()
        .enumerate()
        .map(|(index, &value)| positive_f32("leg distance", index, value))
        .try_fold(0.0_f32, |sum, value| Ok(sum + value?))?;

    let mut raw_output = 0.0_f32;
    for criterion in 0..wave_numbers.len() {
        let wave_number = positive_f32("wave number", criterion, wave_numbers[criterion])?;
        let mean_free_path = positive_f32("mean free path", criterion, mean_free_paths[criterion])?;
        let return_distance = positive_f32("leg distance", path_atoms, leg_distances[path_atoms])?;
        let mut value = finite_f32("angle cosine", path_atoms, angle_cosines[path_atoms])?
            .abs()
            .max(PATH_OUTPUT_MIN_ABS_ANGLE_COSINE)
            / (return_distance * wave_number);

        for atom_position in 0..path_atoms {
            let potential = criteria_potential(
                path_indices,
                atom_potentials,
                fbeta_critical.dim().1,
                atom_position,
            )?;
            let beta_row =
                criteria_beta_row(beta_indices[atom_position], beta_offset, atom_position)?;
            let fbeta = finite_f32(
                "fbeta",
                atom_position,
                fbeta_critical[(beta_row, potential, criterion)],
            )?;
            let distance =
                positive_f32("leg distance", atom_position, leg_distances[atom_position])?;
            value = value * fbeta / (distance * wave_number);
        }

        value *= (-total_distance / mean_free_path).exp();
        raw_output += value;
    }

    let updated_normalization = if normalization <= 0.0 {
        raw_output
    } else {
        normalization
    };
    Ok(PathOutputCriterion {
        output_importance: Some(Real::from(100.0_f32 * raw_output / updated_normalization)),
        normalization: Real::from(updated_normalization),
    })
}

fn path_atom_for_leg(path_indices: &[usize], leg: usize) -> usize {
    if leg == path_indices.len() {
        0
    } else {
        path_indices[leg]
    }
}

fn validate_nonempty_path(path_indices: &[usize]) -> Result<usize, PathError> {
    if path_indices.is_empty() {
        Err(PathError::EmptyPathCriteria)
    } else {
        Ok(path_indices.len())
    }
}

fn validate_criteria_inputs(
    path_indices: &[usize],
    path_atoms: usize,
    leg_distances: &[Real],
    beta_indices: &[i32],
    atom_potentials: &[usize],
    fbeta_critical: ArrayView3<'_, Real>,
    wave_numbers: &[Real],
) -> Result<i32, PathError> {
    let expected = path_atoms + 1;
    if leg_distances.len() != expected || beta_indices.len() != expected {
        return Err(PathError::PathCriteriaLengthMismatch {
            expected,
            leg_distances: leg_distances.len(),
            beta_entries: beta_indices.len(),
        });
    }

    let (beta_rows, potentials, criteria) = fbeta_critical.dim();
    if beta_rows == 0 || beta_rows % 2 == 0 || potentials == 0 || criteria == 0 {
        return Err(PathError::InvalidPathCriteriaTableShape {
            beta_rows,
            potentials,
            criteria,
        });
    }
    if wave_numbers.is_empty() || wave_numbers.len() > criteria {
        return Err(PathError::PathCriteriaWaveCountMismatch {
            wave_numbers: wave_numbers.len(),
            table_criteria: criteria,
        });
    }

    let beta_offset = (beta_rows as i32 - 1) / 2;
    for (atom_position, &beta_index) in beta_indices.iter().take(path_atoms).enumerate() {
        criteria_potential(path_indices, atom_potentials, potentials, atom_position)?;
        criteria_beta_row(beta_index, beta_offset, atom_position)?;
    }
    for (index, &value) in leg_distances.iter().enumerate() {
        positive_f32("leg distance", index, value)?;
    }
    for (index, &value) in wave_numbers.iter().enumerate() {
        positive_f32("wave number", index, value)?;
    }

    Ok(beta_offset)
}

fn criteria_potential(
    path_indices: &[usize],
    atom_potentials: &[usize],
    potential_count: usize,
    position: usize,
) -> Result<usize, PathError> {
    let atom_index = path_indices[position];
    let Some(&potential) = atom_potentials.get(atom_index) else {
        return Err(PathError::PathCriteriaAtomIndexOutOfRange {
            position,
            atom_index,
            atoms: atom_potentials.len(),
        });
    };
    if potential >= potential_count {
        return Err(PathError::PathCriteriaPotentialOutOfRange {
            position,
            potential,
            potentials: potential_count,
        });
    }
    Ok(potential)
}

fn criteria_beta_row(
    beta_index: i32,
    beta_offset: i32,
    position: usize,
) -> Result<usize, PathError> {
    let min = -beta_offset;
    let max = beta_offset;
    if beta_index < min || beta_index > max {
        return Err(PathError::PathCriteriaBetaIndexOutOfRange {
            position,
            beta_index,
            min,
            max,
        });
    }
    Ok((beta_index + beta_offset) as usize)
}

fn finite_f32(quantity: &'static str, index: usize, value: Real) -> Result<f32, PathError> {
    let single = value as f32;
    if value.is_finite() && single.is_finite() {
        Ok(single)
    } else {
        Err(PathError::NonFinitePathCriteriaValue {
            quantity,
            index,
            value,
        })
    }
}

fn positive_f32(quantity: &'static str, index: usize, value: Real) -> Result<f32, PathError> {
    let single = finite_f32(quantity, index, value)?;
    if single > 0.0 {
        Ok(single)
    } else {
        Err(PathError::NonPositivePathCriteriaValue {
            quantity,
            index,
            value,
        })
    }
}

fn validate_path_index(position: usize, value: i32) -> Result<(), PathError> {
    if (0..=MAX_PACKED_PATH_VALUE).contains(&value) {
        Ok(())
    } else {
        Err(PathError::IndexOutOfRange {
            position,
            value,
            max: MAX_PACKED_PATH_VALUE,
        })
    }
}

fn validate_heap_inputs(keys: &[Real], indices: &[i32]) -> Result<(), PathError> {
    if keys.len() != indices.len() {
        return Err(PathError::HeapLengthMismatch {
            keys_len: keys.len(),
            indices_len: indices.len(),
        });
    }
    for (index, &value) in keys.iter().enumerate() {
        if !value.is_finite() {
            return Err(PathError::NonFiniteHeapKey { index, value });
        }
    }
    Ok(())
}

fn validate_hash_input(
    local_positions: ArrayView2<'_, Real>,
    potential_indices: &[i32],
) -> Result<(), PathError> {
    if local_positions.ncols() != 3 || local_positions.nrows() != potential_indices.len() {
        return Err(PathError::InvalidPathHashShape {
            rows: local_positions.nrows(),
            columns: local_positions.ncols(),
            potentials: potential_indices.len(),
        });
    }

    for (position, &value) in potential_indices.iter().enumerate() {
        if value < 0 {
            return Err(PathError::NegativePathPotential { position, value });
        }
    }
    Ok(())
}

fn rounded_hash_coordinate(
    value: Real,
    position: usize,
    component: usize,
) -> Result<i32, PathError> {
    let single = value as f32;
    if !value.is_finite() || !single.is_finite() {
        return Err(PathError::PathHashCoordinateOutOfRange {
            position,
            component,
            value,
        });
    }

    let scaled = single * PATH_HASH_SCALE;
    let rounded = scaled.round();
    let rounded_real = Real::from(rounded);
    if !rounded.is_finite()
        || rounded_real < Real::from(i32::MIN)
        || rounded_real > Real::from(i32::MAX)
    {
        return Err(PathError::PathHashCoordinateOutOfRange {
            position,
            component,
            value,
        });
    }
    Ok(rounded as i32)
}

fn validate_position_shape(atom_positions: ArrayView2<'_, Real>) -> Result<(), PathError> {
    if atom_positions.nrows() == 0 || atom_positions.ncols() != 3 {
        Err(PathError::InvalidAtomPositionShape {
            rows: atom_positions.nrows(),
            columns: atom_positions.ncols(),
        })
    } else {
        Ok(())
    }
}

fn validate_atom_index(
    atom_positions: ArrayView2<'_, Real>,
    position: usize,
    atom_index: usize,
) -> Result<(), PathError> {
    if atom_index >= atom_positions.nrows() {
        Err(PathError::AtomIndexOutOfRange {
            position,
            atom_index,
            atoms: atom_positions.nrows(),
        })
    } else {
        Ok(())
    }
}

fn atom_position(
    atom_positions: ArrayView2<'_, Real>,
    position: usize,
    atom_index: usize,
) -> Result<[f32; 3], PathError> {
    validate_atom_index(atom_positions, position, atom_index)?;
    let mut point = [0.0_f32; 3];
    for component in 0..3 {
        let value = atom_positions[(atom_index, component)];
        if !value.is_finite() {
            return Err(PathError::NonFiniteAtomPosition {
                atom_index,
                component,
                value,
            });
        }
        point[component] = value as f32;
    }
    Ok(point)
}

fn dot_cosine(previous: [f32; 3], current: [f32; 3], next: [f32; 3]) -> f32 {
    let mut cosine = 0.0_f32;
    for component in 0..3 {
        cosine +=
            (current[component] - previous[component]) * (next[component] - current[component]);
    }
    let denominator = single_precision_distance_between(current, previous)
        * single_precision_distance_between(next, current);
    if denominator > DOT_COSINE_EPSILON {
        cosine / denominator
    } else {
        0.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::{Array3, arr2};

    const CRITERION_TOLERANCE: Real = 1.0e-6;
    const HASH_TOLERANCE: Real = 1.0e-3;
    const MRB_TOLERANCE: Real = 1.0e-7;

    #[test]
    fn pack_path_indices_matches_feff_reference() -> Result<(), PathError> {
        let packed = pack_path_indices(&[0, 12, 1289])?;
        assert_eq!(packed, [19_969_203, 1_289, 0]);
        assert_eq!(unpack_path_indices(packed, 8)?, vec![0, 12, 1289]);

        let packed = pack_path_indices(&[1, 2, 3, 4, 5, 6, 7, 8])?;
        assert_eq!(packed, [3_329_498, 8_325_663, 13_321_836]);
        assert_eq!(
            unpack_path_indices(packed, 8)?,
            vec![1, 2, 3, 4, 5, 6, 7, 8]
        );

        let packed = pack_path_indices(&[1289, 0, 17, 300, 42])?;
        assert_eq!(packed, [1_662_815, 70_279_217, 0]);
        assert_eq!(unpack_path_indices(packed, 8)?, vec![1289, 0, 17, 300, 42]);
        Ok(())
    }

    #[test]
    fn pack_path_indices_rejects_invalid_inputs() {
        assert!(matches!(
            pack_path_indices(&[0, 1, 2, 3, 4, 5, 6, 7, 8]),
            Err(PathError::TooManyIndices { count: 9, .. })
        ));
        assert!(matches!(
            pack_path_indices(&[1290]),
            Err(PathError::IndexOutOfRange {
                position: 0,
                value: 1290,
                ..
            })
        ));
        assert!(matches!(
            unpack_path_indices([3_329_498, 8_325_663, 13_321_836], 7),
            Err(PathError::UnpackCapacityTooSmall {
                packed_count: 8,
                capacity: 7
            })
        ));
        assert!(matches!(
            unpack_path_indices([-1, 0, 0], 8),
            Err(PathError::NegativePackedValue {
                position: 0,
                value: -1
            })
        ));
    }

    #[test]
    fn path_heap_helpers_match_feff_reference() -> Result<(), PathError> {
        let mut keys = [1.0, 3.0, 2.0, 5.0, 4.0, 0.5];
        let mut indices = [10, 30, 20, 50, 40, 5];
        path_heap_bubble_up(&mut keys, &mut indices)?;
        assert_eq!(keys, [0.5, 3.0, 1.0, 5.0, 4.0, 2.0]);
        assert_eq!(indices, [5, 30, 10, 50, 40, 20]);

        let mut keys = [6.0, 2.0, 3.0, 4.0, 5.0];
        let mut indices = [60, 20, 30, 40, 50];
        path_heap_bubble_down(&mut keys, &mut indices)?;
        assert_eq!(keys, [2.0, 4.0, 3.0, 6.0, 5.0]);
        assert_eq!(indices, [20, 40, 30, 60, 50]);

        let mut keys = [0.2, 0.4, 0.3, 0.8, 0.7, 0.5, 0.1];
        let mut indices = [2, 4, 3, 8, 7, 5, 1];
        path_heap_bubble_up(&mut keys, &mut indices)?;
        assert_eq!(keys, [0.1, 0.4, 0.2, 0.8, 0.7, 0.5, 0.3]);
        assert_eq!(indices, [1, 4, 2, 8, 7, 5, 3]);
        Ok(())
    }

    #[test]
    fn path_heap_helpers_reject_invalid_inputs() {
        assert!(matches!(
            path_heap_bubble_up(&mut [1.0, 2.0], &mut [1]),
            Err(PathError::HeapLengthMismatch {
                keys_len: 2,
                indices_len: 1
            })
        ));
        assert!(matches!(
            path_heap_bubble_down(&mut [1.0, Real::NAN], &mut [1, 2]),
            Err(PathError::NonFiniteHeapKey { index: 1, .. })
        ));
    }

    #[test]
    fn path_geometry_matches_feff_mrb_reference() -> Result<(), PathError> {
        let atom_positions = mrb_reference_positions();

        let case_a = path_geometry(atom_positions.view(), &[1, 2, 3])?;
        assert_path_geometry_close(
            &case_a,
            &[1.118_034_005, 1.268_857_718, 2.598_076_344, 1.797_220_111],
            &[
                0.810_643_494_1,
                -0.524_784_803_4,
                -0.516_135_692_6,
                0.104_511_246_1,
            ],
        );

        let case_b = path_geometry(atom_positions.view(), &[5, 1])?;
        assert_path_geometry_close(
            &case_b,
            &[0.0, 1.118_034_005, 1.118_034_005],
            &[0.0, -1.0, 0.0],
        );

        let case_c = path_geometry(atom_positions.view(), &[4, 1, 6, 2])?;
        assert_path_geometry_close(
            &case_c,
            &[
                1.603_121_996,
                1.661_324_859,
                0.0,
                1.268_857_718,
                2.271_563_292,
            ],
            &[
                -0.765_965_223_3,
                0.0,
                0.0,
                -0.957_571_744_9,
                -0.142_794_638_9,
            ],
        );

        Ok(())
    }

    #[test]
    fn path_geometry_rejects_invalid_inputs() {
        let bad_shape = arr2(&[[0.0, 0.0]]);
        assert!(matches!(
            path_geometry(bad_shape.view(), &[]),
            Err(PathError::InvalidAtomPositionShape {
                rows: 1,
                columns: 2
            })
        ));

        let atom_positions = mrb_reference_positions();
        assert!(matches!(
            path_geometry(atom_positions.view(), &[7]),
            Err(PathError::AtomIndexOutOfRange {
                position: 0,
                atom_index: 7,
                atoms: 7
            })
        ));

        let with_nan = arr2(&[[0.0, 0.0, 0.0], [1.0, Real::NAN, 0.0]]);
        assert!(matches!(
            path_geometry(with_nan.view(), &[1]),
            Err(PathError::NonFiniteAtomPosition {
                atom_index: 1,
                component: 1,
                ..
            })
        ));
    }

    #[test]
    fn path_degeneracy_hash_matches_feff_phash_reference() -> Result<(), PathError> {
        let case_a_positions = arr2(&[
            [1.23456, -0.34567, 0.12549],
            [-2.25, 1.5004, -0.9995],
            [0.0, 2.4996, 3.3333],
        ]);
        assert_hash_close(
            path_degeneracy_hash(case_a_positions.view(), &[1, 3, 0])?,
            1.210_820_169_326_026E8,
        );

        let case_b_positions = arr2(&[[-0.0005, 0.0005, -1.2345]]);
        assert_hash_close(
            path_degeneracy_hash(case_b_positions.view(), &[2])?,
            4.000_129_162_432_861E7,
        );

        let case_c_positions = arr2(&[
            [4.4444, -3.3333, 2.2222],
            [-1.1111, 0.0, 1.1111],
            [0.75, -0.25, 0.5],
            [-0.5, -0.75, 1.25],
        ]);
        assert_hash_close(
            path_degeneracy_hash(case_c_positions.view(), &[1, 2, 3, 0])?,
            1.585_427_338_452_837E8,
        );

        Ok(())
    }

    #[test]
    fn path_degeneracy_hash_rejects_invalid_inputs() {
        let bad_shape = arr2(&[[0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(bad_shape.view(), &[1]),
            Err(PathError::InvalidPathHashShape {
                rows: 1,
                columns: 2,
                potentials: 1
            })
        ));

        let positions = arr2(&[[0.0, 0.0, 0.0], [1.0, 0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(positions.view(), &[1]),
            Err(PathError::InvalidPathHashShape {
                rows: 2,
                columns: 3,
                potentials: 1
            })
        ));

        let positions = arr2(&[[0.0, 0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(positions.view(), &[-1]),
            Err(PathError::NegativePathPotential {
                position: 0,
                value: -1
            })
        ));

        let positions = arr2(&[[Real::INFINITY, 0.0, 0.0]]);
        assert!(matches!(
            path_degeneracy_hash(positions.view(), &[1]),
            Err(PathError::PathHashCoordinateOutOfRange {
                position: 0,
                component: 0,
                ..
            })
        ));
    }

    #[test]
    fn path_criteria_match_feff_references() -> Result<(), PathError> {
        let path_indices = [1, 2, 3, 4];
        let leg_distances = [1.10, 1.25, 1.40, 1.60, 1.20];
        let angle_cosines = [0.80, -0.35, 0.55, -0.10, 0.25];
        let beta_indices = [-3, 4, 10, -2, 0];
        let atom_potentials = reference_atom_potentials();
        let fbeta = reference_fbeta_table();
        let wave_numbers = [2.0, 3.5, 5.0];
        let mean_free_paths = [7.5, 10.0, 12.0];

        assert_option_close(
            path_heap_criterion(
                &path_indices,
                &leg_distances,
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            )?,
            Some(4.501_763_821),
        );

        let initialized = path_output_criterion(PathOutputCriterionInput {
            path_indices: &path_indices,
            leg_distances: &leg_distances,
            angle_cosines: &angle_cosines,
            beta_indices: &beta_indices,
            atom_potentials: &atom_potentials,
            fbeta_critical: fbeta.view(),
            mean_free_paths: &mean_free_paths,
            wave_numbers: &wave_numbers,
            current_normalization: -1.0,
        })?;
        assert_option_close(initialized.output_importance, Some(100.0));
        assert_close(initialized.normalization, 9.197_448_526E-05);

        let fixed_angle_cosines = [0.80, -0.35, 0.55, -0.10, -0.80];
        let fixed = path_output_criterion(PathOutputCriterionInput {
            path_indices: &path_indices,
            leg_distances: &leg_distances,
            angle_cosines: &fixed_angle_cosines,
            beta_indices: &beta_indices,
            atom_potentials: &atom_potentials,
            fbeta_critical: fbeta.view(),
            mean_free_paths: &mean_free_paths,
            wave_numbers: &wave_numbers,
            current_normalization: 0.004,
        })?;
        assert_option_close(fixed.output_importance, Some(6.131_631_851));
        assert_close(fixed.normalization, 4.000_000_190E-03);

        let central_path = [1, 2, 3, 0];
        assert_eq!(
            path_heap_criterion(
                &central_path,
                &leg_distances,
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            )?,
            None
        );
        let central = path_output_criterion(PathOutputCriterionInput {
            path_indices: &central_path,
            leg_distances: &leg_distances,
            angle_cosines: &fixed_angle_cosines,
            beta_indices: &beta_indices,
            atom_potentials: &atom_potentials,
            fbeta_critical: fbeta.view(),
            mean_free_paths: &mean_free_paths,
            wave_numbers: &wave_numbers,
            current_normalization: 0.004,
        })?;
        assert_eq!(central.output_importance, None);
        assert_close(central.normalization, 4.000_000_190E-03);

        let short_path = [1, 2];
        assert_eq!(
            path_heap_criterion(
                &short_path,
                &leg_distances,
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            )?,
            None
        );
        Ok(())
    }

    #[test]
    fn path_criteria_reject_invalid_inputs() {
        let path_indices = [1, 2, 3, 4];
        let leg_distances = [1.10, 1.25, 1.40, 1.60, 1.20];
        let angle_cosines = [0.80, -0.35, 0.55, -0.10, 0.25];
        let beta_indices = [-3, 4, 10, -2, 0];
        let atom_potentials = reference_atom_potentials();
        let fbeta = reference_fbeta_table();
        let wave_numbers = [2.0, 3.5, 5.0];
        let mean_free_paths = [7.5, 10.0, 12.0];

        assert!(matches!(
            path_heap_criterion(
                &[],
                &leg_distances,
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            ),
            Err(PathError::EmptyPathCriteria)
        ));
        assert!(matches!(
            path_heap_criterion(
                &path_indices,
                &leg_distances[..4],
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            ),
            Err(PathError::PathCriteriaLengthMismatch {
                expected: 5,
                leg_distances: 4,
                beta_entries: 5
            })
        ));

        let bad_table = Array3::zeros((80, 4, 3));
        assert!(matches!(
            path_heap_criterion(
                &path_indices,
                &leg_distances,
                &beta_indices,
                &atom_potentials,
                bad_table.view(),
                &wave_numbers,
            ),
            Err(PathError::InvalidPathCriteriaTableShape { beta_rows: 80, .. })
        ));
        assert!(matches!(
            path_heap_criterion(
                &path_indices,
                &leg_distances,
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &[],
            ),
            Err(PathError::PathCriteriaWaveCountMismatch {
                wave_numbers: 0,
                ..
            })
        ));

        let bad_beta_indices = [-41, 4, 10, -2, 0];
        assert!(matches!(
            path_heap_criterion(
                &path_indices,
                &leg_distances,
                &bad_beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            ),
            Err(PathError::PathCriteriaBetaIndexOutOfRange {
                position: 0,
                beta_index: -41,
                ..
            })
        ));

        let short_potentials = [0, 1, 2];
        assert!(matches!(
            path_heap_criterion(
                &path_indices,
                &leg_distances,
                &beta_indices,
                &short_potentials,
                fbeta.view(),
                &wave_numbers,
            ),
            Err(PathError::PathCriteriaAtomIndexOutOfRange {
                position: 2,
                atom_index: 3,
                atoms: 3
            })
        ));

        let bad_distances = [1.10, 0.0, 1.40, 1.60, 1.20];
        assert!(matches!(
            path_heap_criterion(
                &path_indices,
                &bad_distances,
                &beta_indices,
                &atom_potentials,
                fbeta.view(),
                &wave_numbers,
            ),
            Err(PathError::NonPositivePathCriteriaValue {
                quantity: "leg distance",
                index: 1,
                ..
            })
        ));

        assert!(matches!(
            path_output_criterion(PathOutputCriterionInput {
                path_indices: &path_indices,
                leg_distances: &leg_distances,
                angle_cosines: &angle_cosines,
                beta_indices: &beta_indices,
                atom_potentials: &atom_potentials,
                fbeta_critical: fbeta.view(),
                mean_free_paths: &mean_free_paths[..2],
                wave_numbers: &wave_numbers,
                current_normalization: 1.0,
            }),
            Err(PathError::PathCriteriaMeanFreePathCountMismatch {
                wave_numbers: 3,
                mean_free_paths: 2
            })
        ));
    }

    fn mrb_reference_positions() -> ndarray::Array2<Real> {
        arr2(&[
            [0.0, 0.0, 0.0],
            [1.1, 0.2, 0.0],
            [2.0, 1.0, 0.4],
            [-0.5, 1.7, 0.3],
            [0.7, -1.2, 0.8],
            [0.0, 0.0, 0.0],
            [1.1, 0.2, 0.0],
        ])
    }

    fn assert_path_geometry_close(
        actual: &PathGeometry,
        expected_distances: &[Real],
        expected_cosines: &[Real],
    ) {
        assert_eq!(actual.leg_distances.len(), expected_distances.len());
        assert_eq!(actual.angle_cosines.len(), expected_cosines.len());

        for (&actual, &expected) in actual.leg_distances.iter().zip(expected_distances) {
            assert!(
                (actual - expected).abs() <= MRB_TOLERANCE,
                "leg distance {actual} != {expected}"
            );
        }
        for (&actual, &expected) in actual.angle_cosines.iter().zip(expected_cosines) {
            assert!(
                (actual - expected).abs() <= MRB_TOLERANCE,
                "angle cosine {actual} != {expected}"
            );
        }

        let expected_total = expected_distances
            .iter()
            .fold(0.0_f32, |sum, &distance| sum + distance as f32);
        assert!(
            (actual.total_path_length - Real::from(expected_total)).abs() <= MRB_TOLERANCE,
            "total path length {} != {}",
            actual.total_path_length,
            expected_total
        );
    }

    fn assert_hash_close(actual: Real, expected: Real) {
        assert!(
            (actual - expected).abs() <= HASH_TOLERANCE,
            "path hash {actual} != {expected}"
        );
    }

    fn reference_atom_potentials() -> Vec<usize> {
        (0..=8).map(|index| index % 4).collect()
    }

    fn reference_fbeta_table() -> Array3<Real> {
        Array3::from_shape_fn((81, 4, 3), |(beta_row, potential, criterion)| {
            let beta_index = beta_row as i32 - 40;
            Real::from(
                0.5_f32
                    + 0.01_f32 * potential as f32
                    + 0.002_f32 * (criterion + 1) as f32
                    + 0.003_f32 * beta_index.abs() as f32
                    + 0.0001_f32 * beta_index as f32,
            )
        })
    }

    fn assert_option_close(actual: Option<Real>, expected: Option<Real>) {
        match (actual, expected) {
            (Some(actual), Some(expected)) => assert_close(actual, expected),
            (actual, expected) => assert_eq!(actual, expected),
        }
    }

    fn assert_close(actual: Real, expected: Real) {
        assert!(
            (actual - expected).abs() <= CRITERION_TOLERANCE,
            "path criterion {actual} != {expected}"
        );
    }
}
