//! Self-energy singularity helpers ported from FEFF.
//!
//! `SELF/fndsng.f90` finds real singularities of the Hedin-Lundqvist
//! self-energy integrands by solving the FEFF cubic and quadratic equations,
//! filtering roots to the integration window, and sorting the accepted values.
//! This module also ports the small `SELF/omegaq.f90` dispersion helpers and
//! the `SELF/logi.f90` logarithm branch helper used by the BPR integrands.

use std::cmp::Ordering;

use ndarray::ArrayView1;

use crate::{
    Complex, InterpolationError, Real, RootError, SpecialFunctionError, cubic_zeros,
    quadratic_zeros, terp, x_log_x,
};

const SINGULARITY_TOLERANCE: Real = 1.0e-4;
const MKEXC_FINE_POINTS: usize = 50_000;
const MKEXC_WIDTH_EV: Real = 0.1;

/// FEFF self-energy integrand selector used by `FndSng`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SingularityFunction {
    /// FEFF `iFcn = 1`: solve both equation families.
    First,
    /// FEFF `iFcn = 2`: solve only the cubic equation family.
    Second,
}

/// One row of FEFF `exc.dat` generated by `MkExc`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ExcitationPole {
    /// FEFF `Wi`: pole energy in the same units as the input loss grid.
    pub energy: Real,
    /// FEFF writes a fixed broadened-pole width of `0.1`.
    pub width: Real,
    /// FEFF `gi`: pole amplitude after static-dielectric scaling.
    pub amplitude: Real,
    /// Fourth FEFF `exc.dat` column: `pi / 2 * gi * Wi / Delta`.
    pub loss_height: Real,
}

/// Error returned by self-energy singularity helpers.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum SelfEnergyError {
    /// FEFF only defines singularity selectors `1` and `2`.
    #[error("invalid self-energy singularity function {value}; expected 1 or 2")]
    InvalidFunction { value: i32 },
    /// Inputs must have finite real and imaginary parts.
    #[error("self-energy input {name} must be finite, got {value:?}")]
    NonFiniteComplex { name: &'static str, value: Complex },
    /// Inputs must be finite real values.
    #[error("self-energy input {name} must be finite, got {value}")]
    NonFiniteReal { name: &'static str, value: Real },
    /// Inputs used as positive scales must be strictly positive.
    #[error("self-energy input {name} must be positive, got {value}")]
    NonPositiveReal { name: &'static str, value: Real },
    /// Inputs used as nonnegative values must be zero or positive.
    #[error("self-energy input {name} must be nonnegative, got {value}")]
    NegativeReal { name: &'static str, value: Real },
    /// Loss grids must contain matching energy and loss columns.
    #[error(
        "self-energy loss grid length mismatch: energy has {energy_len} values but loss has {loss_len}"
    )]
    LossGridLengthMismatch { energy_len: usize, loss_len: usize },
    /// FEFF `MkExc` needs at least two loss-grid points for linear interpolation.
    #[error("self-energy loss grid requires at least 2 points, got {len}")]
    InsufficientLossGrid { len: usize },
    /// `MkExc` must be asked for at least one pole.
    #[error("requested excitation pole count must be positive")]
    InvalidPoleCount,
    /// FEFF loss grids are monotonic energy tables.
    #[error(
        "self-energy loss-grid energy must increase strictly at index {index}: previous={previous}, current={current}"
    )]
    NonIncreasingLossEnergy {
        index: usize,
        previous: Real,
        current: Real,
    },
    /// A loss-grid moment that FEFF divides by became zero.
    #[error("self-energy moment {name} is zero")]
    ZeroMoment { name: &'static str },
    /// A computed real square-root radicand fell outside the FEFF branch.
    #[error("self-energy radicand {name} must be nonnegative, got {value}")]
    NegativeRadicand { name: &'static str, value: Real },
    /// FEFF formula denominator is singular for this input.
    #[error("self-energy denominator {name} is zero")]
    ZeroDenominator { name: &'static str },
    /// A special-function helper failed.
    #[error(transparent)]
    SpecialFunction(#[from] SpecialFunctionError),
    /// Polynomial root solving failed.
    #[error(transparent)]
    Root(#[from] RootError),
    /// FEFF interpolation failed while processing a loss grid.
    #[error(transparent)]
    Interpolation(#[from] InterpolationError),
}

impl TryFrom<i32> for SingularityFunction {
    type Error = SelfEnergyError;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::First),
            2 => Ok(Self::Second),
            value => Err(SelfEnergyError::InvalidFunction { value }),
        }
    }
}

/// Port of FEFF `FndSng`: find real self-energy integrand singularities.
///
/// `limits` are the lower and upper integration limits. `dp_parameters`
/// corresponds to FEFF `DPPar(1:4)`, with `DPPar(1)` as `Wp/EFermi` and
/// `DPPar(3)` as `Energy/EFermi`. `complex_parameters` corresponds to
/// `CPar(1:2)`, where `CPar(1)` is `ck/kFermi`.
pub fn find_self_energy_singularities(
    limits: [Complex; 2],
    dp_parameters: [Real; 4],
    complex_parameters: [Complex; 2],
    function: SingularityFunction,
) -> Result<Vec<Real>, SelfEnergyError> {
    ensure_finite_complex("lower limit", limits[0])?;
    ensure_finite_complex("upper limit", limits[1])?;
    ensure_finite_complex("CPar(1)", complex_parameters[0])?;
    ensure_finite_complex("CPar(2)", complex_parameters[1])?;
    for (index, &value) in dp_parameters.iter().enumerate() {
        ensure_finite_real(dp_name(index), value)?;
    }

    let k = complex_parameters[0];
    let energy = dp_parameters[2];
    let plasma = dp_parameters[0];
    let lower = limits[0].re;
    let upper = limits[1].re;
    let mut singularities = Vec::new();

    let base_cubic = [
        4.0 * k,
        2.0 * (3.0 * k * k - energy - 2.0 / 3.0),
        4.0 * k * (k * k - energy),
        (k * k - energy) * (k * k - energy) - plasma * plasma,
    ];

    let plus_roots = cubic_zeros(base_cubic)?;
    singularities.extend(
        plus_roots
            .roots()
            .iter()
            .copied()
            .filter(|&root| accepts_cubic_root(k, energy, plasma, root, true, lower, upper))
            .map(|root| root.re),
    );

    let minus_roots = cubic_zeros([-base_cubic[0], base_cubic[1], -base_cubic[2], base_cubic[3]])?;
    singularities.extend(
        minus_roots
            .roots()
            .iter()
            .copied()
            .filter(|&root| accepts_cubic_root(k, energy, plasma, root, false, lower, upper))
            .map(|root| root.re),
    );

    if function == SingularityFunction::First {
        let roots = quadratic_zeros([
            Complex::new(1.0, 0.0),
            Complex::new(4.0 / 3.0, 0.0),
            Complex::new(plasma * plasma, 0.0),
        ])?;
        for &root in roots.roots() {
            if root.im.abs() <= SINGULARITY_TOLERANCE {
                let square_root = root.sqrt();
                let positive = square_root.re;
                let negative = -square_root.re;
                if positive >= lower && positive <= upper {
                    singularities.push(positive);
                }
                if negative >= lower && negative <= upper {
                    singularities.push(negative);
                }
            }
        }
    }

    sort_like_feff(&mut singularities);
    Ok(singularities)
}

/// Port of FEFF `Omegaq`: plasmon dispersion frequency.
///
/// `plasma_frequency` is FEFF `Wp` and `momentum_transfer` is FEFF `q`.
/// FEFF's source writes `2/7` in the final radicand; Fortran evaluates that as
/// integer zero, so the Rust port preserves the same compatibility behavior.
pub fn omega_q(plasma_frequency: Real, momentum_transfer: Real) -> Result<Real, SelfEnergyError> {
    ensure_positive_real("Wp", plasma_frequency)?;
    ensure_positive_real("q", momentum_transfer)?;

    let q = momentum_transfer;
    let wp = plasma_frequency;
    let log_argument = 2.0 + q;
    if log_argument <= 0.0 || !log_argument.is_finite() {
        return Err(SelfEnergyError::NonPositiveReal {
            name: "Omegaq log argument",
            value: log_argument,
        });
    }

    let denominator = 4.0 * q * (8.0 * q.powi(2) + 3.0 * wp.powi(2))
        - 3.0
            * (q + 2.0)
            * wp.powi(2)
            * ((q - 2.0) * log_argument.ln() - x_log_x((q - 2.0).abs())?.re);
    if denominator == 0.0 {
        return Err(SelfEnergyError::ZeroDenominator {
            name: "Omegaq inverse moment",
        });
    }

    let inverse_moment = (std::f64::consts::PI / 2.0) * (32.0 * q.powi(3) / denominator - 1.0);
    ensure_finite_real("Omegaq inverse moment", inverse_moment)?;
    if inverse_moment == 0.0 {
        return Err(SelfEnergyError::ZeroDenominator {
            name: "Omegaq moment",
        });
    }

    let radicand = -(std::f64::consts::PI * wp.powi(2)) / (2.0 * inverse_moment);
    if radicand < 0.0 || !radicand.is_finite() {
        return Err(SelfEnergyError::NegativeRadicand {
            name: "Omegaq",
            value: radicand,
        });
    }
    Ok(radicand.sqrt())
}

/// Port of FEFF `Gamq`: momentum-dependent broadening.
///
/// FEFF uses a default-real `2.4` literal here; the Rust port keeps that rounded
/// value before evaluating the double-precision square root.
pub fn gamma_q(base_width: Real, momentum_transfer: Real) -> Result<Real, SelfEnergyError> {
    ensure_nonnegative_real("gam0", base_width)?;
    ensure_nonnegative_real("q", momentum_transfer)?;

    let radicand = base_width.powi(2) + (2.4_f32 as Real) * momentum_transfer.powi(2);
    if radicand < 0.0 || !radicand.is_finite() {
        return Err(SelfEnergyError::NegativeRadicand {
            name: "Gamq",
            value: radicand,
        });
    }
    Ok(radicand.sqrt())
}

/// Port of FEFF `Logi`: imaginary logarithm branch correction.
///
/// FEFF's BPR integrands build complex logarithms from `log(abs(z))` plus this
/// branch term. Only the real part of `argument` selects the branch; `sign`
/// is the FEFF integer multiplier applied to `pi`.
pub fn log_i(argument: Complex, sign: i32) -> Result<Complex, SelfEnergyError> {
    ensure_finite_complex("Logi argument", argument)?;
    let imaginary = if argument.re < 0.0 {
        std::f64::consts::PI * Real::from(sign)
    } else {
        0.0
    };
    Ok(Complex::new(0.0, imaginary))
}

/// Port of FEFF `MkExc`: fit a loss function with a many-pole model.
///
/// `energy` and `loss` are the two columns of FEFF `loss.dat`, in eV for the
/// standalone `eps2exc` path. `static_dielectric` is FEFF `Eps0`: values in
/// `(-1.5, 0)` select the metallic normalization, values greater than `1`
/// select dielectric scaling, and other values leave the total strength
/// unchanged. The returned poles are the rows FEFF writes to `exc.dat`.
pub fn make_excitation_poles(
    energy: ArrayView1<'_, Real>,
    loss: ArrayView1<'_, Real>,
    static_dielectric: Real,
    requested_poles: usize,
) -> Result<Vec<ExcitationPole>, SelfEnergyError> {
    validate_loss_grid(energy, loss, static_dielectric, requested_poles)?;

    let fine_grid = fine_loss_grid(energy, loss)?;
    let total_inverse_moment = inverse_loss_moment(&fine_grid.energy, &fine_grid.loss);
    ensure_positive_real("MkExc total inverse loss moment", total_inverse_moment)?;
    let target_inverse_moment = total_inverse_moment / requested_poles as Real;

    let mut drafts = Vec::with_capacity(requested_poles);
    let mut segment_start = 0;
    let mut first_moment = 0.0;
    let mut inverse_moment = 0.0;

    for index in 0..fine_grid.energy.len() - 1 {
        inverse_moment += inverse_loss_interval(&fine_grid.energy, &fine_grid.loss, index);
        first_moment += first_loss_interval(&fine_grid.energy, &fine_grid.loss, index);

        if inverse_moment >= target_inverse_moment || index == fine_grid.energy.len() - 2 {
            drafts.push(make_pole_draft(
                &fine_grid.energy,
                segment_start,
                index,
                first_moment,
                inverse_moment,
            )?);
            segment_start = index + 1;
            first_moment = 0.0;
            inverse_moment = 0.0;
        }

        if drafts.len() >= requested_poles {
            break;
        }
    }

    scale_excitation_poles(drafts, static_dielectric)
}

struct FineLossGrid {
    energy: Vec<Real>,
    loss: Vec<Real>,
}

#[derive(Clone, Copy)]
struct ExcitationPoleDraft {
    energy: Real,
    amplitude: Real,
    width: Real,
}

fn validate_loss_grid(
    energy: ArrayView1<'_, Real>,
    loss: ArrayView1<'_, Real>,
    static_dielectric: Real,
    requested_poles: usize,
) -> Result<(), SelfEnergyError> {
    if energy.len() != loss.len() {
        return Err(SelfEnergyError::LossGridLengthMismatch {
            energy_len: energy.len(),
            loss_len: loss.len(),
        });
    }
    if energy.len() < 2 {
        return Err(SelfEnergyError::InsufficientLossGrid { len: energy.len() });
    }
    if requested_poles == 0 {
        return Err(SelfEnergyError::InvalidPoleCount);
    }
    ensure_finite_real("Eps0", static_dielectric)?;

    for (index, (&energy_value, &loss_value)) in energy.iter().zip(loss.iter()).enumerate() {
        ensure_positive_real("loss energy", energy_value)?;
        ensure_nonnegative_real("loss value", loss_value)?;
        if index > 0 {
            let previous = energy[index - 1];
            if energy_value <= previous {
                return Err(SelfEnergyError::NonIncreasingLossEnergy {
                    index,
                    previous,
                    current: energy_value,
                });
            }
        }
    }

    let fine_span = energy[energy.len() - 1].min(1000.0) - energy[0];
    ensure_positive_real("MkExc fine-grid span", fine_span)
}

fn fine_loss_grid(
    energy: ArrayView1<'_, Real>,
    loss: ArrayView1<'_, Real>,
) -> Result<FineLossGrid, SelfEnergyError> {
    let energy_values = energy.to_vec();
    let loss_values = loss.to_vec();
    let step = (energy_values[energy_values.len() - 1].min(1000.0) - energy_values[0])
        / MKEXC_FINE_POINTS as Real;
    let first_energy = energy_values[0];
    let first_loss = loss_values[0];

    let fine_energy: Vec<_> = (0..MKEXC_FINE_POINTS)
        .map(|index| step * index as Real)
        .collect();
    let fine_loss = fine_energy
        .iter()
        .map(|&value| {
            if value > first_energy {
                Ok(terp(&energy_values, &loss_values, 1, value)?.value)
            } else {
                Ok(value * first_loss / first_energy)
            }
        })
        .collect::<Result<Vec<_>, SelfEnergyError>>()?;

    Ok(FineLossGrid {
        energy: fine_energy,
        loss: fine_loss,
    })
}

fn make_pole_draft(
    fine_energy: &[Real],
    segment_start: usize,
    index: usize,
    first_moment: Real,
    inverse_moment: Real,
) -> Result<ExcitationPoleDraft, SelfEnergyError> {
    if inverse_moment == 0.0 {
        return Err(SelfEnergyError::ZeroMoment {
            name: "MkExc segment inverse loss moment",
        });
    }
    let radicand = first_moment / inverse_moment;
    if radicand < 0.0 || !radicand.is_finite() {
        return Err(SelfEnergyError::NegativeRadicand {
            name: "MkExc pole energy",
            value: radicand,
        });
    }
    let width = fine_energy[index + 1] - fine_energy[segment_start];
    ensure_positive_real("MkExc pole width", width)?;

    Ok(ExcitationPoleDraft {
        energy: radicand.sqrt(),
        amplitude: 2.0 * inverse_moment / std::f64::consts::PI,
        width,
    })
}

fn scale_excitation_poles(
    drafts: Vec<ExcitationPoleDraft>,
    static_dielectric: Real,
) -> Result<Vec<ExcitationPole>, SelfEnergyError> {
    let total_amplitude = drafts.iter().map(|pole| pole.amplitude).sum::<Real>();
    if total_amplitude == 0.0 {
        return Err(SelfEnergyError::ZeroMoment {
            name: "MkExc total pole amplitude",
        });
    }

    let scale = if static_dielectric > -1.5 && static_dielectric < 0.0 {
        1.0 / total_amplitude
    } else if static_dielectric > 1.0 {
        (1.0 - 1.0 / static_dielectric) / total_amplitude
    } else {
        1.0
    };
    ensure_positive_real("MkExc pole scale", scale)?;
    let scale_root = scale.sqrt();

    drafts
        .into_iter()
        .map(|draft| {
            let energy = draft.energy / scale_root;
            let amplitude = scale * draft.amplitude;
            let loss_height = std::f64::consts::FRAC_PI_2 * amplitude * energy / draft.width;
            ensure_finite_real("MkExc pole energy", energy)?;
            ensure_finite_real("MkExc pole amplitude", amplitude)?;
            ensure_finite_real("MkExc pole height", loss_height)?;
            Ok(ExcitationPole {
                energy,
                width: MKEXC_WIDTH_EV,
                amplitude,
                loss_height,
            })
        })
        .collect()
}

fn inverse_loss_moment(fine_energy: &[Real], fine_loss: &[Real]) -> Real {
    (0..fine_energy.len() - 1)
        .map(|index| inverse_loss_interval(fine_energy, fine_loss, index))
        .sum()
}

fn inverse_loss_interval(fine_energy: &[Real], fine_loss: &[Real], index: usize) -> Real {
    if fine_energy[index] != 0.0 {
        0.5 * (fine_loss[index + 1] / fine_energy[index + 1]
            + fine_loss[index] / fine_energy[index])
            * (fine_energy[index + 1] - fine_energy[index])
    } else {
        fine_loss[index + 1]
    }
}

fn first_loss_interval(fine_energy: &[Real], fine_loss: &[Real], index: usize) -> Real {
    0.5 * (fine_loss[index + 1] * fine_energy[index + 1] + fine_loss[index] * fine_energy[index])
        * (fine_energy[index + 1] - fine_energy[index])
}

fn accepts_cubic_root(
    k: Complex,
    energy: Real,
    plasma: Real,
    root: Complex,
    positive_branch: bool,
    lower: Real,
    upper: Real,
) -> bool {
    let radical = (root * root * root * root + root * root * (4.0 / 3.0) + plasma * plasma).sqrt();
    let test = if positive_branch {
        ((k + root) * (k + root) - energy + radical).norm()
    } else {
        ((k - root) * (k - root) - energy - radical).norm()
    };

    test < SINGULARITY_TOLERANCE
        && root.re >= lower
        && root.re <= upper
        && root.im.abs() <= SINGULARITY_TOLERANCE
}

fn sort_like_feff(values: &mut [Real]) {
    values.sort_by(|left, right| {
        if left < right {
            Ordering::Less
        } else if left > right {
            Ordering::Greater
        } else {
            Ordering::Equal
        }
    });
}

fn ensure_finite_complex(name: &'static str, value: Complex) -> Result<(), SelfEnergyError> {
    if value.re.is_finite() && value.im.is_finite() {
        Ok(())
    } else {
        Err(SelfEnergyError::NonFiniteComplex { name, value })
    }
}

fn ensure_finite_real(name: &'static str, value: Real) -> Result<(), SelfEnergyError> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(SelfEnergyError::NonFiniteReal { name, value })
    }
}

fn ensure_positive_real(name: &'static str, value: Real) -> Result<(), SelfEnergyError> {
    ensure_finite_real(name, value)?;
    if value > 0.0 {
        Ok(())
    } else {
        Err(SelfEnergyError::NonPositiveReal { name, value })
    }
}

fn ensure_nonnegative_real(name: &'static str, value: Real) -> Result<(), SelfEnergyError> {
    ensure_finite_real(name, value)?;
    if value >= 0.0 {
        Ok(())
    } else {
        Err(SelfEnergyError::NegativeReal { name, value })
    }
}

fn dp_name(index: usize) -> &'static str {
    match index {
        0 => "DPPar(1)",
        1 => "DPPar(2)",
        2 => "DPPar(3)",
        _ => "DPPar(4)",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_no_singularities_for_feff_empty_window_case() -> Result<(), SelfEnergyError> {
        let values = find_self_energy_singularities(
            [Complex::new(0.0, 0.0), Complex::new(4.0, 0.0)],
            [0.5, 0.01, 1.0, 0.0],
            [Complex::new(1.0, 0.0), Complex::new(0.0, 0.0)],
            SingularityFunction::Second,
        )?;

        assert!(values.is_empty());
        Ok(())
    }

    #[test]
    fn omega_q_and_gamma_q_match_feff_reference() -> Result<(), SelfEnergyError> {
        assert_real_close(omega_q(0.7, 0.2)?, 0.709_685_489_669_779_9);
        assert_real_close(omega_q(0.35, 1.4)?, 2.066_779_772_595_223_3);
        assert_real_close(omega_q(1.1, 2.0)?, 3.446_254_004_954_751_4);
        assert_real_close(gamma_q(0.08, 0.2)?, 0.320_000_005_960_464_46);
        assert_real_close(gamma_q(0.12, 1.4)?, 2.172_187_880_207_457);
        Ok(())
    }

    #[test]
    fn omega_q_and_gamma_q_reject_invalid_inputs() {
        assert!(matches!(
            omega_q(0.0, 0.2),
            Err(SelfEnergyError::NonPositiveReal { name: "Wp", .. })
        ));
        assert!(matches!(
            omega_q(0.7, 0.0),
            Err(SelfEnergyError::NonPositiveReal { name: "q", .. })
        ));
        assert!(matches!(
            gamma_q(-0.1, 0.2),
            Err(SelfEnergyError::NegativeReal { name: "gam0", .. })
        ));
        assert!(matches!(
            gamma_q(0.1, Real::NAN),
            Err(SelfEnergyError::NonFiniteReal { name: "q", .. })
        ));
    }

    #[test]
    fn log_i_matches_feff_reference() -> Result<(), SelfEnergyError> {
        assert_complex_close(
            log_i(Complex::new(-1.0, 0.5), -1)?,
            Complex::new(-0.0, -std::f64::consts::PI),
        );
        assert_complex_close(
            log_i(Complex::new(-1.0, 0.5), 1)?,
            Complex::new(0.0, std::f64::consts::PI),
        );
        assert_complex_close(log_i(Complex::new(0.0, -2.0), 1)?, Complex::new(0.0, 0.0));
        assert_complex_close(log_i(Complex::new(2.0, -1.0), -1)?, Complex::new(0.0, 0.0));
        Ok(())
    }

    #[test]
    fn log_i_rejects_invalid_inputs() {
        assert!(matches!(
            log_i(Complex::new(Real::NAN, 0.0), 1),
            Err(SelfEnergyError::NonFiniteComplex {
                name: "Logi argument",
                ..
            })
        ));
    }

    #[test]
    fn make_excitation_poles_matches_feff_reference() -> Result<(), SelfEnergyError> {
        let energy_a = ndarray::arr1(&[5.0, 12.0, 25.0, 60.0, 120.0, 250.0, 500.0]);
        let loss_a = ndarray::arr1(&[0.18, 0.45, 0.32, 0.20, 0.11, 0.05, 0.02]);
        let case_a = make_excitation_poles(energy_a.view(), loss_a.view(), 12.0, 4)?;
        assert_poles_close(
            &case_a,
            &[
                (
                    4.165_512_009_431_169,
                    0.229_183_902_782_623_38,
                    0.187_235_701_641_844_33,
                ),
                (
                    11.025_700_801_851_542,
                    0.229_299_271_755_288_3,
                    0.456_876_736_589_728_7,
                ),
                (
                    24.194_364_348_638_345,
                    0.229_170_783_294_228_82,
                    0.364_889_139_851_398,
                ),
                (
                    128.605_604_607_891_82,
                    0.229_012_708_834_526_18,
                    0.101_808_025_452_920_42,
                ),
            ],
        );

        let energy_b = ndarray::arr1(&[2.5, 8.0, 18.0, 45.0, 90.0, 160.0]);
        let loss_b = ndarray::arr1(&[0.05, 0.16, 0.40, 0.24, 0.08, 0.03]);
        let case_b = make_excitation_poles(energy_b.view(), loss_b.view(), -1.0, 3)?;
        assert_poles_close(
            &case_b,
            &[
                (
                    5.741_019_682_660_089,
                    0.333_408_628_654_138_84,
                    0.222_079_659_617_889_17,
                ),
                (
                    15.153_714_460_887_954,
                    0.333_333_726_361_256_63,
                    0.508_556_667_140_174_8,
                ),
                (
                    45.301_797_610_056_88,
                    0.333_257_644_984_604_6,
                    0.184_756_013_234_317_15,
                ),
            ],
        );

        let case_c = make_excitation_poles(energy_a.view(), loss_a.view(), -2.0, 5)?;
        assert_poles_close(
            &case_c,
            &[
                (
                    3.720_822_084_245_034_6,
                    0.147_763_245_532_865_18,
                    0.134_207_458_306_101_28,
                ),
                (
                    9.737_854_565_244_156,
                    0.147_704_464_410_052_1,
                    0.360_527_069_673_214_5,
                ),
                (
                    17.277_436_390_886_596,
                    0.147_715_268_479_413_24,
                    0.398_169_894_810_244,
                ),
                (
                    35.184_447_871_741_21,
                    0.147_712_703_984_404_6,
                    0.287_023_624_934_877_54,
                ),
                (
                    158.585_550_889_797_47,
                    0.147_547_484_169_155,
                    0.082_822_840_220_122_9,
                ),
            ],
        );
        Ok(())
    }

    #[test]
    fn make_excitation_poles_rejects_invalid_inputs() {
        let energy = ndarray::arr1(&[1.0, 2.0]);
        let loss = ndarray::arr1(&[0.1, 0.2]);
        assert!(matches!(
            make_excitation_poles(energy.view(), loss.view(), 1.0, 0),
            Err(SelfEnergyError::InvalidPoleCount)
        ));

        let short_loss = ndarray::arr1(&[0.1]);
        assert!(matches!(
            make_excitation_poles(energy.view(), short_loss.view(), 1.0, 1),
            Err(SelfEnergyError::LossGridLengthMismatch { .. })
        ));

        let non_increasing = ndarray::arr1(&[1.0, 1.0]);
        assert!(matches!(
            make_excitation_poles(non_increasing.view(), loss.view(), 1.0, 1),
            Err(SelfEnergyError::NonIncreasingLossEnergy { index: 1, .. })
        ));

        let negative_loss = ndarray::arr1(&[0.1, -0.2]);
        assert!(matches!(
            make_excitation_poles(energy.view(), negative_loss.view(), 1.0, 1),
            Err(SelfEnergyError::NegativeReal {
                name: "loss value",
                ..
            })
        ));
    }

    #[test]
    fn finds_feff_cubic_singularities() -> Result<(), SelfEnergyError> {
        let values = find_self_energy_singularities(
            [Complex::new(-2.0, 0.0), Complex::new(2.0, 0.0)],
            [0.35, 0.02, 0.8, 0.0],
            [Complex::new(0.7, 0.0), Complex::new(0.0, 0.0)],
            SingularityFunction::Second,
        )?;

        assert_real_slice_close(
            &values,
            &[
                -0.5702425768022866,
                -0.5421244103394355,
                -0.03049911884380313,
            ],
        );
        Ok(())
    }

    #[test]
    fn finds_feff_first_function_singularities() -> Result<(), SelfEnergyError> {
        let values = find_self_energy_singularities(
            [Complex::new(-2.0, 0.0), Complex::new(2.0, 0.0)],
            [0.35, 0.02, 0.8, 0.0],
            [Complex::new(0.7, 0.0), Complex::new(0.0, 0.0)],
            SingularityFunction::First,
        )?;

        assert_real_slice_close(
            &values,
            &[
                -0.5702425768022866,
                -0.5421244103394355,
                -0.03049911884380313,
                0.0,
                -0.0,
                0.0,
                -0.0,
            ],
        );
        Ok(())
    }

    #[test]
    fn rejects_invalid_singularity_inputs() {
        assert_eq!(
            SingularityFunction::try_from(3),
            Err(SelfEnergyError::InvalidFunction { value: 3 })
        );
        assert!(matches!(
            find_self_energy_singularities(
                [Complex::new(f64::NAN, 0.0), Complex::new(2.0, 0.0)],
                [0.35, 0.02, 0.8, 0.0],
                [Complex::new(0.7, 0.0), Complex::new(0.0, 0.0)],
                SingularityFunction::Second,
            ),
            Err(SelfEnergyError::NonFiniteComplex {
                name: "lower limit",
                ..
            })
        ));
    }

    fn assert_complex_close(actual: Complex, expected: Complex) {
        assert!(
            (actual - expected).norm() < 1.0e-14,
            "actual={actual:?} expected={expected:?} diff={}",
            (actual - expected).norm()
        );
    }

    fn assert_real_close(actual: Real, expected: Real) {
        assert!(
            (actual - expected).abs() < 1.0e-12,
            "actual={actual} expected={expected} diff={}",
            (actual - expected).abs()
        );
    }

    fn assert_poles_close(actual: &[ExcitationPole], expected: &[(Real, Real, Real)]) {
        assert_eq!(actual.len(), expected.len());
        for (actual, &(energy, amplitude, loss_height)) in actual.iter().zip(expected.iter()) {
            assert_real_close(actual.energy, energy);
            assert_real_close(actual.width, 0.1);
            assert_real_close(actual.amplitude, amplitude);
            assert_real_close(actual.loss_height, loss_height);
        }
    }

    fn assert_real_slice_close(actual: &[Real], expected: &[Real]) {
        assert_eq!(actual.len(), expected.len());
        for (&actual, &expected) in actual.iter().zip(expected.iter()) {
            assert!(
                (actual - expected).abs() < 1.0e-12,
                "actual={actual} expected={expected}"
            );
            if expected == 0.0 {
                assert_eq!(actual.to_bits(), expected.to_bits());
            }
        }
    }
}
