use super::*;

/// FEFF self-energy integrand selector used by `FndSng`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SingularityFunction {
    /// FEFF `iFcn = 1`: solve both equation families.
    First,
    /// FEFF `iFcn = 2`: solve only the cubic equation family.
    Second,
}

/// One row of FEFF `exc.dat` generated by `MkExc`.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ExcitationPole {
    /// FEFF `Wi`: pole energy in the same units as the input loss grid.
    pub energy: Real,
    /// FEFF writes a fixed broadened-pole width of `0.1`.
    pub width: Real,
    /// FEFF `gi`: pole amplitude after static-dielectric scaling.
    pub amplitude: Real,
    /// Fourth FEFF `exc.dat` column: `pi / 2 * gi * Wi / Delta`.
    pub loss_height: Real,
}

/// Dimensionless inputs for FEFF `SELF/csigma.f90` integrand kernels.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SelfEnergyIntegrandInput {
    /// FEFF integration variable `q`.
    pub q: Complex,
    /// FEFF `CPar(1)`: `ck / kFermi`.
    pub normalized_momentum: Complex,
    /// FEFF `CPar(2)`: energy divided by Fermi energy.
    pub normalized_energy: Complex,
    /// FEFF `DPPar(1)`: pole energy divided by Fermi energy.
    pub plasmon_over_fermi: Real,
    /// FEFF `DPPar(2)`: broadening divided by Fermi energy.
    pub width_over_fermi: Real,
    /// FEFF `DPPar(4)`: gap energy in Fermi-energy units.
    pub gap_energy: Real,
}

/// Result from FEFF `cgratr`, the adaptive complex quadrature routine.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CgratrIntegral {
    /// Accumulated complex integral value.
    pub value: Complex,
    /// FEFF `error`: accumulated absolute difference between local estimates.
    pub estimated_error: Real,
    /// FEFF `numcal`: number of integrand evaluations.
    pub evaluations: usize,
    /// FEFF `maxns`: maximum number of active regions on the stack.
    pub max_regions: usize,
}

/// Error returned by self-energy singularity helpers.
#[derive(Debug, Clone, PartialEq, thiserror::Error)]
pub enum SelfEnergyError {
    /// FEFF only defines singularity selectors `1` and `2`.
    #[error("invalid self-energy singularity function {value}; expected 1 or 2")]
    InvalidFunction { value: i32 },
    /// Inputs must have finite real and imaginary parts.
    #[error("self-energy input {name} must be finite, got {value:?}")]
    NonFiniteComplex { name: &'static str, value: Complex },
    /// Inputs must be finite real values.
    #[error("self-energy input {name} must be finite, got {value}")]
    NonFiniteReal { name: &'static str, value: Real },
    /// Inputs used as positive scales must be strictly positive.
    #[error("self-energy input {name} must be positive, got {value}")]
    NonPositiveReal { name: &'static str, value: Real },
    /// Inputs used as nonnegative values must be zero or positive.
    #[error("self-energy input {name} must be nonnegative, got {value}")]
    NegativeReal { name: &'static str, value: Real },
    /// Integration tolerances must be strictly positive.
    #[error("self-energy tolerance {name} must be positive, got {value}")]
    NonPositiveTolerance { name: &'static str, value: Real },
    /// FEFF integration bounds must form a finite nonzero interval.
    #[error("self-energy integration interval must be nonzero: lower={lower:?} upper={upper:?}")]
    InvalidIntegrationInterval { lower: Complex, upper: Complex },
    /// FEFF `cgratr` stores at most 20 explicit split points.
    #[error("self-energy integration received {count} split points; maximum is {max}")]
    TooManySingularities { count: usize, max: usize },
    /// Explicit split points must be finite, ordered, and inside the interval.
    #[error("invalid self-energy split point {index}: {value}")]
    InvalidSingularity { index: usize, value: Real },
    /// FEFF `cgratr` exhausted its fixed region stack.
    #[error("self-energy adaptive integration exceeded {max_regions} active regions")]
    TooManyIntegrationRegions { max_regions: usize },
    /// Loss grids must contain matching energy and loss columns.
    #[error(
        "self-energy loss grid length mismatch: energy has {energy_len} values but loss has {loss_len}"
    )]
    LossGridLengthMismatch { energy_len: usize, loss_len: usize },
    /// FEFF `MkExc` needs at least two loss-grid points for linear interpolation.
    #[error("self-energy loss grid requires at least 2 points, got {len}")]
    InsufficientLossGrid { len: usize },
    /// `MkExc` must be asked for at least one pole.
    #[error("requested excitation pole count must be positive")]
    InvalidPoleCount,
    /// FEFF loss grids are monotonic energy tables.
    #[error(
        "self-energy loss-grid energy must increase strictly at index {index}: previous={previous}, current={current}"
    )]
    NonIncreasingLossEnergy {
        index: usize,
        previous: Real,
        current: Real,
    },
    /// A loss-grid moment that FEFF divides by became zero.
    #[error("self-energy moment {name} is zero")]
    ZeroMoment { name: &'static str },
    /// A computed real square-root radicand fell outside the FEFF branch.
    #[error("self-energy radicand {name} must be nonnegative, got {value}")]
    NegativeRadicand { name: &'static str, value: Real },
    /// FEFF formula denominator is singular for this input.
    #[error("self-energy denominator {name} is zero")]
    ZeroDenominator { name: &'static str },
    /// A special-function helper failed.
    #[error(transparent)]
    SpecialFunction(#[from] SpecialFunctionError),
    /// Polynomial root solving failed.
    #[error(transparent)]
    Root(#[from] RootError),
    /// FEFF interpolation failed while processing a loss grid.
    #[error(transparent)]
    Interpolation(#[from] InterpolationError),
}

impl TryFrom<i32> for SingularityFunction {
    type Error = SelfEnergyError;

    fn try_from(value: i32) -> Result<Self, Self::Error> {
        match value {
            1 => Ok(Self::First),
            2 => Ok(Self::Second),
            value => Err(SelfEnergyError::InvalidFunction { value }),
        }
    }
}
