[package]
name = "refeff-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ndarray.workspace = true
num-complex.workspace = true
refeff-core = { path = "../refeff-core" }
refeff-io = { path = "../refeff-io" }
refeff-linalg = { path = "../refeff-linalg" }

[dev-dependencies]
tempfile.workspace = true

[[bin]]
name = "refeff"
path = "src/bin/refeff.rs"

[[bin]]
name = "feff"
path = "src/bin/feff.rs"

[[bin]]
name = "rdinp"
path = "src/bin/rdinp.rs"

[[bin]]
name = "pot"
path = "src/bin/pot.rs"
