#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::todo,
    clippy::unimplemented
)]

use criterion::{Criterion, black_box, criterion_group, criterion_main};
use ndarray::{Array1, Array2, Array3, Array4, Array6, ShapeBuilder, arr1, arr2, array};
use num_complex::Complex32;
use refeff_core::{
    AtomicCoulombCoefficientInput, AtomicDifferentialIntegralInput, AtomicDifferentialIntegralKind,
    AtomicDiracAbnormalExitRecoveryInput, AtomicDiracEnergyDisagreementCorrectionInput,
    AtomicDiracEnergyDisagreementMatchInput, AtomicDiracEnergyDisagreementSourceInput,
    AtomicDiracEnergyStepInput, AtomicDiracEntryStateInput, AtomicDiracHomogeneousMatchInput,
    AtomicDiracHomogeneousPassSetupInput, AtomicDiracHomogeneousSeedInput,
    AtomicDiracInhomogeneousBranchInput, AtomicDiracInhomogeneousSeedInput,
    AtomicDiracIntegrationInput, AtomicDiracIntegrationMode, AtomicDiracIterationResetInput,
    AtomicDiracLargeComponentMatchInput, AtomicDiracMatchingPointUpdateInput,
    AtomicDiracMethodOneEnergyCorrectionInput, AtomicDiracNodeCountInput,
    AtomicDiracNodeEnergySearchInput, AtomicDiracNormalizationInput,
    AtomicDiracRematchAttemptInput, AtomicDiracShootingPassSetupInput,
    AtomicDiracSolutionNormalizationInput, AtomicDiracSolverSetupInput,
    AtomicDiracTwoComponentMatchInput, AtomicFormFactorInput, AtomicLagrangeParametersInput,
    AtomicLocalDensityExchangeMode, AtomicLocalDensityPotentialInput, AtomicNuclearPotentialInput,
    AtomicOrbitalInitializationInput, AtomicOrbitalPotentialInput,
    AtomicOverlapAmplitudeReductionInput, AtomicQuantitiesGridInput, AtomicRadialIntegralInput,
    AtomicRadialIntegralRequest, AtomicSchmidtIntegralRequest, AtomicSchmidtOrthogonalizationInput,
    AtomicTabulationInput, AtomicTabulationIntegralRequest, AtomicTotalEnergyInput,
    AtomicYkZkExchangeInput, AtomicYkZkPreparedSourceInput, AtomicYkZkTransformInput,
    BasisTransformMode, BravaisLattice, BroydenMixInput, BroydenWorkspace, Complex,
    ComptonGridInput, ComptonProfileInput, ComptonRhoZzpInput, ComptonWindow,
    CoulombPotentialSlwInput, CoulombPotentialUpdateInput, CoulombUpdateMode,
    CurvedWavePolynomialInput, DiracSpinorGridInput, DiracSpinorOrbitalsGridInput,
    DmdwPathDescriptor, DmdwPhononCoupling, DmdwPoleWeightedA2f, DmdwType2AtomGroup,
    EelsAngularDependenceInput, EelsCollectionDependenceInput, EelsGosInput, EelsMeshInput,
    EelsMeshMode, EelsQMeshInput, EelsReadSpectrumInput, EelsReadSpectrumSource, EelsSpectrumInput,
    EnergyIndependentMatrixInput, EpsilonTable, FEFF_BOHR_ANGSTROM, FermiLevelInput,
    Ff2xAtanCorrectionInput, Ff2xExcitationConvolutionInput, FmsAtom, FmsBiCgStabInput,
    FmsDriverSetupInput, FmsFreePropagatorInput, FmsFreePropagatorMatrixInput,
    FmsFullPotentialLuInput, FmsGravesMorrisInput, FmsIterativeSystemInput, FmsLuInput,
    FmsRealSpaceEnergyInput, FmsRecursionInput, FmsRotationDirection, FmsScatteringInput,
    FmsScatteringMethod, FmsSpinFreePropagatorMatrixInput, FmsTMatrixInput, FmsTMatrixTableInput,
    FmsTfqmrInput, FmsYprepClusterInput, FprimeContourIntegralInput, FprimeLogCase,
    FprimePositiveAxisIntegralInput, FullSpectrumBackgroundInput,
    FullSpectrumBackgroundSegmentInput, FullSpectrumDefaultGridEdge, FullSpectrumDrudeInput,
    FullSpectrumEdgeAssemblyInput, FullSpectrumEdgeGridInput, FullSpectrumEdgeSelectionInput,
    FullSpectrumFineStructureInput, FullSpectrumFineStructureSegmentInput,
    FullSpectrumHamakerInput, FullSpectrumKramersKronigInput, FullSpectrumLinearGridInput,
    FullSpectrumNumberDensityInput, FullSpectrumOpticalConstantsInput, FullSpectrumQSumInput,
    FullSpectrumScatteringDielectricInput, FullSpectrumSumRulesInput, FullSpectrumValenceInput,
    GenfmtLegendreNormalizationInput, HydrogenBondAdjustmentInput, InitialStateRotationInput,
    InterstitialShellValuesInput, LambdaIndexInput, LoucksSphericalOverlapInput, MinimumBracket,
    MkgtrGreenTraceInput, MuffinTinOverlapMatrixInput, MuffinTinOverlapNeighbor,
    MuffinTinOverlapProjectionInput, MuffinTinOverlapProjectionMode, NormanRadiusInput,
    OverlapDensityIndicesInput, PathCanonicalRepresentationInput, PathCriteriaDecisionInput,
    PathOutputCriterionInput, PathOutputImportanceInput, PathPhaseCriteriaInput, PathRotationInput,
    PathStandardCoordinatesInput, PolarizationTensorMode, PolarizedScatteringAmplitudeInput,
    PotentialGridInput, PotentialOverlapInput, PotentialOverlapNeighbor, RhorrpAtomicDensityInput,
    RhorrpDensityGridInput, RhorrpDensityIntegrationInput, RhorrpEnergyDensityInput,
    RhorrpEnergyPrefactorInput, RhorrpFermiDistributionInput, RhorrpFmsInclusionInput,
    RhorrpIrregularFixInput, RhorrpNearestAtomInput, RhorrpNearestAtomTableInput,
    RhorrpPairDensityInput, RhorrpPairEnergyDensityInput, RhorrpRadialInterpolationInput,
    RhorrpRadialInterpolationLocation, RhorrpSameSiteGreenInput, RhorrpScatteringGreenInput,
    RhorrpWavefunctionInterpolationInput, ScatteringAmplitudeMatrixInput, ScmtEnergyGridInput,
    ScreenCrpaProjectionWindow, ScreenCrpaResponseSliceInput, ScreenEnergyStateInput,
    ScreenExactRadialContinuationInput, ScreenFmsResponseSliceInput, ScreenGetphRadialBoundsInput,
    ScreenIrregularInitialConditionInput, ScreenIrregularWronskianScaleInput,
    ScreenPhasePotentialInput, ScreenRadialBoundsInput, ScreenRdgeomAtomicUnitsInput,
    ScreenSolutionNormalizationInput, SelfEnergyIntegrandInput, SfconvExafsConvolutionInput,
    SfconvExtrinsicSatelliteSplitInput, SfconvFeffPathInterpolationInput,
    SfconvFeffPathSignalInput, SfconvMomentumSpectralInterpolationInput, SfconvPathAverageInput,
    SfconvPhotoelectronMomentumInput, SfconvQuasiparticlePeakInput, SfconvQuasiparticleTableInput,
    SfconvSatelliteContext, SfconvSatelliteCorrectionInput, SfconvSatelliteTableInput,
    SfconvSelfEnergyContext, SfconvSo2convExafsEnergyPaddingInput,
    SfconvSo2convExafsPreparationInput, SfconvSo2convMaterialInput,
    SfconvSo2convXanesPreparationInput, SfconvSpectralInterpolationInput,
    SfconvSpectralWeightsInput, SfconvXanesConvolutionInput, SingularityFunction, StateKet,
    TransitionBMatrix, TransitionBMatrixInput, TransitionRotationInput, ValenceDensityUpdateInput,
    XStarInput, XsphAxafsInput, XsphHoleOrbitalInput, XsphLgSpectrumUpdateInput,
    XsphLjSpectrumUpdateInput, XsphPhaseEnergyMesh84Input, XsphPhaseUserGridInput,
    XsphPhaseUserGridKind, XsphPhaseUserGridMinimum, XsphPhaseUserGridRecord,
    XsphPhaseUserRegularGrid, XsphSpectrumUpdateMode, XsphThermalPhaseEnergyMeshInput,
    adjust_hydrogen_bonds, atomic_breit_angular_coefficients, atomic_convergence_mix,
    atomic_coulomb_coefficients, atomic_differential_integral, atomic_dirac_abnormal_exit_recovery,
    atomic_dirac_energy_disagreement_correction, atomic_dirac_energy_disagreement_match,
    atomic_dirac_energy_disagreement_source, atomic_dirac_energy_step, atomic_dirac_entry_state,
    atomic_dirac_homogeneous_match, atomic_dirac_homogeneous_pass_setup,
    atomic_dirac_homogeneous_seed, atomic_dirac_inhomogeneous_branch,
    atomic_dirac_inhomogeneous_seed, atomic_dirac_integration, atomic_dirac_iteration_reset,
    atomic_dirac_large_component_match, atomic_dirac_matching_point_update,
    atomic_dirac_method_one_energy_correction, atomic_dirac_node_count,
    atomic_dirac_node_energy_search, atomic_dirac_normalization, atomic_dirac_rematch_attempt,
    atomic_dirac_shooting_pass_setup, atomic_dirac_solution_normalization,
    atomic_dirac_solver_setup, atomic_dirac_two_component_match, atomic_direct_coulomb_coefficient,
    atomic_exchange_coulomb_coefficient, atomic_form_factor, atomic_lagrange_parameters,
    atomic_local_density_potential, atomic_nuclear_potential, atomic_occupation_product,
    atomic_orbital_initialization, atomic_orbital_potential, atomic_overlap_amplitude_reduction,
    atomic_polynomial_product_coefficient, atomic_radial_integral,
    atomic_schmidt_orthogonalization, atomic_tabulation, atomic_total_energy,
    atomic_yk_zk_exchange, atomic_yk_zk_prepared_source, atomic_yk_zk_transform,
    basis_transform_matrices, besjh, besjn, bilinear_interpolate_complex, bracket_table_minimum,
    brent_derivative_minimum, brent_table_minimum, cgratr, change_basis_representation,
    change_cartesian_basis, classical_debye_correlation, combine_epsilon_tables,
    compton_build_grid, compton_jzzp, compton_profile, compton_profiles, compton_rhozzp_slice,
    compton_rotation_axis_angle, construct_state_kets, conv, coulomb_potential_slw, csommjas,
    cubic_zeros, curved_wave_polynomials, define_k_path, depressed_quartic_roots,
    dirac_hara_exchange_potential, distance_between, dmdw_expand_path_descriptor,
    dmdw_moment_summaries_from_poles, dmdw_self_energy_grid_from_a2f_poles,
    dmdw_spectral_function_from_a2f_poles, dmdw_type2_pole_weighted_a2f, eels_angular_dependence,
    eels_collection_angle_dependence, eels_euler_rotation_matrix,
    eels_generalized_oscillator_strength, eels_integration_mesh, eels_product_matrix_vector,
    eels_qmesh, eels_read_spectrum, eels_spectrum, elam_edge_energy_hartree,
    electron_wavelength_atomic_units, energy_independent_transition_matrix, exjlnl,
    ff2x_atan_correction, ff2x_excitation_convolve, find_self_energy_singularities,
    fix_atomic_quantities_grid, fix_dirac_spinor_grid, fix_dirac_spinor_orbitals_grid,
    fix_potential_grid, fms_bicgstab_scattering, fms_driver_setup, fms_free_propagator_element,
    fms_free_propagator_matrix, fms_full_potential_lu_scattering, fms_graves_morris_scattering,
    fms_iterative_system_matrix, fms_lu_scattering, fms_pair_tables, fms_real_space_energy,
    fms_recursion_scattering, fms_rotation_matrix, fms_scattering, fms_spin_free_propagator_matrix,
    fms_spin_pair_tables, fms_t_matrix_element, fms_t_matrix_table, fms_tfqmr_scattering,
    fms_yprep_cluster, fms_yprep_geometry, fprime_contour_integral, fprime_log_correction,
    fprime_positive_axis_integral, full_spectrum_assemble_edge,
    full_spectrum_background_from_fprime, full_spectrum_default_energy_grid,
    full_spectrum_drude_term, full_spectrum_edge_energy_grid, full_spectrum_edges_from_occupations,
    full_spectrum_effective_electron_count, full_spectrum_elam_edge_energies,
    full_spectrum_fine_structure_from_segments, full_spectrum_hamaker_transform,
    full_spectrum_kramers_kronig, full_spectrum_linear_energy_grid, full_spectrum_number_density,
    full_spectrum_optical_constants, full_spectrum_scattering_to_dielectric,
    full_spectrum_sum_rules, full_spectrum_valence_epsilon2, gamma_q, gauss_legendre_quadrature,
    genfmt_legendre_normalization_table, hartree_fock_exchange, hedin_lundqvist_ffq,
    hedin_lundqvist_imaginary_self_energy, hedin_lundqvist_self_energy, initial_state_rotation,
    integrated_double_lorentz, interpolation_polynomial_coefficients, interstitial_fermi_level,
    interstitial_shell_values, karasiev_sjostrom_dufty_trickey_vxc, kk_integral,
    kmesh_arbitrary_mesh, kmesh_basis_divisions, kmesh_bravais_basis, kmesh_tetrahedron_division,
    kmesh_tetrahedron_records, lambda_indices, legendre_normalization_table, legendre_polynomials,
    lint, log_i, make_excitation_poles, mix_broyden_density, mkgtr_clebsch_gordan_coefficients,
    mkgtr_green_trace, morse_einstein_cumulants, muffin_tin_overlap_matrix,
    muffin_tin_phase_amplitude, next_elam_edge_hartree, norman_radius_from_density, nuclear_mass,
    omega_q, overlap_density_indices, overlap_potential_density, pack_path_indices,
    pair_polar_angles, path_canonical_representation, path_criteria_decision, path_degeneracy_hash,
    path_geometry, path_heap_bubble_down, path_heap_bubble_up, path_heap_criterion,
    path_output_criterion, path_output_importance, path_output_parameters,
    path_phase_criteria_tables, path_rotation_angles, path_standard_coordinates, perdew_zunger_vxc,
    perrot_dharma_wardana_vxc, point_group_operations, polarization_tensor,
    polarized_scattering_amplitude_matrix, previous_elam_edge_hartree, project_muffin_tin_overlap,
    qsortd_order_1based, quadratic_zeros, quantum_debye_correlation, quantum_debye_waller_factor,
    quinn_imaginary_self_energy, real_polynomial_roots, reciprocal_lattice_vectors,
    reciprocal_metric, redefine_lattice_symmetry_operations, reduce_kmesh_common_divisor,
    reduce_kmesh_irreducible_points, reduce_to_lattice_cell, rehr_albers_polynomials,
    rehr_albers_z_axis_propagator, relativistic_clebsch_gordan_coefficients,
    relativistic_state_index_1based, rhorrp_atomic_density, rhorrp_density_grid_points,
    rhorrp_energy_prefactor, rhorrp_evaluate_density_grid, rhorrp_fermi_distribution,
    rhorrp_finish_energy_density, rhorrp_fix_irregular_origin, rhorrp_fms_inclusion_counts,
    rhorrp_integrate_density, rhorrp_interpolate_wavefunction, rhorrp_nearest_atom,
    rhorrp_nearest_atom_table, rhorrp_pair_density, rhorrp_pair_energy_density,
    rhorrp_process_ranges, rhorrp_radial_interpolation_location, rhorrp_same_site_green,
    rhorrp_scattering_green, scattering_amplitude_matrix, scmt_energy_grid,
    screen_atomic_response_slice, screen_bare_core_hole_potential, screen_coulomb_kernel_matrix,
    screen_crpa_density_weights, screen_crpa_hubbard_summary, screen_crpa_orbital_density,
    screen_crpa_response_slice, screen_energy_integration_delta, screen_energy_state,
    screen_exact_radial_continuation, screen_fms_cluster_green_trace, screen_fms_response_slice,
    screen_getph_lmax, screen_getph_radial_bounds, screen_integrate_response_step,
    screen_irregular_initial_condition, screen_irregular_wronskian_scale,
    screen_lda_exchange_correlation_kernel, screen_phase_potential_reference_shift,
    screen_radial_bounds, screen_radial_coulomb_potential, screen_radial_grid,
    screen_rdgeom_atomic_units, screen_response_system_matrix, screen_solution_normalization,
    screen_solve_response_potential, screen_symmetrize_response_upper, self_energy_r1_integrand,
    sfconv_correct_satellite_weights, sfconv_exafs_convolution, sfconv_extrinsic_beta,
    sfconv_feff_path_signal, sfconv_grater_integrate, sfconv_imaginary_self_energy,
    sfconv_imaginary_self_energy_derivative, sfconv_interference_satellite,
    sfconv_interpolate_feff_path, sfconv_interpolate_momentum_spectral_function,
    sfconv_interpolate_spectral_function, sfconv_intrinsic_satellite, sfconv_path_average,
    sfconv_plasma_parameters, sfconv_plasmon_threshold_momentum, sfconv_pole_dispersion,
    sfconv_q_limits, sfconv_quasiparticle_main_peak, sfconv_quasiparticle_table,
    sfconv_real_self_energy, sfconv_real_self_energy_derivative, sfconv_satellite_table,
    sfconv_select_pole, sfconv_so2conv_material_parameters, sfconv_so2conv_momentum_grid,
    sfconv_so2conv_pad_exafs_energy_grid, sfconv_so2conv_photoelectron_momentum,
    sfconv_so2conv_prepare_exafs_signal, sfconv_so2conv_prepare_xanes_signal,
    sfconv_spectral_energy_grid, sfconv_spectral_weights, sfconv_split_extrinsic_satellite,
    sfconv_xanes_convolution, somm2, sort_atoms_by_radius, sort_representative_atoms,
    sortid_order_1based, sortii_order_1based, sortir_order_1based, sphere_overlap_lens_volume,
    spherical_harmonics, spin_orbit_coupling_tables, subtract_lattice_translation,
    sum_loucks_spherical_overlap, symmetry_check, terp, terpc, thermal_expansion_cumulants,
    thomas_fermi_density_potential, transform_lapw_symmetry_operations, transition_b_matrix, trap,
    unpack_path_indices, update_coulomb_potential, update_valence_density,
    von_barth_hedin_potential, wigner_rotation, x_log_x, xscorr_arctangent_step,
    xscorr_lorentz_kernel, xsph_angular_density_coefficients, xsph_axafs, xsph_even_energy_mesh,
    xsph_exafs_energy_grid_84, xsph_exponential_energy_mesh, xsph_fprime_energy_grid_84,
    xsph_initial_hole_orbital, xsph_k_energy_mesh, xsph_lj_needed_flags,
    xsph_longitudinal_multipole_factor, xsph_minimize_calculations, xsph_nrixs_transition_weights,
    xsph_occupation_normalization, xsph_phase_energy_mesh_84, xsph_phase_energy_mesh_user,
    xsph_q_bessel_table, xsph_relativistic_multipole_factors, xsph_reverse_energy_grid,
    xsph_sort_energy_grid, xsph_thermal_phase_energy_mesh, xsph_update_nrixs_atom_spectrum,
    xsph_update_nrixs_lg_spectrum, xsph_update_nrixs_lj_spectrum, xsph_vertical_energy_mesh_84,
    xsph_xanes_energy_grid_84, xsph_xes_energy_grid_84, xstar,
};

#[path = "core_tables/angular_state.rs"]
mod angular_state;
#[path = "core_tables/bessel.rs"]
mod bessel;
#[path = "core_tables/compton.rs"]
mod compton;
#[path = "core_tables/convolution.rs"]
mod convolution;
#[path = "core_tables/density.rs"]
mod density;
#[path = "core_tables/fms.rs"]
mod fms;
#[path = "core_tables/fms_realistic.rs"]
mod fms_realistic;
#[path = "core_tables/fprime.rs"]
mod fprime;
#[path = "core_tables/genfmt.rs"]
mod genfmt;
#[path = "core_tables/grid.rs"]
mod grid;
#[path = "core_tables/interpolation.rs"]
mod interpolation;
#[path = "core_tables/kspace.rs"]
mod kspace;
#[path = "core_tables/path.rs"]
mod path;
#[path = "core_tables/quadrature.rs"]
mod quadrature;
#[path = "core_tables/rhorrp.rs"]
mod rhorrp;
#[path = "core_tables/scalar.rs"]
mod scalar;
#[path = "core_tables/sort.rs"]
mod sort;

criterion_group!(
    benches,
    angular_state::bench_angular_tables,
    angular_state::bench_state_kets,
    compton::bench_compton_helpers,
    rhorrp::bench_rhorrp_helpers,
    kspace::bench_kspace_helpers,
    density::bench_density_helpers,
    grid::bench_grid_helpers,
    genfmt::bench_genfmt_helpers,
    interpolation::bench_interpolation,
    quadrature::bench_quadrature,
    bessel::bench_bessel,
    convolution::bench_convolution,
    fprime::bench_fprime_helpers,
    fms::bench_fms,
    fms_realistic::bench_fms_realistic,
    scalar::bench_scalar_helpers,
    sort::bench_sort_helpers,
    path::bench_path_helpers
);
criterion_main!(benches);
